const curatedPlaces = [
 {
  "place": "Meenakshi Amman Temple",
  "state": "Tamil Nadu",
  "district": "Madurai",
  "category": "temple",
  "lat": 9.9195,
  "lng": 78.1193,
  "text": "Iconic twin-towered temple complex dedicated to Meenakshi and Sundareswarar; go before 6am to beat the crowds.",
  "best": "Oct-Mar",
  "id": "meenakshi-amman-temple"
 },
 {
  "place": "Brihadeeswarar Temple",
  "state": "Tamil Nadu",
  "district": "Thanjavur",
  "category": "temple",
  "lat": 10.7828,
  "lng": 79.1318,
  "text": "UNESCO-listed Chola-era temple with a massive granite vimana; visit in the golden evening light.",
  "best": "Nov-Feb",
  "id": "brihadeeswarar-temple"
 },
 {
  "place": "Ramanathaswamy Temple",
  "state": "Tamil Nadu",
  "district": "Rameswaram",
  "category": "temple",
  "lat": 9.2882,
  "lng": 79.3129,
  "text": "Famous for its 1200m corridor of carved pillars and 22 sacred wells inside the temple.",
  "best": "Oct-Mar",
  "id": "ramanathaswamy-temple"
 },
 {
  "place": "Sri Ranganathaswamy Temple",
  "state": "Tamil Nadu",
  "district": "Tiruchirappalli",
  "category": "temple",
  "lat": 10.8624,
  "lng": 78.6897,
  "text": "One of the largest functioning temple complexes in the world, with seven concentric walled prakarams.",
  "best": "Nov-Feb",
  "id": "sri-ranganathaswamy-temple"
 },
 {
  "place": "Nataraja Temple",
  "state": "Tamil Nadu",
  "district": "Chidambaram",
  "category": "temple",
  "lat": 11.3994,
  "lng": 79.6929,
  "text": "Dedicated to Shiva as cosmic dancer; the golden-roofed sanctum is a highlight of Chola temple art.",
  "best": "Nov-Feb",
  "id": "nataraja-temple"
 },
 {
  "place": "Ekambareswarar Temple",
  "state": "Tamil Nadu",
  "district": "Kanchipuram",
  "category": "temple",
  "lat": 12.8433,
  "lng": 79.7,
  "text": "One of the Pancha Bhoota Stalams, with a thousand-year-old mango tree in its courtyard.",
  "best": "Nov-Feb",
  "id": "ekambareswarar-temple"
 },
 {
  "place": "Kailasanathar Temple",
  "state": "Tamil Nadu",
  "district": "Kanchipuram",
  "category": "temple",
  "lat": 12.8309,
  "lng": 79.6924,
  "text": "Oldest surviving structure in Kanchipuram, built by Pallava king Narasimhavarman II.",
  "best": "Nov-Feb",
  "id": "kailasanathar-temple"
 },
 {
  "place": "Varadaraja Perumal Temple",
  "state": "Tamil Nadu",
  "district": "Kanchipuram",
  "category": "temple",
  "lat": 12.8367,
  "lng": 79.7096,
  "text": "Grand Vishnu temple famed for its 100-pillared hall with intricate carvings.",
  "best": "Nov-Feb",
  "id": "varadaraja-perumal-temple"
 },
 {
  "place": "Airavatesvara Temple",
  "state": "Tamil Nadu",
  "district": "Darasuram",
  "category": "temple",
  "lat": 10.9427,
  "lng": 79.3097,
  "text": "Smaller but exquisitely detailed UNESCO Chola temple, part of the Great Living Chola Temples group.",
  "best": "Nov-Feb",
  "id": "airavatesvara-temple"
 },
 {
  "place": "Gangaikonda Cholapuram Temple",
  "state": "Tamil Nadu",
  "district": "Ariyalur",
  "category": "temple",
  "lat": 11.2136,
  "lng": 79.4478,
  "text": "Built by Rajendra Chola I to rival Thanjavur's Big Temple; far fewer crowds, equally impressive carvings.",
  "best": "Nov-Feb",
  "id": "gangaikonda-cholapuram-temple"
 },
 {
  "place": "Vaitheeswaran Koil",
  "state": "Tamil Nadu",
  "district": "Mayiladuthurai",
  "category": "temple",
  "lat": 11.1667,
  "lng": 79.6167,
  "text": "Shiva temple associated with astrology and nadi palm-leaf readings.",
  "best": "Oct-Feb",
  "id": "vaitheeswaran-koil"
 },
 {
  "place": "Arulmigu Dhandayuthapani Temple",
  "state": "Tamil Nadu",
  "district": "Palani",
  "category": "temple",
  "lat": 10.4499,
  "lng": 77.5218,
  "text": "Hilltop Murugan shrine reached by 689 steps, cable car, or winch.",
  "best": "Oct-Mar",
  "id": "arulmigu-dhandayuthapani-temple"
 },
 {
  "place": "Arunachaleswarar Temple",
  "state": "Tamil Nadu",
  "district": "Tiruvannamalai",
  "category": "temple",
  "lat": 12.2253,
  "lng": 79.0691,
  "text": "Massive Shiva temple at the base of Arunachala hill; the Karthigai Deepam festival draws huge crowds.",
  "best": "Nov-Feb",
  "id": "arunachaleswarar-temple"
 },
 {
  "place": "Sripuram Golden Temple",
  "state": "Tamil Nadu",
  "district": "Vellore",
  "category": "temple",
  "lat": 12.8988,
  "lng": 79.1444,
  "text": "A Lakshmi temple covered in gold-plated copper sheets set in landscaped grounds.",
  "best": "Oct-Mar",
  "id": "sripuram-golden-temple"
 },
 {
  "place": "Velankanni Basilica",
  "state": "Tamil Nadu",
  "district": "Nagapattinam",
  "category": "temple",
  "lat": 10.68,
  "lng": 79.8422,
  "text": "Major Christian pilgrimage church, 'Lourdes of the East', busiest during the September festival.",
  "best": "Sep, Oct-Feb",
  "id": "velankanni-basilica"
 },
 {
  "place": "Suchindram Thanumalayan Temple",
  "state": "Tamil Nadu",
  "district": "Kanyakumari",
  "category": "temple",
  "lat": 8.1667,
  "lng": 77.4333,
  "text": "Rare temple honouring the Trimurti together, known for its musical stone pillars.",
  "best": "Nov-Feb",
  "id": "suchindram-thanumalayan-temple"
 },
 {
  "place": "Nellaiappar Temple",
  "state": "Tamil Nadu",
  "district": "Tirunelveli",
  "category": "temple",
  "lat": 8.7284,
  "lng": 77.6958,
  "text": "Twin temple complex with a 1000-pillar hall and musical pillars.",
  "best": "Nov-Feb",
  "id": "nellaiappar-temple"
 },
 {
  "place": "Thiruparankundram Murugan Temple",
  "state": "Tamil Nadu",
  "district": "Madurai",
  "category": "temple",
  "lat": 9.8683,
  "lng": 78.0567,
  "text": "Rock-cut cave temple, one of the six abodes of Murugan.",
  "best": "Oct-Mar",
  "id": "thiruparankundram-murugan-temple"
 },
 {
  "place": "Swamimalai Murugan Temple",
  "state": "Tamil Nadu",
  "district": "Kumbakonam",
  "category": "temple",
  "lat": 10.9686,
  "lng": 79.3067,
  "text": "Where Murugan is believed to have taught Shiva the meaning of Om; famed bronze-casting town nearby.",
  "best": "Nov-Feb",
  "id": "swamimalai-murugan-temple"
 },
 {
  "place": "Jambukeswarar Temple",
  "state": "Tamil Nadu",
  "district": "Tiruchirappalli",
  "category": "temple",
  "lat": 10.8531,
  "lng": 78.7069,
  "text": "Water-element Pancha Bhoota Stalam with a sanctum that stays perpetually damp.",
  "best": "Nov-Feb",
  "id": "jambukeswarar-temple"
 },
 {
  "place": "Rockfort Ucchi Pillayar Temple",
  "state": "Tamil Nadu",
  "district": "Tiruchirappalli",
  "category": "heritage",
  "lat": 10.8253,
  "lng": 78.6958,
  "text": "Ganesh shrine atop a 273-step rock outcrop with sweeping views over the Cauvery.",
  "best": "Nov-Feb",
  "id": "rockfort-ucchi-pillayar-temple"
 },
 {
  "place": "Srivilliputhur Andal Temple",
  "state": "Tamil Nadu",
  "district": "Srivilliputhur",
  "category": "temple",
  "lat": 9.5122,
  "lng": 77.6336,
  "text": "Birthplace shrine of Andal, its tall gopuram appears on the Tamil Nadu state emblem.",
  "best": "Nov-Feb",
  "id": "srivilliputhur-andal-temple"
 },
 {
  "place": "Thiruchendur Murugan Temple",
  "state": "Tamil Nadu",
  "district": "Thoothukudi",
  "category": "temple",
  "lat": 8.4956,
  "lng": 78.1219,
  "text": "Seaside Murugan temple where waves break almost at the temple steps.",
  "best": "Oct-Mar",
  "id": "thiruchendur-murugan-temple"
 },
 {
  "place": "Kutralanathar Temple",
  "state": "Tamil Nadu",
  "district": "Courtallam",
  "category": "temple",
  "lat": 8.9333,
  "lng": 77.2667,
  "text": "Shiva temple beside the Courtallam falls, popular during the monsoon bathing season.",
  "best": "Jun-Sep",
  "id": "kutralanathar-temple"
 },
 {
  "place": "Sivagangai Palace",
  "state": "Tamil Nadu",
  "district": "Sivaganga",
  "category": "heritage",
  "lat": 9.8433,
  "lng": 78.4809,
  "text": "Former seat of the Sivaganga Zamindari with fading but photogenic colonial-era architecture.",
  "best": "Nov-Feb",
  "id": "sivagangai-palace"
 },
 {
  "place": "Pudukkottai Government Museum",
  "state": "Tamil Nadu",
  "district": "Pudukkottai",
  "category": "museum",
  "lat": 10.3833,
  "lng": 78.8167,
  "text": "Small but rich museum of Pallava and Pandya-era sculpture and local natural history.",
  "best": "Nov-Feb",
  "id": "pudukkottai-government-museum"
 },
 {
  "place": "Thirumalai Nayakkar Mahal",
  "state": "Tamil Nadu",
  "district": "Madurai",
  "category": "heritage",
  "lat": 9.9186,
  "lng": 78.1281,
  "text": "17th-century Indo-Saracenic palace famed for its towering stucco-work pillars.",
  "best": "Nov-Feb",
  "id": "thirumalai-nayakkar-mahal"
 },
 {
  "place": "Gandhi Memorial Museum",
  "state": "Tamil Nadu",
  "district": "Madurai",
  "category": "museum",
  "lat": 9.9252,
  "lng": 78.1198,
  "text": "Houses the blood-stained cloth Gandhi wore when he was shot; strong Independence-era exhibits.",
  "best": "Nov-Feb",
  "id": "gandhi-memorial-museum"
 },
 {
  "place": "Keezhadi Excavation Site",
  "state": "Tamil Nadu",
  "district": "Sivaganga",
  "category": "heritage",
  "lat": 9.8167,
  "lng": 78.2333,
  "text": "Ongoing archaeological dig revealing a 2,600-year-old urban Sangam-era settlement.",
  "best": "Nov-Feb",
  "id": "keezhadi-excavation-site"
 },
 {
  "place": "Alagar Kovil",
  "state": "Tamil Nadu",
  "district": "Madurai",
  "category": "temple",
  "lat": 9.9686,
  "lng": 78.2214,
  "text": "Hillside Vishnu temple set against forested slopes, quieter than Madurai's main temple.",
  "best": "Nov-Feb",
  "id": "alagar-kovil"
 },
 {
  "place": "Ooty (Udhagamandalam)",
  "state": "Tamil Nadu",
  "district": "Nilgiris",
  "category": "hill",
  "lat": 11.4102,
  "lng": 76.695,
  "text": "The 'Queen of Hill Stations' - toy train, botanical garden, and a cool climate year-round.",
  "best": "Oct-Jun",
  "id": "ooty-udhagamandalam"
 },
 {
  "place": "Kodaikanal",
  "state": "Tamil Nadu",
  "district": "Dindigul",
  "category": "hill",
  "lat": 10.2381,
  "lng": 77.4892,
  "text": "Star-shaped lake, pine forests, and viewpoints over the Palani hills.",
  "best": "Sep-May",
  "id": "kodaikanal"
 },
 {
  "place": "Yercaud",
  "state": "Tamil Nadu",
  "district": "Salem",
  "category": "hill",
  "lat": 11.7753,
  "lng": 78.2101,
  "text": "A laid-back coffee-growing hill station with a peaceful lake, less crowded than Ooty.",
  "best": "Oct-May",
  "id": "yercaud"
 },
 {
  "place": "Coonoor",
  "state": "Tamil Nadu",
  "district": "Nilgiris",
  "category": "hill",
  "lat": 11.353,
  "lng": 76.7959,
  "text": "Tea-estate town on the Nilgiri toy train route; Sim's Park is a quiet botanical stop.",
  "best": "Sep-May",
  "id": "coonoor"
 },
 {
  "place": "Kotagiri",
  "state": "Tamil Nadu",
  "district": "Nilgiris",
  "category": "hill",
  "lat": 11.4224,
  "lng": 76.8631,
  "text": "Oldest hill station in the Nilgiris, known for the Rangaswamy Pillar viewpoint.",
  "best": "Sep-May",
  "id": "kotagiri"
 },
 {
  "place": "Valparai",
  "state": "Tamil Nadu",
  "district": "Coimbatore",
  "category": "hill",
  "lat": 10.3273,
  "lng": 76.955,
  "text": "Remote tea-and-coffee plateau in the Anamalais with frequent wild elephant sightings.",
  "best": "Oct-Apr",
  "id": "valparai"
 },
 {
  "place": "Yelagiri",
  "state": "Tamil Nadu",
  "district": "Tirupattur",
  "category": "hill",
  "lat": 12.5833,
  "lng": 78.6333,
  "text": "Compact, quiet hill station good for a short weekend trip from Chennai/Bengaluru.",
  "best": "Oct-Mar",
  "id": "yelagiri"
 },
 {
  "place": "Kolli Hills",
  "state": "Tamil Nadu",
  "district": "Namakkal",
  "category": "hill",
  "lat": 11.25,
  "lng": 78.3333,
  "text": "70 hairpin bends lead up to a lesser-visited plateau with waterfalls and millet farms.",
  "best": "Oct-Feb",
  "id": "kolli-hills"
 },
 {
  "place": "Javadi Hills",
  "state": "Tamil Nadu",
  "district": "Tirupattur",
  "category": "hill",
  "lat": 12.5667,
  "lng": 78.85,
  "text": "Offbeat hill range with mango orchards and scattered ancient temples.",
  "best": "Nov-Feb",
  "id": "javadi-hills"
 },
 {
  "place": "Sirumalai",
  "state": "Tamil Nadu",
  "district": "Dindigul",
  "category": "hill",
  "lat": 10.2333,
  "lng": 77.9333,
  "text": "Small hill range near Dindigul known for orange and coffee plantations.",
  "best": "Nov-Feb",
  "id": "sirumalai"
 },
 {
  "place": "Meghamalai (High Wavys)",
  "state": "Tamil Nadu",
  "district": "Theni",
  "category": "hill",
  "lat": 9.75,
  "lng": 77.45,
  "text": "Remote cardamom-and-tea plateau, one of Tamil Nadu's least-visited hill regions.",
  "best": "Oct-Feb",
  "id": "meghamalai-high-wavys"
 },
 {
  "place": "Topslip",
  "state": "Tamil Nadu",
  "district": "Coimbatore",
  "category": "wildlife",
  "lat": 10.5667,
  "lng": 76.85,
  "text": "Gateway to Anamalai Tiger Reserve, popular for jeep safaris and elephant camps.",
  "best": "Nov-Apr",
  "id": "topslip"
 },
 {
  "place": "Doddabetta Peak",
  "state": "Tamil Nadu",
  "district": "Nilgiris",
  "category": "nature",
  "lat": 11.4064,
  "lng": 76.7397,
  "text": "Highest point in the Nilgiris; a telescope house offers views across two states on a clear day.",
  "best": "Sep-May",
  "id": "doddabetta-peak"
 },
 {
  "place": "Pykara Falls & Lake",
  "state": "Tamil Nadu",
  "district": "Nilgiris",
  "category": "waterfall",
  "lat": 11.46,
  "lng": 76.61,
  "text": "Boating lake and a waterfall a short drive from Ooty, popular with day-trippers.",
  "best": "Sep-May",
  "id": "pykara-falls-lake"
 },
 {
  "place": "Silver Cascade Falls",
  "state": "Tamil Nadu",
  "district": "Nilgiris",
  "category": "waterfall",
  "lat": 11.3833,
  "lng": 76.7167,
  "text": "Roadside waterfall on the Coonoor-Kotagiri route, best after monsoon rains.",
  "best": "Jun-Sep",
  "id": "silver-cascade-falls"
 },
 {
  "place": "Kodaikanal Lake",
  "state": "Tamil Nadu",
  "district": "Dindigul",
  "category": "nature",
  "lat": 10.2381,
  "lng": 77.4892,
  "text": "Star-shaped artificial lake; cycling and boating are the classic Kodaikanal activity.",
  "best": "Sep-May",
  "id": "kodaikanal-lake"
 },
 {
  "place": "Ooty Lake",
  "state": "Tamil Nadu",
  "district": "Nilgiris",
  "category": "nature",
  "lat": 11.4025,
  "lng": 76.695,
  "text": "Boating lake bordered by eucalyptus groves, popular at sunset.",
  "best": "Sep-May",
  "id": "ooty-lake"
 },
 {
  "place": "Sim's Park",
  "state": "Tamil Nadu",
  "district": "Coonoor",
  "category": "nature",
  "lat": 11.3556,
  "lng": 76.7967,
  "text": "Terraced botanical garden with rare temperate trees, quieter than Ooty's garden.",
  "best": "Sep-May",
  "id": "sim-s-park"
 },
 {
  "place": "Marina Beach",
  "state": "Tamil Nadu",
  "district": "Chennai",
  "category": "beach",
  "lat": 13.05,
  "lng": 80.2824,
  "text": "One of the world's longest urban beaches; go for sunrise, evening crowds are heavy.",
  "best": "Nov-Feb",
  "id": "marina-beach"
 },
 {
  "place": "Elliot's Beach",
  "state": "Tamil Nadu",
  "district": "Chennai",
  "category": "beach",
  "lat": 12.9988,
  "lng": 80.2717,
  "text": "Quieter than Marina, with cafes nearby in Besant Nagar; good for an evening walk.",
  "best": "Nov-Feb",
  "id": "elliot-s-beach"
 },
 {
  "place": "Mahabalipuram Beach",
  "state": "Tamil Nadu",
  "district": "Chengalpattu",
  "category": "beach",
  "lat": 12.6208,
  "lng": 80.1944,
  "text": "Sits beside the Shore Temple; combine a beach evening with the UNESCO monuments.",
  "best": "Nov-Feb",
  "id": "mahabalipuram-beach"
 },
 {
  "place": "Kanyakumari Beach",
  "state": "Tamil Nadu",
  "district": "Kanyakumari",
  "category": "beach",
  "lat": 8.0883,
  "lng": 77.5385,
  "text": "Where the Arabian Sea, Bay of Bengal and Indian Ocean meet; famous sunrise and sunset point.",
  "best": "Oct-Mar",
  "id": "kanyakumari-beach"
 },
 {
  "place": "Rameswaram Beach",
  "state": "Tamil Nadu",
  "district": "Rameswaram",
  "category": "beach",
  "lat": 9.2876,
  "lng": 79.3129,
  "text": "Calm, shallow waters near the temple town; sacred bathing spot for many pilgrims.",
  "best": "Oct-Mar",
  "id": "rameswaram-beach"
 },
 {
  "place": "Dhanushkodi Beach",
  "state": "Tamil Nadu",
  "district": "Rameswaram",
  "category": "beach",
  "lat": 9.15,
  "lng": 79.4167,
  "text": "Ghost-town beach at India's southeastern tip, devastated by an 1964 cyclone; stunning but remote.",
  "best": "Nov-Feb",
  "id": "dhanushkodi-beach"
 },
 {
  "place": "Poompuhar Beach",
  "state": "Tamil Nadu",
  "district": "Mayiladuthurai",
  "category": "beach",
  "lat": 11.1333,
  "lng": 79.85,
  "text": "Site of the ancient Chola port city, now largely submerged; archaeological museum nearby.",
  "best": "Nov-Feb",
  "id": "poompuhar-beach"
 },
 {
  "place": "Tranquebar (Tharangambadi) Beach",
  "state": "Tamil Nadu",
  "district": "Mayiladuthurai",
  "category": "beach",
  "lat": 11.0294,
  "lng": 79.8483,
  "text": "Former Danish colonial town with a fort right on the beach.",
  "best": "Nov-Feb",
  "id": "tranquebar-tharangambadi-beach"
 },
 {
  "place": "Silver Beach",
  "state": "Tamil Nadu",
  "district": "Cuddalore",
  "category": "beach",
  "lat": 11.7167,
  "lng": 79.7667,
  "text": "Wide, relatively uncrowded beach with a working lighthouse.",
  "best": "Nov-Feb",
  "id": "silver-beach"
 },
 {
  "place": "Manapad Beach",
  "state": "Tamil Nadu",
  "district": "Thoothukudi",
  "category": "beach",
  "lat": 8.4167,
  "lng": 78.0167,
  "text": "Small fishing-village beach with a 16th-century church on a rocky headland.",
  "best": "Nov-Feb",
  "id": "manapad-beach"
 },
 {
  "place": "Mudumalai National Park",
  "state": "Tamil Nadu",
  "district": "Nilgiris",
  "category": "wildlife",
  "lat": 11.5833,
  "lng": 76.6333,
  "text": "Elephant, tiger and gaur territory bordering Bandipur and Wayanad; early-morning safaris are best.",
  "best": "Nov-Apr",
  "id": "mudumalai-national-park"
 },
 {
  "place": "Anamalai Tiger Reserve",
  "state": "Tamil Nadu",
  "district": "Coimbatore",
  "category": "wildlife",
  "lat": 10.4,
  "lng": 76.9333,
  "text": "Rugged reserve around Valparai and Topslip, home to lion-tailed macaques and elephants.",
  "best": "Nov-Apr",
  "id": "anamalai-tiger-reserve"
 },
 {
  "place": "Indira Gandhi Wildlife Sanctuary",
  "state": "Tamil Nadu",
  "district": "Coimbatore",
  "category": "wildlife",
  "lat": 10.45,
  "lng": 76.9167,
  "text": "Core zone of the Anamalais landscape, permits required for deep-forest visits.",
  "best": "Nov-Apr",
  "id": "indira-gandhi-wildlife-sanctuary"
 },
 {
  "place": "Vedanthangal Bird Sanctuary",
  "state": "Tamil Nadu",
  "district": "Chengalpattu",
  "category": "wildlife",
  "lat": 12.5486,
  "lng": 79.8631,
  "text": "One of India's oldest bird sanctuaries; migratory storks and pelicans nest here Nov-Feb.",
  "best": "Nov-Feb",
  "id": "vedanthangal-bird-sanctuary"
 },
 {
  "place": "Point Calimere Wildlife Sanctuary",
  "state": "Tamil Nadu",
  "district": "Nagapattinam",
  "category": "wildlife",
  "lat": 10.2917,
  "lng": 79.85,
  "text": "Coastal sanctuary known for blackbuck and huge flocks of migratory flamingos.",
  "best": "Nov-Feb",
  "id": "point-calimere-wildlife-sanctuary"
 },
 {
  "place": "Mukurthi National Park",
  "state": "Tamil Nadu",
  "district": "Nilgiris",
  "category": "wildlife",
  "lat": 11.3833,
  "lng": 76.5333,
  "text": "High-altitude shola-grassland park protecting the endangered Nilgiri tahr.",
  "best": "Sep-May",
  "id": "mukurthi-national-park"
 },
 {
  "place": "Guindy National Park",
  "state": "Tamil Nadu",
  "district": "Chennai",
  "category": "wildlife",
  "lat": 13.0067,
  "lng": 80.2206,
  "text": "A rare national park within a metro city, home to blackbuck and spotted deer.",
  "best": "Nov-Feb",
  "id": "guindy-national-park"
 },
 {
  "place": "Sathyamangalam Tiger Reserve",
  "state": "Tamil Nadu",
  "district": "Erode",
  "category": "wildlife",
  "lat": 11.5,
  "lng": 77.25,
  "text": "Corridor connecting Nilgiri and Eastern Ghats forests; safaris need advance booking.",
  "best": "Nov-Apr",
  "id": "sathyamangalam-tiger-reserve"
 },
 {
  "place": "Courtallam Falls",
  "state": "Tamil Nadu",
  "district": "Tenkasi",
  "category": "waterfall",
  "lat": 8.9333,
  "lng": 77.2667,
  "text": "The 'Spa of the South'; nine linked falls believed to have medicinal properties, best in monsoon.",
  "best": "Jun-Sep",
  "id": "courtallam-falls"
 },
 {
  "place": "Thirparappu Falls",
  "state": "Tamil Nadu",
  "district": "Kanyakumari",
  "category": "waterfall",
  "lat": 8.3,
  "lng": 77.35,
  "text": "Wide horseshoe waterfall near Kanyakumari with a small Shiva temple beside it.",
  "best": "Jun-Jan",
  "id": "thirparappu-falls"
 },
 {
  "place": "Hogenakkal Falls",
  "state": "Tamil Nadu",
  "district": "Dharmapuri",
  "category": "waterfall",
  "lat": 12.1167,
  "lng": 77.7833,
  "text": "The 'Niagara of India' on the Cauvery, famous for coracle rides through the gorge.",
  "best": "Jul-Dec",
  "id": "hogenakkal-falls"
 },
 {
  "place": "Kumbakkarai Falls",
  "state": "Tamil Nadu",
  "district": "Dindigul",
  "category": "waterfall",
  "lat": 10.1167,
  "lng": 77.5667,
  "text": "Cool, rock-pool waterfall on the way up to Kodaikanal, popular for a quick dip.",
  "best": "Jun-Jan",
  "id": "kumbakkarai-falls"
 },
 {
  "place": "Monkey Falls",
  "state": "Tamil Nadu",
  "district": "Coimbatore",
  "category": "waterfall",
  "lat": 10.4167,
  "lng": 76.9333,
  "text": "Roadside falls near Valparai, named for resident macaques; can get crowded on weekends.",
  "best": "Jun-Dec",
  "id": "monkey-falls"
 },
 {
  "place": "Suruli Falls",
  "state": "Tamil Nadu",
  "district": "Theni",
  "category": "waterfall",
  "lat": 9.9333,
  "lng": 77.4,
  "text": "Seasonal falls near the Kerala border with a ropeway up to a nearby cave temple.",
  "best": "Jun-Sep",
  "id": "suruli-falls"
 },
 {
  "place": "Aliyar Falls & Dam",
  "state": "Tamil Nadu",
  "district": "Coimbatore",
  "category": "waterfall",
  "lat": 10.4667,
  "lng": 76.95,
  "text": "Dam and falls popular for boating, close to the Anamalai foothills.",
  "best": "Nov-Feb",
  "id": "aliyar-falls-dam"
 },
 {
  "place": "Fort St. George",
  "state": "Tamil Nadu",
  "district": "Chennai",
  "category": "heritage",
  "lat": 13.0797,
  "lng": 80.287,
  "text": "First English fortress in India (1644); houses a museum of colonial-era Madras artefacts.",
  "best": "Nov-Feb",
  "id": "fort-st-george"
 },
 {
  "place": "Thanjavur Maratha Palace",
  "state": "Tamil Nadu",
  "district": "Thanjavur",
  "category": "heritage",
  "lat": 10.787,
  "lng": 79.1378,
  "text": "Sprawling palace complex with a Saraswathi Mahal library of rare palm-leaf manuscripts.",
  "best": "Nov-Feb",
  "id": "thanjavur-maratha-palace"
 },
 {
  "place": "Vellore Fort",
  "state": "Tamil Nadu",
  "district": "Vellore",
  "category": "heritage",
  "lat": 12.9186,
  "lng": 79.1325,
  "text": "Well-preserved 16th-century fort with a moat, and site of the 1806 Vellore Mutiny.",
  "best": "Nov-Feb",
  "id": "vellore-fort"
 },
 {
  "place": "Gingee Fort",
  "state": "Tamil Nadu",
  "district": "Villupuram",
  "category": "heritage",
  "lat": 12.2667,
  "lng": 79.4167,
  "text": "Sprawling hill fort once called 'unconquerable' by the Mughals; steep climb, big views.",
  "best": "Nov-Feb",
  "id": "gingee-fort"
 },
 {
  "place": "Danish Fort Tranquebar",
  "state": "Tamil Nadu",
  "district": "Mayiladuthurai",
  "category": "heritage",
  "lat": 11.0289,
  "lng": 79.8489,
  "text": "Fort Dansborg, remnant of a 17th-century Danish trading post right on the shore.",
  "best": "Nov-Feb",
  "id": "danish-fort-tranquebar"
 },
 {
  "place": "Chettinad Mansions",
  "state": "Tamil Nadu",
  "district": "Karaikudi",
  "category": "heritage",
  "lat": 10.0733,
  "lng": 78.7828,
  "text": "Grand, Athangudi-tiled mansions built by the Chettiar merchant community; several open for tours.",
  "best": "Nov-Feb",
  "id": "chettinad-mansions"
 },
 {
  "place": "Padmanabhapuram Palace",
  "state": "Tamil Nadu",
  "district": "Kanyakumari",
  "category": "heritage",
  "lat": 8.2436,
  "lng": 77.3239,
  "text": "Wooden Travancore-era royal palace with intricate murals, technically inside Tamil Nadu near the Kerala border.",
  "best": "Nov-Feb",
  "id": "padmanabhapuram-palace"
 },
 {
  "place": "Government Museum Chennai",
  "state": "Tamil Nadu",
  "district": "Chennai",
  "category": "museum",
  "lat": 13.0694,
  "lng": 80.2578,
  "text": "One of India's oldest museums, with a superb bronze gallery of Chola-era sculpture.",
  "best": "Nov-Feb",
  "id": "government-museum-chennai"
 },
 {
  "place": "DakshinaChitra Heritage Museum",
  "state": "Tamil Nadu",
  "district": "Chennai",
  "category": "museum",
  "lat": 12.8225,
  "lng": 80.2394,
  "text": "Living-museum village of relocated traditional South Indian houses and craft demos.",
  "best": "Nov-Feb",
  "id": "dakshinachitra-heritage-museum"
 },
 {
  "place": "Amirthi Zoological Park",
  "state": "Tamil Nadu",
  "district": "Vellore",
  "category": "wildlife",
  "lat": 12.7833,
  "lng": 78.9833,
  "text": "Small forest zoo and picnic spot in the Javadi foothills.",
  "best": "Nov-Feb",
  "id": "amirthi-zoological-park"
 },
 {
  "place": "Vattakottai Fort",
  "state": "Tamil Nadu",
  "district": "Kanyakumari",
  "category": "heritage",
  "lat": 8.1167,
  "lng": 77.5,
  "text": "Small coastal fort near Kanyakumari with dramatic sea views from its ramparts.",
  "best": "Nov-Mar",
  "id": "vattakottai-fort"
 },
 {
  "place": "Pichavaram Mangrove Forest",
  "state": "Tamil Nadu",
  "district": "Cuddalore",
  "category": "nature",
  "lat": 11.4272,
  "lng": 79.7761,
  "text": "Second-largest mangrove forest in the world; boat rides thread through narrow water channels.",
  "best": "Nov-Feb",
  "id": "pichavaram-mangrove-forest"
 },
 {
  "place": "Muthupet Mangroves",
  "state": "Tamil Nadu",
  "district": "Tiruvarur",
  "category": "nature",
  "lat": 10.3833,
  "lng": 79.4833,
  "text": "Quieter mangrove backwater, good for birdwatching away from the crowds.",
  "best": "Nov-Feb",
  "id": "muthupet-mangroves"
 },
 {
  "place": "Vivekananda Rock Memorial",
  "state": "Tamil Nadu",
  "district": "Kanyakumari",
  "category": "heritage",
  "lat": 8.0778,
  "lng": 77.5533,
  "text": "Memorial on a rock island reached by ferry, off Kanyakumari's southern tip.",
  "best": "Oct-Mar",
  "id": "vivekananda-rock-memorial"
 },
 {
  "place": "Thiruvalluvar Statue",
  "state": "Tamil Nadu",
  "district": "Kanyakumari",
  "category": "heritage",
  "lat": 8.0764,
  "lng": 77.555,
  "text": "133-foot statue of the Tamil poet-saint, beside the Vivekananda Rock.",
  "best": "Oct-Mar",
  "id": "thiruvalluvar-statue"
 },
 {
  "place": "Kallanai (Grand Anicut) Dam",
  "state": "Tamil Nadu",
  "district": "Tiruchirappalli",
  "category": "nature",
  "lat": 10.8167,
  "lng": 79.0333,
  "text": "One of the oldest water-regulation structures still in use, built ~2000 years ago.",
  "best": "Nov-Feb",
  "id": "kallanai-grand-anicut-dam"
 },
 {
  "place": "Mettur Dam",
  "state": "Tamil Nadu",
  "district": "Salem",
  "category": "nature",
  "lat": 11.7833,
  "lng": 77.8,
  "text": "Large reservoir on the Cauvery with a musical fountain and nearby garden.",
  "best": "Nov-Feb",
  "id": "mettur-dam"
 },
 {
  "place": "Krishnagiri Dam",
  "state": "Tamil Nadu",
  "district": "Krishnagiri",
  "category": "nature",
  "lat": 12.5333,
  "lng": 78.2167,
  "text": "Popular weekend picnic reservoir with a park and boating.",
  "best": "Nov-Feb",
  "id": "krishnagiri-dam"
 },
 {
  "place": "Bhavanisagar Dam",
  "state": "Tamil Nadu",
  "district": "Erode",
  "category": "nature",
  "lat": 11.4833,
  "lng": 77.1,
  "text": "One of Asia's largest earthen dams, at the confluence of the Bhavani and Moyar rivers.",
  "best": "Nov-Feb",
  "id": "bhavanisagar-dam"
 },
 {
  "place": "Manimuthar Dam",
  "state": "Tamil Nadu",
  "district": "Tirunelveli",
  "category": "nature",
  "lat": 8.6667,
  "lng": 77.4167,
  "text": "Scenic reservoir at the foot of the Western Ghats with a garden and falls nearby.",
  "best": "Nov-Feb",
  "id": "manimuthar-dam"
 },
 {
  "place": "Samanar Hills",
  "state": "Tamil Nadu",
  "district": "Madurai",
  "category": "heritage",
  "lat": 9.9667,
  "lng": 78.0167,
  "text": "Jain rock-cut beds and inscriptions dating back over 2,000 years.",
  "best": "Nov-Feb",
  "id": "samanar-hills"
 },
 {
  "place": "Vaigai Dam",
  "state": "Tamil Nadu",
  "district": "Theni",
  "category": "nature",
  "lat": 9.9333,
  "lng": 77.5167,
  "text": "Reservoir with a garden and boating facility, popular day trip from Madurai.",
  "best": "Nov-Feb",
  "id": "vaigai-dam"
 },
 {
  "place": "Marina Lighthouse",
  "state": "Tamil Nadu",
  "district": "Chennai",
  "category": "heritage",
  "lat": 13.0447,
  "lng": 80.2822,
  "text": "Working lighthouse with an elevator to a viewing deck over Marina Beach.",
  "best": "Nov-Feb",
  "id": "marina-lighthouse"
 },
 {
  "place": "Vandiyur Mariamman Teppakkulam",
  "state": "Tamil Nadu",
  "district": "Madurai",
  "category": "heritage",
  "lat": 9.9083,
  "lng": 78.1367,
  "text": "Huge temple tank that hosts a spectacular floating festival (Teppotsavam) once a year.",
  "best": "Jan-Feb",
  "id": "vandiyur-mariamman-teppakkulam"
 },
 {
  "place": "Mahamaham Tank",
  "state": "Tamil Nadu",
  "district": "Kumbakonam",
  "category": "heritage",
  "lat": 10.9601,
  "lng": 79.3788,
  "text": "Sacred tank at the centre of Kumbakonam, site of a once-in-12-years mega festival.",
  "best": "Nov-Feb",
  "id": "mahamaham-tank"
 },
 {
  "place": "Papanasam Falls & Temple",
  "state": "Tamil Nadu",
  "district": "Tirunelveli",
  "category": "waterfall",
  "lat": 8.6167,
  "lng": 77.3833,
  "text": "Falls beside an ancient Shiva temple at the edge of the Kalakad-Mundanthurai reserve.",
  "best": "Jun-Jan",
  "id": "papanasam-falls-temple"
 },
 {
  "place": "Manjolai Tea Estate",
  "state": "Tamil Nadu",
  "district": "Tirunelveli",
  "category": "hill",
  "lat": 8.5667,
  "lng": 77.3167,
  "text": "High, remote tea estate deep in the Western Ghats reserve forest; permit-controlled access.",
  "best": "Nov-Feb",
  "id": "manjolai-tea-estate"
 },
 {
  "place": "Bannari Amman Temple",
  "state": "Tamil Nadu",
  "district": "Erode",
  "category": "temple",
  "lat": 11.5333,
  "lng": 77.1167,
  "text": "Popular hilltop goddess temple near the Tamil Nadu-Karnataka border.",
  "best": "Nov-Feb",
  "id": "bannari-amman-temple"
 },
 {
  "place": "Bhavani Sangameswarar Temple",
  "state": "Tamil Nadu",
  "district": "Erode",
  "category": "temple",
  "lat": 11.4472,
  "lng": 77.6836,
  "text": "Temple at the confluence (Triveni Sangamam) of the Cauvery, Bhavani and a mythical third river.",
  "best": "Nov-Feb",
  "id": "bhavani-sangameswarar-temple"
 },
 {
  "place": "Namakkal Anjaneyar Temple",
  "state": "Tamil Nadu",
  "district": "Namakkal",
  "category": "temple",
  "lat": 11.22,
  "lng": 78.165,
  "text": "Home to one of Asia's tallest monolithic Hanuman statues, beside Namakkal Fort.",
  "best": "Nov-Feb",
  "id": "namakkal-anjaneyar-temple"
 },
 {
  "place": "Namakkal Fort",
  "state": "Tamil Nadu",
  "district": "Namakkal",
  "category": "heritage",
  "lat": 11.2214,
  "lng": 78.1667,
  "text": "Rock fort with a Ranganathar temple built right into the hill's caverns.",
  "best": "Nov-Feb",
  "id": "namakkal-fort"
 },
 {
  "place": "Pasupatheeswarar Temple",
  "state": "Tamil Nadu",
  "district": "Karur",
  "category": "temple",
  "lat": 10.9601,
  "lng": 78.0766,
  "text": "Riverside Shiva temple in the textile town of Karur.",
  "best": "Nov-Feb",
  "id": "pasupatheeswarar-temple"
 },
 {
  "place": "Puliyancholai Falls",
  "state": "Tamil Nadu",
  "district": "Tiruchirappalli",
  "category": "waterfall",
  "lat": 10.6167,
  "lng": 78.6167,
  "text": "Seasonal falls with rock pools, a popular monsoon day-trip near Kallanai.",
  "best": "Jul-Oct",
  "id": "puliyancholai-falls"
 },
 {
  "place": "Devanampattinam Beach",
  "state": "Tamil Nadu",
  "district": "Cuddalore",
  "category": "beach",
  "lat": 11.75,
  "lng": 79.7833,
  "text": "Quiet beach with an old lighthouse and Dutch-era cemetery close by.",
  "best": "Nov-Feb",
  "id": "devanampattinam-beach"
 },
 {
  "place": "Melmalayanur Temple",
  "state": "Tamil Nadu",
  "district": "Villupuram",
  "category": "temple",
  "lat": 12.2667,
  "lng": 79.4833,
  "text": "Devi temple known for its dramatic firewalking festival.",
  "best": "Jan-Feb",
  "id": "melmalayanur-temple"
 },
 {
  "place": "Rayakottai Fort",
  "state": "Tamil Nadu",
  "district": "Krishnagiri",
  "category": "heritage",
  "lat": 12.4167,
  "lng": 78.1,
  "text": "Ruined hill fort with panoramic views, an offbeat trek near Krishnagiri.",
  "best": "Nov-Feb",
  "id": "rayakottai-fort"
 },
 {
  "place": "Marudhamalai Temple",
  "state": "Tamil Nadu",
  "district": "Coimbatore",
  "category": "temple",
  "lat": 11.0764,
  "lng": 76.8814,
  "text": "Hilltop Murugan temple overlooking Coimbatore city, reachable by winch or steps.",
  "best": "Nov-Feb",
  "id": "marudhamalai-temple"
 },
 {
  "place": "VOC Park & Zoo",
  "state": "Tamil Nadu",
  "district": "Coimbatore",
  "category": "wildlife",
  "lat": 11.0025,
  "lng": 76.9628,
  "text": "Compact city zoo and park named after freedom fighter V.O. Chidambaram Pillai.",
  "best": "Nov-Feb",
  "id": "voc-park-zoo"
 },
 {
  "place": "Perur Pateeswarar Temple",
  "state": "Tamil Nadu",
  "district": "Coimbatore",
  "category": "temple",
  "lat": 10.9581,
  "lng": 76.9364,
  "text": "Riverside temple famed for its ornate 1000-pillar hall and horse-drawn chariot sculptures.",
  "best": "Nov-Feb",
  "id": "perur-pateeswarar-temple"
 },
 {
  "place": "Black Thunder Water Theme Park",
  "state": "Tamil Nadu",
  "district": "Mettupalayam",
  "category": "adventure",
  "lat": 11.2833,
  "lng": 76.9333,
  "text": "Large water park at the foot of the Nilgiris, a popular family day out.",
  "best": "Nov-May",
  "id": "black-thunder-water-theme-park"
 },
 {
  "place": "Avalanche Lake",
  "state": "Tamil Nadu",
  "district": "Nilgiris",
  "category": "nature",
  "lat": 11.3167,
  "lng": 76.5667,
  "text": "Remote reservoir inside a shola forest reserve near Ooty; permit required to visit.",
  "best": "Sep-May",
  "id": "avalanche-lake"
 },
 {
  "place": "Emerald Lake",
  "state": "Tamil Nadu",
  "district": "Nilgiris",
  "category": "nature",
  "lat": 11.3333,
  "lng": 76.5833,
  "text": "Secluded reservoir close to Avalanche, surrounded by dense shola forest.",
  "best": "Sep-May",
  "id": "emerald-lake"
 },
 {
  "place": "Glenmorgan Viewpoint",
  "state": "Tamil Nadu",
  "district": "Nilgiris",
  "category": "nature",
  "lat": 11.4333,
  "lng": 76.5667,
  "text": "Tea-garden viewpoint on the Ooty-Pykara road, quieter than the main Ooty sights.",
  "best": "Sep-May",
  "id": "glenmorgan-viewpoint"
 },
 {
  "place": "Dindigul Fort",
  "state": "Tamil Nadu",
  "district": "Dindigul",
  "category": "heritage",
  "lat": 10.3556,
  "lng": 77.9603,
  "text": "Rock fort built by Tipu Sultan's forces, offering views over Dindigul town.",
  "best": "Nov-Feb",
  "id": "dindigul-fort"
 },
 {
  "place": "Kalayarkoil Temple",
  "state": "Tamil Nadu",
  "district": "Sivaganga",
  "category": "temple",
  "lat": 9.6667,
  "lng": 78.5833,
  "text": "Shiva temple known for its towering gopuram, one of the tallest in the region.",
  "best": "Nov-Feb",
  "id": "kalayarkoil-temple"
 },
 {
  "place": "Ramanathapuram Palace",
  "state": "Tamil Nadu",
  "district": "Ramanathapuram",
  "category": "heritage",
  "lat": 9.3639,
  "lng": 78.8395,
  "text": "Former Sethupathi kingdom palace with a small museum of royal artefacts.",
  "best": "Nov-Feb",
  "id": "ramanathapuram-palace"
 },
 {
  "place": "Our Lady of Snows Basilica",
  "state": "Tamil Nadu",
  "district": "Thoothukudi",
  "category": "temple",
  "lat": 8.7642,
  "lng": 78.1348,
  "text": "Coastal Catholic basilica overlooking the harbour town of Thoothukudi.",
  "best": "Nov-Feb",
  "id": "our-lady-of-snows-basilica"
 },
 {
  "place": "Hare Island",
  "state": "Tamil Nadu",
  "district": "Thoothukudi",
  "category": "nature",
  "lat": 8.8,
  "lng": 78.1667,
  "text": "Small coral-fringed island reachable by boat, popular for snorkelling day trips.",
  "best": "Dec-Mar",
  "id": "hare-island"
 },
 {
  "place": "Muttom Beach",
  "state": "Tamil Nadu",
  "district": "Kanyakumari",
  "category": "beach",
  "lat": 8.1333,
  "lng": 77.3167,
  "text": "Rocky, dramatic coastline with a lighthouse, quieter than Kanyakumari town.",
  "best": "Oct-Mar",
  "id": "muttom-beach"
 },
 {
  "place": "Nagore Dargah",
  "state": "Tamil Nadu",
  "district": "Nagapattinam",
  "category": "temple",
  "lat": 10.8167,
  "lng": 79.85,
  "text": "Major Sufi shrine drawing pilgrims of multiple faiths, famous for its annual Kanduri festival.",
  "best": "Year-round",
  "id": "nagore-dargah"
 },
 {
  "place": "San Thome Basilica",
  "state": "Tamil Nadu",
  "district": "Chennai",
  "category": "heritage",
  "lat": 13.0336,
  "lng": 80.2775,
  "text": "Built over the tomb of St. Thomas the Apostle, one of only three churches worldwide on an apostle's burial site.",
  "best": "Nov-Feb",
  "id": "san-thome-basilica"
 },
 {
  "place": "Vadapalani Murugan Temple",
  "state": "Tamil Nadu",
  "district": "Chennai",
  "category": "temple",
  "lat": 13.0503,
  "lng": 80.2122,
  "text": "Busy neighbourhood Murugan temple, a major stop for the film industry crowd nearby.",
  "best": "Year-round",
  "id": "vadapalani-murugan-temple"
 },
 {
  "place": "Valluvar Kottam",
  "state": "Tamil Nadu",
  "district": "Chennai",
  "category": "heritage",
  "lat": 13.0522,
  "lng": 80.2425,
  "text": "Chariot-shaped monument housing a giant statue of poet Thiruvalluvar.",
  "best": "Nov-Feb",
  "id": "valluvar-kottam"
 },
 {
  "place": "Semmozhi Poonga",
  "state": "Tamil Nadu",
  "district": "Chennai",
  "category": "nature",
  "lat": 13.0569,
  "lng": 80.2497,
  "text": "Landscaped botanical park in the middle of the city, a peaceful green break.",
  "best": "Nov-Feb",
  "id": "semmozhi-poonga"
 },
 {
  "place": "Arignar Anna Zoological Park",
  "state": "Tamil Nadu",
  "district": "Chennai",
  "category": "wildlife",
  "lat": 12.8836,
  "lng": 80.0919,
  "text": "One of South Asia's largest zoos, at Vandalur on Chennai's outskirts.",
  "best": "Nov-Feb",
  "id": "arignar-anna-zoological-park"
 },
 {
  "place": "Shore Temple & Five Rathas",
  "state": "Tamil Nadu",
  "district": "Mahabalipuram",
  "category": "heritage",
  "lat": 12.6169,
  "lng": 80.1929,
  "text": "UNESCO rock-cut monuments including monolithic chariot temples and Arjuna's Penance relief.",
  "best": "Nov-Feb",
  "id": "shore-temple-five-rathas"
 },
 {
  "place": "Kamakshi Amman Temple",
  "state": "Tamil Nadu",
  "district": "Kanchipuram",
  "category": "temple",
  "lat": 12.8353,
  "lng": 79.6989,
  "text": "One of the Shakti Peethas, dedicated to the goddess Kamakshi.",
  "best": "Nov-Feb",
  "id": "kamakshi-amman-temple"
 },
 {
  "place": "Ooty Rose Garden",
  "state": "Tamil Nadu",
  "district": "Nilgiris",
  "category": "nature",
  "lat": 11.4183,
  "lng": 76.7133,
  "text": "Terraced garden with thousands of rose varieties on a hillside above town.",
  "best": "Sep-May",
  "id": "ooty-rose-garden"
 },
 {
  "place": "Kotagiri Catherine Falls",
  "state": "Tamil Nadu",
  "district": "Nilgiris",
  "category": "waterfall",
  "lat": 11.45,
  "lng": 76.85,
  "text": "Two-tier waterfall near Kotagiri with a viewpoint just off the main road.",
  "best": "Jun-Sep",
  "id": "kotagiri-catherine-falls"
 },
 {
  "place": "Alleppey Backwaters",
  "state": "Kerala",
  "district": "Alappuzha",
  "category": "backwater",
  "lat": 9.4981,
  "lng": 76.3388,
  "text": "The classic Kerala houseboat cruise through palm-fringed canals and paddy fields.",
  "best": "Oct-Mar",
  "id": "alleppey-backwaters"
 },
 {
  "place": "Kumarakom Backwaters",
  "state": "Kerala",
  "district": "Kottayam",
  "category": "backwater",
  "lat": 9.618,
  "lng": 76.43,
  "text": "Vembanad lakeside village known for houseboats and its bird sanctuary.",
  "best": "Nov-Feb",
  "id": "kumarakom-backwaters"
 },
 {
  "place": "Kuttanad",
  "state": "Kerala",
  "district": "Alappuzha",
  "category": "backwater",
  "lat": 9.3833,
  "lng": 76.4167,
  "text": "'The Rice Bowl of Kerala' - farmland lying below sea level, criss-crossed by canals.",
  "best": "Oct-Feb",
  "id": "kuttanad"
 },
 {
  "place": "Ashtamudi Lake",
  "state": "Kerala",
  "district": "Kollam",
  "category": "backwater",
  "lat": 8.95,
  "lng": 76.5833,
  "text": "Second-largest backwater lake in Kerala, gateway to the Kollam-Alleppey houseboat route.",
  "best": "Oct-Mar",
  "id": "ashtamudi-lake"
 },
 {
  "place": "Punnamada Lake",
  "state": "Kerala",
  "district": "Alappuzha",
  "category": "backwater",
  "lat": 9.5667,
  "lng": 76.3667,
  "text": "Venue of the famous Nehru Trophy Snake Boat Race every August.",
  "best": "Aug (race), Oct-Mar",
  "id": "punnamada-lake"
 },
 {
  "place": "Vembanad Lake",
  "state": "Kerala",
  "district": "Alappuzha",
  "category": "backwater",
  "lat": 9.5916,
  "lng": 76.3928,
  "text": "Kerala's longest lake, spanning Alappuzha, Kottayam and Ernakulam districts.",
  "best": "Oct-Mar",
  "id": "vembanad-lake"
 },
 {
  "place": "Munroe Island",
  "state": "Kerala",
  "district": "Kollam",
  "category": "backwater",
  "lat": 8.9333,
  "lng": 76.5833,
  "text": "Cluster of small islands with narrow canoe-only canals, quieter than Alleppey.",
  "best": "Oct-Mar",
  "id": "munroe-island"
 },
 {
  "place": "Kavvayi Backwaters",
  "state": "Kerala",
  "district": "Kannur",
  "category": "backwater",
  "lat": 12.1167,
  "lng": 75.2333,
  "text": "North Kerala's largest backwater system, still relatively undiscovered by tourists.",
  "best": "Oct-Feb",
  "id": "kavvayi-backwaters"
 },
 {
  "place": "Valiyaparamba Backwaters",
  "state": "Kerala",
  "district": "Kasaragod",
  "category": "backwater",
  "lat": 12.3,
  "lng": 75.1833,
  "text": "Island-studded backwater stretch near Bekal, good for a quieter houseboat trip.",
  "best": "Oct-Feb",
  "id": "valiyaparamba-backwaters"
 },
 {
  "place": "Poovar Backwaters",
  "state": "Kerala",
  "district": "Thiruvananthapuram",
  "category": "backwater",
  "lat": 8.3167,
  "lng": 77.0833,
  "text": "Where the backwaters meet the sea near a golden sandbar, close to the capital.",
  "best": "Nov-Feb",
  "id": "poovar-backwaters"
 },
 {
  "place": "Neyyar Dam Reservoir",
  "state": "Kerala",
  "district": "Thiruvananthapuram",
  "category": "backwater",
  "lat": 8.5667,
  "lng": 77.15,
  "text": "Reservoir with a lion safari park and yoga centre nearby.",
  "best": "Nov-Feb",
  "id": "neyyar-dam-reservoir"
 },
 {
  "place": "Malampuzha Dam & Garden",
  "state": "Kerala",
  "district": "Palakkad",
  "category": "backwater",
  "lat": 10.8333,
  "lng": 76.6833,
  "text": "Dam with a large ornamental garden, rock garden and a cable car.",
  "best": "Nov-Feb",
  "id": "malampuzha-dam-garden"
 },
 {
  "place": "Idukki Dam",
  "state": "Kerala",
  "district": "Idukki",
  "category": "backwater",
  "lat": 9.85,
  "lng": 76.9833,
  "text": "One of Asia's tallest arch dams, set in a dramatic mountain gorge.",
  "best": "Nov-Feb",
  "id": "idukki-dam"
 },
 {
  "place": "Mattupetty Dam",
  "state": "Kerala",
  "district": "Idukki",
  "category": "backwater",
  "lat": 10.1,
  "lng": 77.1333,
  "text": "Popular Munnar viewpoint with boating and a nearby Indo-Swiss dairy farm.",
  "best": "Sep-Mar",
  "id": "mattupetty-dam"
 },
 {
  "place": "Kundala Lake",
  "state": "Kerala",
  "district": "Idukki",
  "category": "backwater",
  "lat": 10.1333,
  "lng": 77.1,
  "text": "High-altitude lake near Munnar, good for a short boat ride amid tea gardens.",
  "best": "Sep-Mar",
  "id": "kundala-lake"
 },
 {
  "place": "Munnar",
  "state": "Kerala",
  "district": "Idukki",
  "category": "hill",
  "lat": 10.0889,
  "lng": 77.0595,
  "text": "Rolling tea-garden hills and cool climate; the classic Kerala hill-station trip.",
  "best": "Sep-Mar",
  "id": "munnar"
 },
 {
  "place": "Wayanad (Kalpetta)",
  "state": "Kerala",
  "district": "Wayanad",
  "category": "hill",
  "lat": 11.6854,
  "lng": 76.1319,
  "text": "Misty plateau of spice plantations, caves, and wildlife on the Karnataka border.",
  "best": "Oct-May",
  "id": "wayanad-kalpetta"
 },
 {
  "place": "Thekkady (Periyar)",
  "state": "Kerala",
  "district": "Idukki",
  "category": "hill",
  "lat": 9.5916,
  "lng": 77.16,
  "text": "Spice-plantation hill town beside Periyar Tiger Reserve's lake.",
  "best": "Sep-Mar",
  "id": "thekkady-periyar"
 },
 {
  "place": "Vagamon",
  "state": "Kerala",
  "district": "Idukki",
  "category": "hill",
  "lat": 9.6833,
  "lng": 76.9167,
  "text": "Rolling grassy meadows and pine forests, quieter than Munnar.",
  "best": "Sep-Mar",
  "id": "vagamon"
 },
 {
  "place": "Ponmudi",
  "state": "Kerala",
  "district": "Thiruvananthapuram",
  "category": "hill",
  "lat": 8.75,
  "lng": 77.1167,
  "text": "Closest hill station to the state capital, known for hairpin drives and views.",
  "best": "Sep-Mar",
  "id": "ponmudi"
 },
 {
  "place": "Nelliyampathy",
  "state": "Kerala",
  "district": "Palakkad",
  "category": "hill",
  "lat": 10.65,
  "lng": 76.6833,
  "text": "Orange and coffee estate hills with a viewpoint over the Western Ghats.",
  "best": "Oct-Mar",
  "id": "nelliyampathy"
 },
 {
  "place": "Devikulam",
  "state": "Kerala",
  "district": "Idukki",
  "category": "hill",
  "lat": 10.0833,
  "lng": 77.1,
  "text": "Quiet tea-estate village near Munnar with the Sita Devi Lake.",
  "best": "Sep-Mar",
  "id": "devikulam"
 },
 {
  "place": "Peermade",
  "state": "Kerala",
  "district": "Idukki",
  "category": "hill",
  "lat": 9.5667,
  "lng": 76.9667,
  "text": "Historic plantation town on the old Munnar-Kumily trade route.",
  "best": "Sep-Mar",
  "id": "peermade"
 },
 {
  "place": "Marayoor",
  "state": "Kerala",
  "district": "Idukki",
  "category": "hill",
  "lat": 10.25,
  "lng": 77.1333,
  "text": "Home to Kerala's only natural sandalwood forest and prehistoric dolmens (muniyara).",
  "best": "Sep-Mar",
  "id": "marayoor"
 },
 {
  "place": "Chembra Peak",
  "state": "Kerala",
  "district": "Wayanad",
  "category": "hill",
  "lat": 11.5,
  "lng": 76.1167,
  "text": "Highest peak in Wayanad, famous for its heart-shaped lake reached on a day trek.",
  "best": "Oct-May",
  "id": "chembra-peak"
 },
 {
  "place": "Banasura Hill",
  "state": "Kerala",
  "district": "Wayanad",
  "category": "hill",
  "lat": 11.6667,
  "lng": 75.95,
  "text": "Second-highest peak in the Western Ghats, near the Banasura Sagar earthen dam.",
  "best": "Oct-May",
  "id": "banasura-hill"
 },
 {
  "place": "Gavi",
  "state": "Kerala",
  "district": "Pathanamthitta",
  "category": "hill",
  "lat": 9.4333,
  "lng": 77.15,
  "text": "Remote eco-tourism forest reserve reachable only with Forest Department permits.",
  "best": "Oct-Mar",
  "id": "gavi"
 },
 {
  "place": "Paithalmala",
  "state": "Kerala",
  "district": "Kannur",
  "category": "hill",
  "lat": 12.0333,
  "lng": 75.6167,
  "text": "Trekking hill near the Karnataka border with sweeping Western Ghats views.",
  "best": "Oct-Mar",
  "id": "paithalmala"
 },
 {
  "place": "Ramakkalmedu",
  "state": "Kerala",
  "district": "Idukki",
  "category": "hill",
  "lat": 9.7167,
  "lng": 77.0833,
  "text": "Windy viewpoint with wind turbines, near Kumily and the Tamil Nadu border.",
  "best": "Oct-Mar",
  "id": "ramakkalmedu"
 },
 {
  "place": "Kovalam Beach",
  "state": "Kerala",
  "district": "Thiruvananthapuram",
  "category": "beach",
  "lat": 8.4004,
  "lng": 76.9787,
  "text": "Kerala's original beach resort town, with a lighthouse and three crescent coves.",
  "best": "Nov-Feb",
  "id": "kovalam-beach"
 },
 {
  "place": "Varkala Beach",
  "state": "Kerala",
  "district": "Thiruvananthapuram",
  "category": "beach",
  "lat": 8.7379,
  "lng": 76.7163,
  "text": "Dramatic red laterite cliffs overlooking the Arabian Sea, lined with cafes.",
  "best": "Nov-Feb",
  "id": "varkala-beach"
 },
 {
  "place": "Marari Beach",
  "state": "Kerala",
  "district": "Alappuzha",
  "category": "beach",
  "lat": 9.5978,
  "lng": 76.2967,
  "text": "Quiet fishing-village beach south of Kochi, popular for a low-key resort stay.",
  "best": "Nov-Feb",
  "id": "marari-beach"
 },
 {
  "place": "Cherai Beach",
  "state": "Kerala",
  "district": "Ernakulam",
  "category": "beach",
  "lat": 10.1367,
  "lng": 76.1797,
  "text": "Long beach near Kochi where the backwaters and the sea sit almost side by side.",
  "best": "Nov-Feb",
  "id": "cherai-beach"
 },
 {
  "place": "Bekal Beach",
  "state": "Kerala",
  "district": "Kasaragod",
  "category": "beach",
  "lat": 12.3936,
  "lng": 75.0347,
  "text": "Beach beside Kerala's largest fort, a quieter alternative to the southern beach towns.",
  "best": "Nov-Feb",
  "id": "bekal-beach"
 },
 {
  "place": "Muzhappilangad Drive-in Beach",
  "state": "Kerala",
  "district": "Kannur",
  "category": "beach",
  "lat": 11.7167,
  "lng": 75.5167,
  "text": "One of India's few drive-in beaches, a 4km stretch open to vehicles at low tide.",
  "best": "Nov-Feb",
  "id": "muzhappilangad-drive-in-beach"
 },
 {
  "place": "Kappad Beach",
  "state": "Kerala",
  "district": "Kozhikode",
  "category": "beach",
  "lat": 11.3833,
  "lng": 75.6667,
  "text": "Historic beach where Vasco da Gama first landed in India in 1498.",
  "best": "Nov-Feb",
  "id": "kappad-beach"
 },
 {
  "place": "Payyambalam Beach",
  "state": "Kerala",
  "district": "Kannur",
  "category": "beach",
  "lat": 11.8833,
  "lng": 75.3667,
  "text": "Landscaped city beach with a sculpture park, popular for evening walks.",
  "best": "Nov-Feb",
  "id": "payyambalam-beach"
 },
 {
  "place": "Shanghumukham Beach",
  "state": "Kerala",
  "district": "Thiruvananthapuram",
  "category": "beach",
  "lat": 8.4667,
  "lng": 76.9167,
  "text": "City beach near the airport, known for a giant mermaid sculpture.",
  "best": "Nov-Feb",
  "id": "shanghumukham-beach"
 },
 {
  "place": "Fort Kochi Beach",
  "state": "Kerala",
  "district": "Ernakulam",
  "category": "beach",
  "lat": 9.9658,
  "lng": 76.2422,
  "text": "Beach lined with the iconic Chinese fishing nets; best at sunset.",
  "best": "Nov-Feb",
  "id": "fort-kochi-beach"
 },
 {
  "place": "Alappuzha Beach",
  "state": "Kerala",
  "district": "Alappuzha",
  "category": "beach",
  "lat": 9.49,
  "lng": 76.32,
  "text": "Long pier and beach right by Alappuzha town, near the backwater boat jetties.",
  "best": "Nov-Feb",
  "id": "alappuzha-beach"
 },
 {
  "place": "Thirumullavaram Beach",
  "state": "Kerala",
  "district": "Kollam",
  "category": "beach",
  "lat": 8.9333,
  "lng": 76.5833,
  "text": "Quiet, less commercial beach close to Kollam town.",
  "best": "Nov-Feb",
  "id": "thirumullavaram-beach"
 },
 {
  "place": "Kozhikode Beach",
  "state": "Kerala",
  "district": "Kozhikode",
  "category": "beach",
  "lat": 11.25,
  "lng": 75.7667,
  "text": "City beach with an old pier, popular for evening street food.",
  "best": "Nov-Feb",
  "id": "kozhikode-beach"
 },
 {
  "place": "Meenkunnu Beach",
  "state": "Kerala",
  "district": "Kannur",
  "category": "beach",
  "lat": 11.9333,
  "lng": 75.3667,
  "text": "Rocky, less-visited beach near Payyambalam, good for a quiet walk.",
  "best": "Nov-Feb",
  "id": "meenkunnu-beach"
 },
 {
  "place": "Nattika Beach",
  "state": "Kerala",
  "district": "Thrissur",
  "category": "beach",
  "lat": 10.4167,
  "lng": 75.9833,
  "text": "Uncrowded stretch of coast between Kochi and Thrissur.",
  "best": "Nov-Feb",
  "id": "nattika-beach"
 },
 {
  "place": "Periyar Tiger Reserve",
  "state": "Kerala",
  "district": "Idukki",
  "category": "wildlife",
  "lat": 9.463,
  "lng": 77.238,
  "text": "Boat safaris on Periyar Lake with chances of elephant and bison sightings.",
  "best": "Oct-Apr",
  "id": "periyar-tiger-reserve"
 },
 {
  "place": "Wayanad Wildlife Sanctuary",
  "state": "Kerala",
  "district": "Wayanad",
  "category": "wildlife",
  "lat": 11.6081,
  "lng": 76.3894,
  "text": "Contiguous with Bandipur and Mudumalai, forming one of South India's largest elephant corridors.",
  "best": "Oct-Apr",
  "id": "wayanad-wildlife-sanctuary"
 },
 {
  "place": "Eravikulam National Park",
  "state": "Kerala",
  "district": "Idukki",
  "category": "wildlife",
  "lat": 10.2167,
  "lng": 77.05,
  "text": "Grassy high-altitude park protecting the endangered Nilgiri tahr, near Munnar.",
  "best": "Sep-Mar",
  "id": "eravikulam-national-park"
 },
 {
  "place": "Silent Valley National Park",
  "state": "Kerala",
  "district": "Palakkad",
  "category": "wildlife",
  "lat": 11.0833,
  "lng": 76.4333,
  "text": "One of the last patches of undisturbed tropical rainforest in India.",
  "best": "Nov-Apr",
  "id": "silent-valley-national-park"
 },
 {
  "place": "Parambikulam Tiger Reserve",
  "state": "Kerala",
  "district": "Palakkad",
  "category": "wildlife",
  "lat": 10.4,
  "lng": 76.85,
  "text": "Dense forest reserve with ancient trees and rich biodiversity, permit-based visits.",
  "best": "Nov-Apr",
  "id": "parambikulam-tiger-reserve"
 },
 {
  "place": "Thattekad Bird Sanctuary",
  "state": "Kerala",
  "district": "Ernakulam",
  "category": "wildlife",
  "lat": 10.1333,
  "lng": 76.6167,
  "text": "One of India's richest birding spots, established with Salim Ali's recommendation.",
  "best": "Nov-Mar",
  "id": "thattekad-bird-sanctuary"
 },
 {
  "place": "Kumarakom Bird Sanctuary",
  "state": "Kerala",
  "district": "Kottayam",
  "category": "wildlife",
  "lat": 9.6167,
  "lng": 76.4333,
  "text": "Vembanad-side sanctuary drawing migratory birds alongside resident waterfowl.",
  "best": "Nov-Feb",
  "id": "kumarakom-bird-sanctuary"
 },
 {
  "place": "Chinnar Wildlife Sanctuary",
  "state": "Kerala",
  "district": "Idukki",
  "category": "wildlife",
  "lat": 10.3,
  "lng": 77.1167,
  "text": "Dry scrub sanctuary near Munnar with giant grizzled squirrels and star tortoises.",
  "best": "Nov-Apr",
  "id": "chinnar-wildlife-sanctuary"
 },
 {
  "place": "Neyyar Wildlife Sanctuary",
  "state": "Kerala",
  "district": "Thiruvananthapuram",
  "category": "wildlife",
  "lat": 8.5667,
  "lng": 77.1667,
  "text": "Reserve around the Neyyar Dam with a crocodile farm and lion safari park.",
  "best": "Nov-Feb",
  "id": "neyyar-wildlife-sanctuary"
 },
 {
  "place": "Peppara Wildlife Sanctuary",
  "state": "Kerala",
  "district": "Thiruvananthapuram",
  "category": "wildlife",
  "lat": 8.6667,
  "lng": 77.15,
  "text": "Forest reserve feeding the Peppara reservoir, close to Ponmudi.",
  "best": "Nov-Feb",
  "id": "peppara-wildlife-sanctuary"
 },
 {
  "place": "Athirappilly Falls",
  "state": "Kerala",
  "district": "Thrissur",
  "category": "waterfall",
  "lat": 10.2851,
  "lng": 76.5695,
  "text": "Kerala's largest waterfall, on the Chalakudy river at the edge of Vazhachal forest.",
  "best": "Jun-Jan",
  "id": "athirappilly-falls"
 },
 {
  "place": "Vazhachal Falls",
  "state": "Kerala",
  "district": "Thrissur",
  "category": "waterfall",
  "lat": 10.3167,
  "lng": 76.5667,
  "text": "Wide cascading falls a short drive upstream from Athirappilly.",
  "best": "Jun-Jan",
  "id": "vazhachal-falls"
 },
 {
  "place": "Meenmutty Falls",
  "state": "Kerala",
  "district": "Wayanad",
  "category": "waterfall",
  "lat": 11.6333,
  "lng": 76.0833,
  "text": "Wayanad's largest waterfall, reached by a short forest trek.",
  "best": "Jun-Jan",
  "id": "meenmutty-falls"
 },
 {
  "place": "Soochipara Falls",
  "state": "Kerala",
  "district": "Wayanad",
  "category": "waterfall",
  "lat": 11.5833,
  "lng": 76.1,
  "text": "Three-tiered falls with a natural pool, popular for a supervised swim.",
  "best": "Jun-Jan",
  "id": "soochipara-falls"
 },
 {
  "place": "Thommankuthu Falls",
  "state": "Kerala",
  "district": "Idukki",
  "category": "waterfall",
  "lat": 9.7333,
  "lng": 76.7833,
  "text": "Seven-stage cascading falls, a popular trekking and picnic spot.",
  "best": "Jun-Dec",
  "id": "thommankuthu-falls"
 },
 {
  "place": "Palaruvi Falls",
  "state": "Kerala",
  "district": "Kollam",
  "category": "waterfall",
  "lat": 8.95,
  "lng": 77.15,
  "text": "'Milk waterfall' cascading 300 feet, near the Tamil Nadu border.",
  "best": "Jun-Jan",
  "id": "palaruvi-falls"
 },
 {
  "place": "Thusharagiri Falls",
  "state": "Kerala",
  "district": "Kozhikode",
  "category": "waterfall",
  "lat": 11.3833,
  "lng": 76.0667,
  "text": "Three linked waterfalls set amid dense forest, popular for trekking.",
  "best": "Jun-Jan",
  "id": "thusharagiri-falls"
 },
 {
  "place": "Kanthanpara Falls",
  "state": "Kerala",
  "district": "Wayanad",
  "category": "waterfall",
  "lat": 11.5833,
  "lng": 76.0833,
  "text": "Family-friendly falls with easy access, good for a quick stop.",
  "best": "Jun-Jan",
  "id": "kanthanpara-falls"
 },
 {
  "place": "Cheeyappara Falls",
  "state": "Kerala",
  "district": "Idukki",
  "category": "waterfall",
  "lat": 10.0667,
  "lng": 76.7833,
  "text": "Seven-step roadside falls on the Kochi-Munnar highway.",
  "best": "Jun-Dec",
  "id": "cheeyappara-falls"
 },
 {
  "place": "Valara Falls",
  "state": "Kerala",
  "district": "Idukki",
  "category": "waterfall",
  "lat": 10.0833,
  "lng": 76.7667,
  "text": "Roadside falls just before Cheeyappara on the Munnar route.",
  "best": "Jun-Dec",
  "id": "valara-falls"
 },
 {
  "place": "Vellarimala Falls",
  "state": "Kerala",
  "district": "Kozhikode",
  "category": "waterfall",
  "lat": 11.5,
  "lng": 76.05,
  "text": "Remote falls near the Wayanad border, reached via a forest trek.",
  "best": "Jun-Jan",
  "id": "vellarimala-falls"
 },
 {
  "place": "Bekal Fort",
  "state": "Kerala",
  "district": "Kasaragod",
  "category": "heritage",
  "lat": 12.3936,
  "lng": 75.0347,
  "text": "Kerala's largest fort, a laterite fortress jutting into the Arabian Sea.",
  "best": "Nov-Feb",
  "id": "bekal-fort"
 },
 {
  "place": "Mattancherry Palace (Dutch Palace)",
  "state": "Kerala",
  "district": "Ernakulam",
  "category": "heritage",
  "lat": 9.958,
  "lng": 76.2599,
  "text": "16th-century Portuguese-built palace famous for its Hindu mythological murals.",
  "best": "Nov-Feb",
  "id": "mattancherry-palace-dutch-palace"
 },
 {
  "place": "Hill Palace Tripunithura",
  "state": "Kerala",
  "district": "Ernakulam",
  "category": "heritage",
  "lat": 9.9333,
  "lng": 76.35,
  "text": "Kerala's largest palace complex, once the seat of the Kochi royal family, now a museum.",
  "best": "Nov-Feb",
  "id": "hill-palace-tripunithura"
 },
 {
  "place": "Padmanabhaswamy Temple",
  "state": "Kerala",
  "district": "Thiruvananthapuram",
  "category": "temple",
  "lat": 8.4828,
  "lng": 76.9436,
  "text": "One of the world's richest temples, with a distinctive Dravidian gopuram; strict dress code.",
  "best": "Nov-Feb",
  "id": "padmanabhaswamy-temple"
 },
 {
  "place": "Napier Museum",
  "state": "Kerala",
  "district": "Thiruvananthapuram",
  "category": "museum",
  "lat": 8.5069,
  "lng": 76.9558,
  "text": "Indo-Saracenic building housing bronzes, ivory carvings and a natural history wing.",
  "best": "Nov-Feb",
  "id": "napier-museum"
 },
 {
  "place": "Fort Kochi Heritage Zone",
  "state": "Kerala",
  "district": "Ernakulam",
  "category": "heritage",
  "lat": 9.9658,
  "lng": 76.2422,
  "text": "Walkable colonial-era quarter of Portuguese, Dutch and British era buildings.",
  "best": "Nov-Feb",
  "id": "fort-kochi-heritage-zone"
 },
 {
  "place": "St. Francis Church",
  "state": "Kerala",
  "district": "Ernakulam",
  "category": "heritage",
  "lat": 9.9654,
  "lng": 76.2408,
  "text": "One of the oldest European-built churches in India; Vasco da Gama was buried here.",
  "best": "Nov-Feb",
  "id": "st-francis-church"
 },
 {
  "place": "Santa Cruz Basilica",
  "state": "Kerala",
  "district": "Ernakulam",
  "category": "heritage",
  "lat": 9.9636,
  "lng": 76.2417,
  "text": "Colourful Gothic-style basilica in Fort Kochi with striking painted interiors.",
  "best": "Nov-Feb",
  "id": "santa-cruz-basilica"
 },
 {
  "place": "Paradesi Synagogue",
  "state": "Kerala",
  "district": "Ernakulam",
  "category": "heritage",
  "lat": 9.9578,
  "lng": 76.2597,
  "text": "Oldest active synagogue in the Commonwealth, in Kochi's historic Jew Town.",
  "best": "Nov-Feb (closed Sat)",
  "id": "paradesi-synagogue"
 },
 {
  "place": "Bolgatty Palace",
  "state": "Kerala",
  "district": "Ernakulam",
  "category": "heritage",
  "lat": 9.9958,
  "lng": 76.2664,
  "text": "Former Dutch palace on Bolgatty Island, now a heritage hotel with island views.",
  "best": "Nov-Feb",
  "id": "bolgatty-palace"
 },
 {
  "place": "Krishnapuram Palace",
  "state": "Kerala",
  "district": "Alappuzha",
  "category": "heritage",
  "lat": 9.3333,
  "lng": 76.3667,
  "text": "Palace museum famous for its huge mural of Gajendra Moksham.",
  "best": "Nov-Feb",
  "id": "krishnapuram-palace"
 },
 {
  "place": "Thangassery Fort",
  "state": "Kerala",
  "district": "Kollam",
  "category": "heritage",
  "lat": 8.8833,
  "lng": 76.5833,
  "text": "Ruined Portuguese-Dutch fort and lighthouse on Kollam's coast.",
  "best": "Nov-Feb",
  "id": "thangassery-fort"
 },
 {
  "place": "Chandragiri Fort",
  "state": "Kerala",
  "district": "Kasaragod",
  "category": "heritage",
  "lat": 12.4833,
  "lng": 74.9833,
  "text": "Riverside fort ruins with views over the Chandragiri river estuary.",
  "best": "Nov-Feb",
  "id": "chandragiri-fort"
 },
 {
  "place": "Tellicherry Fort",
  "state": "Kerala",
  "district": "Kannur",
  "category": "heritage",
  "lat": 11.75,
  "lng": 75.4833,
  "text": "British-era fort by the sea in Thalassery, the town famous for its biryani.",
  "best": "Nov-Feb",
  "id": "tellicherry-fort"
 },
 {
  "place": "Kuthiramalika Palace",
  "state": "Kerala",
  "district": "Thiruvananthapuram",
  "category": "heritage",
  "lat": 8.4833,
  "lng": 76.9439,
  "text": "'Palace of Horses' - carved teak palace museum next to Padmanabhaswamy Temple.",
  "best": "Nov-Feb",
  "id": "kuthiramalika-palace"
 },
 {
  "place": "Sabarimala Ayyappa Temple",
  "state": "Kerala",
  "district": "Pathanamthitta",
  "category": "temple",
  "lat": 9.4333,
  "lng": 77.0833,
  "text": "One of the world's largest annual pilgrimages; trek up through forest, season-restricted entry.",
  "best": "Nov-Jan",
  "id": "sabarimala-ayyappa-temple"
 },
 {
  "place": "Guruvayur Krishna Temple",
  "state": "Kerala",
  "district": "Thrissur",
  "category": "temple",
  "lat": 10.5946,
  "lng": 76.0396,
  "text": "One of Kerala's most visited Krishna temples, famous for its elephant sanctuary nearby.",
  "best": "Year-round",
  "id": "guruvayur-krishna-temple"
 },
 {
  "place": "Vaikom Mahadeva Temple",
  "state": "Kerala",
  "district": "Kottayam",
  "category": "temple",
  "lat": 9.75,
  "lng": 76.3958,
  "text": "Ancient Shiva temple linked to the historic 1924 Vaikom Satyagraha.",
  "best": "Nov-Feb",
  "id": "vaikom-mahadeva-temple"
 },
 {
  "place": "Ettumanoor Mahadeva Temple",
  "state": "Kerala",
  "district": "Kottayam",
  "category": "temple",
  "lat": 9.6667,
  "lng": 76.55,
  "text": "Temple famed for its mural paintings and the Ezharaponnana (7.5 golden elephants) festival.",
  "best": "Feb-Mar",
  "id": "ettumanoor-mahadeva-temple"
 },
 {
  "place": "Chottanikkara Temple",
  "state": "Kerala",
  "district": "Ernakulam",
  "category": "temple",
  "lat": 9.9167,
  "lng": 76.3667,
  "text": "Devi temple known for rituals believed to help with mental health afflictions.",
  "best": "Year-round",
  "id": "chottanikkara-temple"
 },
 {
  "place": "Ambalapuzha Sree Krishna Temple",
  "state": "Kerala",
  "district": "Alappuzha",
  "category": "temple",
  "lat": 9.3833,
  "lng": 76.3333,
  "text": "Temple famous for its 'Ambalapuzha Palpayasam' milk-rice offering.",
  "best": "Year-round",
  "id": "ambalapuzha-sree-krishna-temple"
 },
 {
  "place": "Aranmula Parthasarathy Temple",
  "state": "Kerala",
  "district": "Pathanamthitta",
  "category": "temple",
  "lat": 9.3333,
  "lng": 76.5667,
  "text": "Riverside Krishna temple, host to the spectacular Aranmula snake boat race.",
  "best": "Aug-Sep (race)",
  "id": "aranmula-parthasarathy-temple"
 },
 {
  "place": "Thrikkakara Temple",
  "state": "Kerala",
  "district": "Ernakulam",
  "category": "temple",
  "lat": 10.0333,
  "lng": 76.3333,
  "text": "Temple associated with the Onam legend of King Mahabali and Vamana.",
  "best": "Aug-Sep (Onam)",
  "id": "thrikkakara-temple"
 },
 {
  "place": "Attukal Bhagavathy Temple",
  "state": "Kerala",
  "district": "Thiruvananthapuram",
  "category": "temple",
  "lat": 8.4667,
  "lng": 76.95,
  "text": "Holds a Guinness World Record for the largest annual gathering of women (Pongala festival).",
  "best": "Feb-Mar",
  "id": "attukal-bhagavathy-temple"
 },
 {
  "place": "Vadakkunnathan Temple",
  "state": "Kerala",
  "district": "Thrissur",
  "category": "temple",
  "lat": 10.5222,
  "lng": 76.2144,
  "text": "Ancient hilltop Shiva temple at the centre of Thrissur, hosts the famous Thrissur Pooram.",
  "best": "Apr-May (Pooram)",
  "id": "vadakkunnathan-temple"
 },
 {
  "place": "Munnar Tea Museum",
  "state": "Kerala",
  "district": "Idukki",
  "category": "museum",
  "lat": 10.0833,
  "lng": 77.05,
  "text": "Working museum explaining tea processing, with a tasting counter.",
  "best": "Sep-Mar",
  "id": "munnar-tea-museum"
 },
 {
  "place": "Marayoor Sandalwood Forest",
  "state": "Kerala",
  "district": "Idukki",
  "category": "nature",
  "lat": 10.25,
  "lng": 77.1333,
  "text": "Kerala's only natural sandalwood forest, guarded due to past sandal-smuggling.",
  "best": "Sep-Mar",
  "id": "marayoor-sandalwood-forest"
 },
 {
  "place": "Anamudi Peak",
  "state": "Kerala",
  "district": "Idukki",
  "category": "hill",
  "lat": 10.1667,
  "lng": 77.0667,
  "text": "Highest peak in South India, inside Eravikulam National Park; permit trekking only.",
  "best": "Sep-Mar",
  "id": "anamudi-peak"
 },
 {
  "place": "Kuttikkanam",
  "state": "Kerala",
  "district": "Idukki",
  "category": "hill",
  "lat": 9.5833,
  "lng": 76.95,
  "text": "Cardamom-hill town between Peermade and Vagamon, dotted with old colonial bungalows.",
  "best": "Sep-Mar",
  "id": "kuttikkanam"
 },
 {
  "place": "Top Station",
  "state": "Kerala",
  "district": "Idukki",
  "category": "nature",
  "lat": 10.1167,
  "lng": 77.2167,
  "text": "Highest viewpoint above Munnar overlooking the Tamil Nadu plains, famous for rare neelakurinji blooms.",
  "best": "Sep-Mar",
  "id": "top-station"
 },
 {
  "place": "Agasthyakoodam Peak",
  "state": "Kerala",
  "district": "Thiruvananthapuram",
  "category": "hill",
  "lat": 8.6167,
  "lng": 77.2333,
  "text": "Sacred, biodiversity-rich peak with a restricted trekking season and permits.",
  "best": "Dec-Apr",
  "id": "agasthyakoodam-peak"
 },
 {
  "place": "Edakkal Caves",
  "state": "Kerala",
  "district": "Wayanad",
  "category": "heritage",
  "lat": 11.5167,
  "lng": 76.0,
  "text": "Cave with Neolithic-era petroglyphs, reached via a steep rocky climb.",
  "best": "Oct-May",
  "id": "edakkal-caves"
 },
 {
  "place": "Pookode Lake",
  "state": "Kerala",
  "district": "Wayanad",
  "category": "nature",
  "lat": 11.5333,
  "lng": 76.0,
  "text": "Freshwater lake surrounded by forest, with boating and a small aquarium.",
  "best": "Oct-May",
  "id": "pookode-lake"
 },
 {
  "place": "Banasura Sagar Dam",
  "state": "Kerala",
  "district": "Wayanad",
  "category": "backwater",
  "lat": 11.6667,
  "lng": 75.9667,
  "text": "India's largest earthen dam, with boating amid small forested islands.",
  "best": "Oct-May",
  "id": "banasura-sagar-dam"
 },
 {
  "place": "Parassinikadavu Snake Park",
  "state": "Kerala",
  "district": "Kannur",
  "category": "wildlife",
  "lat": 11.9833,
  "lng": 75.4,
  "text": "Snake park beside a riverside temple famous for its Theyyam ritual performances.",
  "best": "Nov-Mar",
  "id": "parassinikadavu-snake-park"
 },
 {
  "place": "Ranipuram",
  "state": "Kerala",
  "district": "Kasaragod",
  "category": "hill",
  "lat": 12.4167,
  "lng": 75.3667,
  "text": "Lesser-known grassy hill and shola forest reserve near the Karnataka border.",
  "best": "Oct-Mar",
  "id": "ranipuram"
 },
 {
  "place": "Thrissur Zoo",
  "state": "Kerala",
  "district": "Thrissur",
  "category": "wildlife",
  "lat": 10.5236,
  "lng": 76.2144,
  "text": "One of India's older zoos, adjacent to the Kerala State Museum.",
  "best": "Nov-Feb",
  "id": "thrissur-zoo"
 },
 {
  "place": "Kalady (Adi Shankara Birthplace)",
  "state": "Kerala",
  "district": "Ernakulam",
  "category": "temple",
  "lat": 10.1667,
  "lng": 76.4333,
  "text": "Riverside pilgrim town marking the birthplace of philosopher Adi Shankaracharya.",
  "best": "Nov-Feb",
  "id": "kalady-adi-shankara-birthplace"
 },
 {
  "place": "Anayirankal Dam",
  "state": "Kerala",
  "district": "Idukki",
  "category": "backwater",
  "lat": 9.9667,
  "lng": 77.1,
  "text": "Quiet reservoir amid tea estates near Munnar, less crowded than Mattupetty.",
  "best": "Sep-Mar",
  "id": "anayirankal-dam"
 },
 {
  "place": "Jatayu Earth's Center",
  "state": "Kerala",
  "district": "Kollam",
  "category": "nature",
  "lat": 8.8167,
  "lng": 76.9167,
  "text": "Rock-hill park with a giant Jatayu bird sculpture and adventure activities.",
  "best": "Nov-Feb",
  "id": "jatayu-earth-s-center"
 },
 {
  "place": "Kanakakunnu Palace",
  "state": "Kerala",
  "district": "Thiruvananthapuram",
  "category": "heritage",
  "lat": 8.5083,
  "lng": 76.9556,
  "text": "Former royal palace and gardens, now a cultural events venue.",
  "best": "Nov-Feb",
  "id": "kanakakunnu-palace"
 },
 {
  "place": "Veli Tourist Village",
  "state": "Kerala",
  "district": "Thiruvananthapuram",
  "category": "nature",
  "lat": 8.4833,
  "lng": 76.8833,
  "text": "Lagoon-side park where a backwater lake meets the sea, with pedal boats.",
  "best": "Nov-Feb",
  "id": "veli-tourist-village"
 },
 {
  "place": "Beypore",
  "state": "Kerala",
  "district": "Kozhikode",
  "category": "heritage",
  "lat": 11.1667,
  "lng": 75.8167,
  "text": "Historic port town famous for its centuries-old wooden Uru (dhow) shipbuilding.",
  "best": "Nov-Feb",
  "id": "beypore"
 },
 {
  "place": "Kadalundi Bird Sanctuary",
  "state": "Kerala",
  "district": "Kozhikode",
  "category": "wildlife",
  "lat": 11.1333,
  "lng": 75.8167,
  "text": "Estuarine sanctuary where migratory shorebirds gather in large numbers.",
  "best": "Nov-Feb",
  "id": "kadalundi-bird-sanctuary"
 },
 {
  "place": "Nilambur Teak Plantations",
  "state": "Kerala",
  "district": "Malappuram",
  "category": "nature",
  "lat": 11.2833,
  "lng": 76.2333,
  "text": "Site of the world's oldest planted teak forest, dating to 1844.",
  "best": "Nov-Mar",
  "id": "nilambur-teak-plantations"
 },
 {
  "place": "Kottakkunnu",
  "state": "Kerala",
  "district": "Malappuram",
  "category": "nature",
  "lat": 11.05,
  "lng": 76.0833,
  "text": "Hillock park with sculptures and gardens overlooking Malappuram town.",
  "best": "Nov-Feb",
  "id": "kottakkunnu"
 },
 {
  "place": "Karlad Lake",
  "state": "Kerala",
  "district": "Wayanad",
  "category": "backwater",
  "lat": 11.6167,
  "lng": 76.1333,
  "text": "Small forest-fringed lake near Kalpetta, good for a quiet boat ride.",
  "best": "Oct-May",
  "id": "karlad-lake"
 },
 {
  "place": "Konni Elephant Camp",
  "state": "Kerala",
  "district": "Pathanamthitta",
  "category": "wildlife",
  "lat": 9.2333,
  "lng": 76.9333,
  "text": "Riverside camp where captive elephants are trained and bathed.",
  "best": "Nov-Feb",
  "id": "konni-elephant-camp"
 },
 {
  "place": "Chinnakanal",
  "state": "Kerala",
  "district": "Idukki",
  "category": "hill",
  "lat": 10.1,
  "lng": 77.15,
  "text": "Waterfall-dotted tea-estate village en route to Top Station from Munnar.",
  "best": "Sep-Mar",
  "id": "chinnakanal"
 },
 {
  "place": "Thyagaraja Temple",
  "state": "Tamil Nadu",
  "district": "Tiruvarur",
  "category": "temple",
  "lat": 10.7714,
  "lng": 79.6339,
  "text": "Birthplace temple of the Carnatic composer-saint Thyagaraja, with the largest temple chariot in Tamil Nadu.",
  "best": "Nov-Feb",
  "id": "thyagaraja-temple"
 },
 {
  "place": "Sri Vaikunda Perumal Temple",
  "state": "Tamil Nadu",
  "district": "Kanchipuram",
  "category": "temple",
  "lat": 12.8389,
  "lng": 79.6994,
  "text": "Pallava-era Vishnu temple with a unique three-tiered sanctum sanctorum.",
  "best": "Nov-Feb",
  "id": "sri-vaikunda-perumal-temple"
 },
 {
  "place": "Vridhachalam Vridhagiriswarar Temple",
  "state": "Tamil Nadu",
  "district": "Cuddalore",
  "category": "temple",
  "lat": 11.5167,
  "lng": 79.3167,
  "text": "One of the Pancha Sabhai Shiva shrines, associated with the cosmic dance of Shiva.",
  "best": "Nov-Feb",
  "id": "vridhachalam-vridhagiriswarar-temple"
 },
 {
  "place": "Thirumayam Fort",
  "state": "Tamil Nadu",
  "district": "Pudukkottai",
  "category": "heritage",
  "lat": 10.3167,
  "lng": 78.9167,
  "text": "17th-century fort beside two rock-cut cave temples, an offbeat Pudukkottai stop.",
  "best": "Nov-Feb",
  "id": "thirumayam-fort"
 },
 {
  "place": "Kodikkarai (Point Calimere) Salt Pans",
  "state": "Tamil Nadu",
  "district": "Nagapattinam",
  "category": "nature",
  "lat": 10.3,
  "lng": 79.8667,
  "text": "Flat coastal salt-pan landscape adjoining the wildlife sanctuary, dramatic at sunset.",
  "best": "Nov-Feb",
  "id": "kodikkarai-point-calimere-salt-pans"
 },
 {
  "place": "Sathanur Dam",
  "state": "Tamil Nadu",
  "district": "Tiruvannamalai",
  "category": "nature",
  "lat": 12.2833,
  "lng": 78.9667,
  "text": "Dam with a garden and a small crocodile farm, popular weekend outing.",
  "best": "Nov-Feb",
  "id": "sathanur-dam"
 },
 {
  "place": "Vellimalai Murugan Temple",
  "state": "Tamil Nadu",
  "district": "Kanyakumari",
  "category": "temple",
  "lat": 8.2833,
  "lng": 77.3667,
  "text": "Hillside Murugan shrine near Nagercoil with a winding ghat road up.",
  "best": "Nov-Feb",
  "id": "vellimalai-murugan-temple"
 },
 {
  "place": "Nagercoil Bhagavathy Amman Temple",
  "state": "Tamil Nadu",
  "district": "Kanyakumari",
  "category": "temple",
  "lat": 8.1783,
  "lng": 77.4339,
  "text": "Ancient temple in Nagercoil combining Jain and Hindu architectural elements.",
  "best": "Nov-Feb",
  "id": "nagercoil-bhagavathy-amman-temple"
 },
 {
  "place": "Chettinad Palace (Kanadukathan)",
  "state": "Tamil Nadu",
  "district": "Karaikudi",
  "category": "heritage",
  "lat": 10.0833,
  "lng": 78.7167,
  "text": "One of the grandest Chettinad mansions, still owned by the original family.",
  "best": "Nov-Feb",
  "id": "chettinad-palace-kanadukathan"
 },
 {
  "place": "Kazhugumalai Rock-cut Temple",
  "state": "Tamil Nadu",
  "district": "Kovilpatti",
  "category": "heritage",
  "lat": 9.2333,
  "lng": 77.5667,
  "text": "8th-century Pandya rock-cut shrine with unfinished Jain carvings on the hillside.",
  "best": "Nov-Feb",
  "id": "kazhugumalai-rock-cut-temple"
 },
 {
  "place": "Sankarankovil Temple",
  "state": "Tamil Nadu",
  "district": "Tenkasi",
  "category": "temple",
  "lat": 9.1667,
  "lng": 77.5333,
  "text": "Temple uniquely housing both Shiva and Vishnu forms in one sanctum.",
  "best": "Nov-Feb",
  "id": "sankarankovil-temple"
 },
 {
  "place": "Agasthiyar Falls",
  "state": "Tamil Nadu",
  "district": "Tirunelveli",
  "category": "waterfall",
  "lat": 8.6167,
  "lng": 77.25,
  "text": "Remote falls inside the Kalakad-Mundanthurai Tiger Reserve, trek-in only.",
  "best": "Jun-Jan",
  "id": "agasthiyar-falls"
 },
 {
  "place": "Yanaimalai Caves",
  "state": "Tamil Nadu",
  "district": "Madurai",
  "category": "heritage",
  "lat": 9.9667,
  "lng": 78.2,
  "text": "Rock-cut Pandya-era Ganesh shrine on an elephant-shaped hill outside Madurai.",
  "best": "Nov-Feb",
  "id": "yanaimalai-caves"
 },
 {
  "place": "Kutralam Falls (Main Falls)",
  "state": "Tamil Nadu",
  "district": "Tenkasi",
  "category": "waterfall",
  "lat": 8.9319,
  "lng": 77.2681,
  "text": "Also called Chitraruvi; the most-visited of the nine Courtallam waterfalls.",
  "best": "Jun-Sep",
  "id": "kutralam-falls-main-falls"
 },
 {
  "place": "Vellore Government Museum",
  "state": "Tamil Nadu",
  "district": "Vellore",
  "category": "museum",
  "lat": 12.9186,
  "lng": 79.1325,
  "text": "Housed inside Vellore Fort, with Vijayanagara and Chola-period exhibits.",
  "best": "Nov-Feb",
  "id": "vellore-government-museum"
 },
 {
  "place": "Thanjavur Art Gallery",
  "state": "Tamil Nadu",
  "district": "Thanjavur",
  "category": "museum",
  "lat": 10.787,
  "lng": 79.1378,
  "text": "Bronze and stone sculpture gallery inside the Thanjavur palace complex.",
  "best": "Nov-Feb",
  "id": "thanjavur-art-gallery"
 },
 {
  "place": "Tiruchendur Beach",
  "state": "Tamil Nadu",
  "district": "Thoothukudi",
  "category": "beach",
  "lat": 8.4956,
  "lng": 78.1219,
  "text": "Beach right beside the Thiruchendur Murugan temple, popular for a temple-and-sea visit.",
  "best": "Oct-Mar",
  "id": "tiruchendur-beach"
 },
 {
  "place": "Yercaud Pagoda Point",
  "state": "Tamil Nadu",
  "district": "Salem",
  "category": "nature",
  "lat": 11.8,
  "lng": 78.2167,
  "text": "Terraced viewpoint near Yercaud overlooking the plains below.",
  "best": "Oct-May",
  "id": "yercaud-pagoda-point"
 },
 {
  "place": "Kolli Hills Agaya Gangai Falls",
  "state": "Tamil Nadu",
  "district": "Namakkal",
  "category": "waterfall",
  "lat": 11.2667,
  "lng": 78.35,
  "text": "300-foot falls reached by a long flight of steps through the Kolli Hills forest.",
  "best": "Jun-Sep",
  "id": "kolli-hills-agaya-gangai-falls"
 },
 {
  "place": "Salem Kottai Mariamman Temple",
  "state": "Tamil Nadu",
  "district": "Salem",
  "category": "temple",
  "lat": 11.6643,
  "lng": 78.146,
  "text": "City-centre goddess temple known for its annual chariot festival.",
  "best": "Nov-Feb",
  "id": "salem-kottai-mariamman-temple"
 },
 {
  "place": "Erode Bhavani Sangam",
  "state": "Tamil Nadu",
  "district": "Erode",
  "category": "nature",
  "lat": 11.4472,
  "lng": 77.6836,
  "text": "River confluence spot with ghats popular for a peaceful evening visit.",
  "best": "Nov-Feb",
  "id": "erode-bhavani-sangam"
 },
 {
  "place": "Karur Amaravathi Dam",
  "state": "Tamil Nadu",
  "district": "Karur",
  "category": "nature",
  "lat": 10.4667,
  "lng": 77.65,
  "text": "Reservoir on the Amaravathi river with a nearby crocodile-breeding centre.",
  "best": "Nov-Feb",
  "id": "karur-amaravathi-dam"
 },
 {
  "place": "Thoothukudi Salt Pans",
  "state": "Tamil Nadu",
  "district": "Thoothukudi",
  "category": "nature",
  "lat": 8.7642,
  "lng": 78.15,
  "text": "Vast coastal salt-production flats, striking at sunrise and sunset.",
  "best": "Nov-Feb",
  "id": "thoothukudi-salt-pans"
 },
 {
  "place": "Kalakad Mundanthurai Tiger Reserve",
  "state": "Tamil Nadu",
  "district": "Tirunelveli",
  "category": "wildlife",
  "lat": 8.5667,
  "lng": 77.3333,
  "text": "Biodiversity-rich reserve straddling the Western Ghats, home to lion-tailed macaques.",
  "best": "Nov-Apr",
  "id": "kalakad-mundanthurai-tiger-reserve"
 },
 {
  "place": "Perambalur Uthamacholapuram Temple",
  "state": "Tamil Nadu",
  "district": "Perambalur",
  "category": "temple",
  "lat": 11.2333,
  "lng": 78.8833,
  "text": "Small Chola-era temple, an offbeat stop in a lightly-touristed district.",
  "best": "Nov-Feb",
  "id": "perambalur-uthamacholapuram-temple"
 },
 {
  "place": "Villupuram Melmalai Murugan Temple",
  "state": "Tamil Nadu",
  "district": "Villupuram",
  "category": "temple",
  "lat": 11.9333,
  "lng": 79.5,
  "text": "Hillside Murugan shrine popular with local pilgrims.",
  "best": "Nov-Feb",
  "id": "villupuram-melmalai-murugan-temple"
 },
 {
  "place": "Pollachi Aliyar Dam Boat Club",
  "state": "Tamil Nadu",
  "district": "Coimbatore",
  "category": "nature",
  "lat": 10.4833,
  "lng": 76.9667,
  "text": "Boating point below Aliyar Dam, gateway to the Anamalai foothills.",
  "best": "Nov-Feb",
  "id": "pollachi-aliyar-dam-boat-club"
 },
 {
  "place": "Dharmapuri Theerthamalai Temple",
  "state": "Tamil Nadu",
  "district": "Dharmapuri",
  "category": "temple",
  "lat": 12.0667,
  "lng": 78.15,
  "text": "Hillside Shiva temple with a natural spring believed to have healing waters.",
  "best": "Nov-Feb",
  "id": "dharmapuri-theerthamalai-temple"
 },
 {
  "place": "Ariyalur Fossil Park",
  "state": "Tamil Nadu",
  "district": "Ariyalur",
  "category": "museum",
  "lat": 11.15,
  "lng": 79.0667,
  "text": "Small park showcasing marine fossils from the region's Cretaceous-era seabed.",
  "best": "Nov-Feb",
  "id": "ariyalur-fossil-park"
 },
 {
  "place": "Theni Suruli Cave Temple",
  "state": "Tamil Nadu",
  "district": "Theni",
  "category": "temple",
  "lat": 9.9333,
  "lng": 77.4167,
  "text": "Cave shrine reached via ropeway above the Suruli waterfalls.",
  "best": "Nov-Feb",
  "id": "theni-suruli-cave-temple"
 },
 {
  "place": "Kollam Town & Ghats",
  "state": "Kerala",
  "district": "Kollam",
  "category": "backwater",
  "lat": 8.8932,
  "lng": 76.6141,
  "text": "Cashew-trading town on Ashtamudi Lake, the classic starting point for backwater cruises.",
  "best": "Oct-Mar",
  "id": "kollam-town-ghats"
 },
 {
  "place": "Thenmala Eco-tourism Zone",
  "state": "Kerala",
  "district": "Kollam",
  "category": "nature",
  "lat": 9.0,
  "lng": 77.05,
  "text": "India's first planned eco-tourism destination, with a dam, forest walks and adventure zones.",
  "best": "Nov-Feb",
  "id": "thenmala-eco-tourism-zone"
 },
 {
  "place": "Kollam Palaruvi Falls Trek",
  "state": "Kerala",
  "district": "Kollam",
  "category": "waterfall",
  "lat": 8.95,
  "lng": 77.15,
  "text": "Short forest trail leading to the base of Palaruvi Falls.",
  "best": "Jun-Jan",
  "id": "kollam-palaruvi-falls-trek"
 },
 {
  "place": "Kottayam Backwater Ghats",
  "state": "Kerala",
  "district": "Kottayam",
  "category": "backwater",
  "lat": 9.5916,
  "lng": 76.5222,
  "text": "Quiet town on Vembanad Lake, a low-key alternative base to Alleppey.",
  "best": "Oct-Mar",
  "id": "kottayam-backwater-ghats"
 },
 {
  "place": "Marmala Waterfalls",
  "state": "Kerala",
  "district": "Idukki",
  "category": "waterfall",
  "lat": 9.6667,
  "lng": 76.95,
  "text": "Forest waterfall near Kuttikkanam, reached by a short trek through rubber estates.",
  "best": "Jun-Jan",
  "id": "marmala-waterfalls"
 },
 {
  "place": "Vagamon Pine Forest",
  "state": "Kerala",
  "district": "Idukki",
  "category": "nature",
  "lat": 9.6833,
  "lng": 76.9167,
  "text": "Planted pine grove that's become one of Vagamon's most-photographed spots.",
  "best": "Sep-Mar",
  "id": "vagamon-pine-forest"
 },
 {
  "place": "Idukki Wildlife Sanctuary",
  "state": "Kerala",
  "district": "Idukki",
  "category": "wildlife",
  "lat": 9.85,
  "lng": 76.9833,
  "text": "Reserve surrounding the Idukki reservoir, with boat-based wildlife viewing.",
  "best": "Nov-Apr",
  "id": "idukki-wildlife-sanctuary"
 },
 {
  "place": "Anjuna Kannur Fort",
  "state": "Kerala",
  "district": "Kannur",
  "category": "heritage",
  "lat": 11.8667,
  "lng": 75.35,
  "text": "St. Angelo Fort - a Portuguese-built coastal fortress overlooking Kannur harbour.",
  "best": "Nov-Feb",
  "id": "anjuna-kannur-fort"
 },
 {
  "place": "Muzhappilangad Water Sports Zone",
  "state": "Kerala",
  "district": "Kannur",
  "category": "adventure",
  "lat": 11.7167,
  "lng": 75.5167,
  "text": "Jet-skiing and banana-boat rides on the drive-in beach's calm waters.",
  "best": "Nov-Feb",
  "id": "muzhappilangad-water-sports-zone"
 },
 {
  "place": "Alappuzha Lighthouse Beach",
  "state": "Kerala",
  "district": "Alappuzha",
  "category": "beach",
  "lat": 9.4941,
  "lng": 76.3222,
  "text": "Beach beside a 137-year-old working lighthouse open to visitors.",
  "best": "Nov-Feb",
  "id": "alappuzha-lighthouse-beach"
 },
 {
  "place": "Champakulam Church",
  "state": "Kerala",
  "district": "Alappuzha",
  "category": "heritage",
  "lat": 9.4167,
  "lng": 76.4167,
  "text": "One of the seven ancient churches founded by St. Thomas the Apostle in Kerala tradition.",
  "best": "Nov-Feb",
  "id": "champakulam-church"
 },
 {
  "place": "Pathiramanal Island",
  "state": "Kerala",
  "district": "Alappuzha",
  "category": "nature",
  "lat": 9.5833,
  "lng": 76.4,
  "text": "Tiny 'sands of midnight' island in Vembanad Lake, a haven for migratory birds.",
  "best": "Nov-Feb",
  "id": "pathiramanal-island"
 },
 {
  "place": "Kumily Spice Plantations",
  "state": "Kerala",
  "district": "Idukki",
  "category": "nature",
  "lat": 9.6,
  "lng": 77.1667,
  "text": "Guided walks through cardamom, pepper and clove plantations near Thekkady.",
  "best": "Sep-Mar",
  "id": "kumily-spice-plantations"
 },
 {
  "place": "Ponmudi Golden Valley",
  "state": "Kerala",
  "district": "Thiruvananthapuram",
  "category": "nature",
  "lat": 8.7667,
  "lng": 77.1167,
  "text": "Valley viewpoint on the Ponmudi ghat road, popular for photography.",
  "best": "Sep-Mar",
  "id": "ponmudi-golden-valley"
 },
 {
  "place": "Kovalam Lighthouse",
  "state": "Kerala",
  "district": "Thiruvananthapuram",
  "category": "heritage",
  "lat": 8.4008,
  "lng": 76.98,
  "text": "Red-and-white lighthouse on Kovalam's Lighthouse Beach, open for a coastal view climb.",
  "best": "Nov-Feb",
  "id": "kovalam-lighthouse"
 },
 {
  "place": "Akkulam Lake",
  "state": "Kerala",
  "district": "Thiruvananthapuram",
  "category": "backwater",
  "lat": 8.5167,
  "lng": 76.9,
  "text": "City lake with boating close to Thiruvananthapuram, popular for families.",
  "best": "Nov-Feb",
  "id": "akkulam-lake"
 },
 {
  "place": "Kozhikode Beypore Backwaters",
  "state": "Kerala",
  "district": "Kozhikode",
  "category": "backwater",
  "lat": 11.1667,
  "lng": 75.8167,
  "text": "Where the Chaliyar river meets the sea beside the historic Uru shipyards.",
  "best": "Nov-Feb",
  "id": "kozhikode-beypore-backwaters"
 },
 {
  "place": "Kakkayam Dam",
  "state": "Kerala",
  "district": "Kozhikode",
  "category": "backwater",
  "lat": 11.5167,
  "lng": 75.9833,
  "text": "Reservoir in the Western Ghats foothills, gateway to nearby trekking trails.",
  "best": "Nov-Mar",
  "id": "kakkayam-dam"
 },
 {
  "place": "Peruvannamuzhi Dam & Wildlife Park",
  "state": "Kerala",
  "district": "Kozhikode",
  "category": "wildlife",
  "lat": 11.5833,
  "lng": 75.85,
  "text": "Reservoir with a small deer and crocodile park nearby.",
  "best": "Nov-Feb",
  "id": "peruvannamuzhi-dam-wildlife-park"
 },
 {
  "place": "Malappuram Kottakkal Ayurveda Town",
  "state": "Kerala",
  "district": "Malappuram",
  "category": "heritage",
  "lat": 10.9833,
  "lng": 76.0,
  "text": "Home to the century-old Arya Vaidya Sala, a centre of traditional Ayurvedic treatment.",
  "best": "Year-round",
  "id": "malappuram-kottakkal-ayurveda-town"
 },
 {
  "place": "Nilambur Conolly's Plot",
  "state": "Kerala",
  "district": "Malappuram",
  "category": "nature",
  "lat": 11.2833,
  "lng": 76.2333,
  "text": "The world's oldest man-made teak plantation, planted in 1844.",
  "best": "Nov-Mar",
  "id": "nilambur-conolly-s-plot"
 },
 {
  "place": "Thrissur Punnathur Kotta Elephant Sanctuary",
  "state": "Kerala",
  "district": "Thrissur",
  "category": "wildlife",
  "lat": 10.5833,
  "lng": 76.05,
  "text": "Palace grounds housing temple elephants owned by the Guruvayur Devaswom.",
  "best": "Year-round",
  "id": "thrissur-punnathur-kotta-elephant-sanctuary"
 },
 {
  "place": "Cherpu Church",
  "state": "Kerala",
  "district": "Thrissur",
  "category": "heritage",
  "lat": 10.4667,
  "lng": 76.2833,
  "text": "Historic Syro-Malabar church known for its towering annual festival flagstaff.",
  "best": "Nov-Feb",
  "id": "cherpu-church"
 },
 {
  "place": "Athirappilly Vazhachal Forest Trail",
  "state": "Kerala",
  "district": "Thrissur",
  "category": "nature",
  "lat": 10.3,
  "lng": 76.5667,
  "text": "Forest walking trail linking Athirappilly and Vazhachal falls through evergreen forest.",
  "best": "Nov-Mar",
  "id": "athirappilly-vazhachal-forest-trail"
 },
 {
  "place": "Ernakulam Marine Drive",
  "state": "Kerala",
  "district": "Ernakulam",
  "category": "nature",
  "lat": 9.9744,
  "lng": 76.2822,
  "text": "Waterfront promenade along the backwaters in the heart of Kochi city.",
  "best": "Nov-Feb",
  "id": "ernakulam-marine-drive"
 },
 {
  "place": "Willingdon Island",
  "state": "Kerala",
  "district": "Ernakulam",
  "category": "heritage",
  "lat": 9.95,
  "lng": 76.2667,
  "text": "Largest man-made island in India, home to Kochi's naval base and port.",
  "best": "Nov-Feb",
  "id": "willingdon-island"
 },
 {
  "place": "Cherai Chinese Fishing Nets Point",
  "state": "Kerala",
  "district": "Ernakulam",
  "category": "heritage",
  "lat": 10.1367,
  "lng": 76.1797,
  "text": "Stretch of coast near Cherai where traditional cantilevered fishing nets still operate.",
  "best": "Nov-Feb",
  "id": "cherai-chinese-fishing-nets-point"
 },
 {
  "place": "Kottayam Vaikom Ashtami Grounds",
  "state": "Kerala",
  "district": "Kottayam",
  "category": "temple",
  "lat": 9.75,
  "lng": 76.3958,
  "text": "Festival grounds beside Vaikom temple hosting one of Kerala's grandest annual festivals.",
  "best": "Nov (Ashtami)",
  "id": "kottayam-vaikom-ashtami-grounds"
 },
 {
  "place": "Pathanamthitta Konni Forest",
  "state": "Kerala",
  "district": "Pathanamthitta",
  "category": "nature",
  "lat": 9.2333,
  "lng": 76.9333,
  "text": "Forest belt along the Achankovil river, home to the Konni elephant camp.",
  "best": "Nov-Feb",
  "id": "pathanamthitta-konni-forest"
 },
 {
  "place": "Kasaragod Madhur Temple",
  "state": "Kerala",
  "district": "Kasaragod",
  "category": "temple",
  "lat": 12.4833,
  "lng": 75.0,
  "text": "Ganesh temple known for its distinctive copper-plated roof.",
  "best": "Nov-Feb",
  "id": "kasaragod-madhur-temple"
 },
 {
  "place": "Kannur Theyyam Villages",
  "state": "Kerala",
  "district": "Kannur",
  "category": "heritage",
  "lat": 11.8745,
  "lng": 75.3704,
  "text": "North Kerala's ritual Theyyam dance-worship performances, held at village shrines in season.",
  "best": "Nov-Apr",
  "id": "kannur-theyyam-villages"
 }
];

// Exposed for app.js — a static reference directory of well-known tourist
// places across Tamil Nadu and Kerala, separate from the community-submitted
// tips in the Tips tab. Coordinates are town/landmark-level (good for sorting
// by distance) rather than survey-precise pins for every single spot.
