// Namma Tour — curated directory of real Tamil Nadu & Kerala tourist places.
// Loaded as a plain global (no build step / bundler) so it works with the
// app's zero-server, phone-only setup. Read by the Explore tab in app.js.
const curatedPlaces = [
  {
    "id": "p001",
    "place": "Meenakshi Amman Temple",
    "district": "Madurai",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 9.9195,
    "lng": 78.1193,
    "best": "Oct-Mar",
    "text": "Iconic twin-towered temple complex with over 14 gopurams, famed for its sculpture and evening 'palli arai' ceremony."
  },
  {
    "id": "p002",
    "place": "Brihadeeswarar Temple",
    "district": "Thanjavur",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 10.7828,
    "lng": 79.1318,
    "best": "Oct-Mar",
    "text": "UNESCO World Heritage Chola-era temple, over 1000 years old, known for its massive vimana tower."
  },
  {
    "id": "p003",
    "place": "Ramanathaswamy Temple",
    "district": "Rameswaram",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 9.2882,
    "lng": 79.3129,
    "best": "Oct-Mar",
    "text": "One of the Char Dham sites, famous for its 1200m corridor lined with carved pillars."
  },
  {
    "id": "p004",
    "place": "Arunachaleswarar Temple",
    "district": "Tiruvannamalai",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 12.2253,
    "lng": 79.0693,
    "best": "Nov-Feb",
    "text": "Major Shiva temple at the base of Arunachala hill, site of the Karthigai Deepam festival."
  },
  {
    "id": "p005",
    "place": "Kapaleeshwarar Temple",
    "district": "Chennai",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 13.0338,
    "lng": 80.2697,
    "best": "Nov-Feb",
    "text": "Colourful Dravidian-style temple in Mylapore, one of Chennai's oldest."
  },
  {
    "id": "p006",
    "place": "Nataraja Temple",
    "district": "Chidambaram",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 11.3994,
    "lng": 79.6936,
    "best": "Dec-Feb",
    "text": "Temple dedicated to Shiva as the cosmic dancer, famous for its golden-roofed sanctum."
  },
  {
    "id": "p007",
    "place": "Ranganathaswamy Temple",
    "district": "Srirangam",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 10.8624,
    "lng": 78.6905,
    "best": "Dec-Feb",
    "text": "One of the largest functioning temple complexes in the world, on an island in the Kaveri."
  },
  {
    "id": "p008",
    "place": "Palani Murugan Temple",
    "district": "Palani",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 10.447,
    "lng": 77.5222,
    "best": "Oct-Feb",
    "text": "Hilltop temple reached by winch/ropeway or steps, one of Murugan's six abodes."
  },
  {
    "id": "p009",
    "place": "Ekambareswarar Temple",
    "district": "Kanchipuram",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 12.8447,
    "lng": 79.7006,
    "best": "Nov-Feb",
    "text": "Massive Shiva temple with a thousand-pillar hall and an ancient mango tree shrine."
  },
  {
    "id": "p010",
    "place": "Kailasanathar Temple",
    "district": "Kanchipuram",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 12.8378,
    "lng": 79.6944,
    "best": "Nov-Feb",
    "text": "Oldest structural temple in Kanchipuram, built by the Pallavas, known for its sandstone carvings."
  },
  {
    "id": "p011",
    "place": "Airavatesvara Temple",
    "district": "Darasuram",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 10.9598,
    "lng": 79.3193,
    "best": "Oct-Mar",
    "text": "UNESCO-listed Chola temple famous for its stone chariot-shaped mandapa."
  },
  {
    "id": "p012",
    "place": "Vaitheeswaran Koil",
    "district": "Sirkazhi",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 11.1794,
    "lng": 79.652,
    "best": "Nov-Feb",
    "text": "Temple associated with astrology and Navagraha (planetary) worship."
  },
  {
    "id": "p013",
    "place": "Suchindram Thanumalayan Temple",
    "district": "Kanyakumari",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 8.1719,
    "lng": 77.4406,
    "best": "Nov-Feb",
    "text": "Rare temple honouring the Trimurti together, known for its musical stone pillars."
  },
  {
    "id": "p014",
    "place": "Padmanabhapuram Palace",
    "district": "Thuckalay",
    "state": "Tamil Nadu",
    "category": "heritage",
    "lat": 8.245,
    "lng": 77.335,
    "best": "Nov-Feb",
    "text": "Beautifully preserved wooden Travancore-era royal palace with intricate carvings."
  },
  {
    "id": "p015",
    "place": "Ooty (Udhagamandalam)",
    "district": "The Nilgiris",
    "state": "Tamil Nadu",
    "category": "hill",
    "lat": 11.4064,
    "lng": 76.6932,
    "best": "Sep-May",
    "text": "Queen of hill stations with botanical gardens, a toy train and Ooty Lake."
  },
  {
    "id": "p016",
    "place": "Kodaikanal",
    "district": "Dindigul",
    "state": "Tamil Nadu",
    "category": "hill",
    "lat": 10.2381,
    "lng": 77.4892,
    "best": "Sep-May",
    "text": "Misty hill town centred on a star-shaped lake, pine forests and Coaker's Walk."
  },
  {
    "id": "p017",
    "place": "Yercaud",
    "district": "Salem",
    "state": "Tamil Nadu",
    "category": "hill",
    "lat": 11.7753,
    "lng": 78.2101,
    "best": "Oct-May",
    "text": "Quiet coffee-growing hill station with a lake, orange groves and viewpoints."
  },
  {
    "id": "p018",
    "place": "Coonoor",
    "district": "The Nilgiris",
    "state": "Tamil Nadu",
    "category": "hill",
    "lat": 11.353,
    "lng": 76.7959,
    "best": "Sep-May",
    "text": "Tea-estate hill town with Sim's Park and the Dolphin's Nose viewpoint."
  },
  {
    "id": "p019",
    "place": "Kotagiri",
    "district": "The Nilgiris",
    "state": "Tamil Nadu",
    "category": "hill",
    "lat": 11.4235,
    "lng": 76.8659,
    "best": "Sep-May",
    "text": "Oldest Nilgiri hill station, quieter than Ooty, surrounded by tea gardens."
  },
  {
    "id": "p020",
    "place": "Valparai",
    "district": "Coimbatore",
    "state": "Tamil Nadu",
    "category": "hill",
    "lat": 10.3273,
    "lng": 76.955,
    "best": "Oct-Feb",
    "text": "Remote plateau of tea estates in the Anamalai hills, good for wildlife sightings."
  },
  {
    "id": "p021",
    "place": "Yelagiri",
    "district": "Vellore",
    "state": "Tamil Nadu",
    "category": "hill",
    "lat": 12.5827,
    "lng": 78.6389,
    "best": "Oct-Mar",
    "text": "Small laid-back hill station popular for trekking and paragliding."
  },
  {
    "id": "p022",
    "place": "Kolli Hills",
    "district": "Namakkal",
    "state": "Tamil Nadu",
    "category": "hill",
    "lat": 11.2497,
    "lng": 78.3288,
    "best": "Oct-Mar",
    "text": "Remote hill range reached via 70 hairpin bends, home to Agaya Gangai falls."
  },
  {
    "id": "p023",
    "place": "Marina Beach",
    "district": "Chennai",
    "state": "Tamil Nadu",
    "category": "beach",
    "lat": 13.05,
    "lng": 80.2824,
    "best": "Nov-Feb",
    "text": "One of the world's longest urban beaches, a Chennai evening institution."
  },
  {
    "id": "p024",
    "place": "Elliot's Beach",
    "district": "Chennai",
    "state": "Tamil Nadu",
    "category": "beach",
    "lat": 13.0011,
    "lng": 80.2707,
    "best": "Nov-Feb",
    "text": "Calmer alternative to Marina, popular with joggers and cafe-hoppers."
  },
  {
    "id": "p025",
    "place": "Kanyakumari Beach",
    "district": "Kanyakumari",
    "state": "Tamil Nadu",
    "category": "beach",
    "lat": 8.0788,
    "lng": 77.5385,
    "best": "Oct-Mar",
    "text": "Southern tip of India where three seas meet, famous for sunrise and sunset views."
  },
  {
    "id": "p026",
    "place": "Dhanushkodi Beach",
    "district": "Rameswaram",
    "state": "Tamil Nadu",
    "category": "beach",
    "lat": 9.15,
    "lng": 79.4167,
    "best": "Oct-Mar",
    "text": "Ghost-town beach at the narrow tip of Rameswaram, where the sea splits in two colours."
  },
  {
    "id": "p027",
    "place": "Mahabalipuram Beach",
    "district": "Chengalpattu",
    "state": "Tamil Nadu",
    "category": "beach",
    "lat": 12.6167,
    "lng": 80.1931,
    "best": "Nov-Feb",
    "text": "Beach beside the famous Shore Temple and rock-cut monuments."
  },
  {
    "id": "p028",
    "place": "Covelong (Kovalam) Beach TN",
    "district": "Chengalpattu",
    "state": "Tamil Nadu",
    "category": "beach",
    "lat": 12.7925,
    "lng": 80.2513,
    "best": "Nov-Feb",
    "text": "Fishing-village beach near Chennai known for surfing schools."
  },
  {
    "id": "p029",
    "place": "Pichavaram Mangrove Forest",
    "district": "Cuddalore",
    "state": "Tamil Nadu",
    "category": "backwater",
    "lat": 11.4275,
    "lng": 79.7867,
    "best": "Nov-Feb",
    "text": "Second-largest mangrove forest in the world, explored by boat through narrow water channels."
  },
  {
    "id": "p030",
    "place": "Muthupet Lagoon",
    "district": "Tiruvarur",
    "state": "Tamil Nadu",
    "category": "backwater",
    "lat": 10.3833,
    "lng": 79.4667,
    "best": "Nov-Feb",
    "text": "Coastal mangrove lagoon and estuary, a haven for migratory birds."
  },
  {
    "id": "p031",
    "place": "Mudumalai National Park",
    "district": "The Nilgiris",
    "state": "Tamil Nadu",
    "category": "wildlife",
    "lat": 11.568,
    "lng": 76.536,
    "best": "Feb-May",
    "text": "Tiger reserve on the Kerala-Karnataka border known for elephant herds."
  },
  {
    "id": "p032",
    "place": "Indira Gandhi Wildlife Sanctuary (Anamalai)",
    "district": "Coimbatore",
    "state": "Tamil Nadu",
    "category": "wildlife",
    "lat": 10.4667,
    "lng": 76.9333,
    "best": "Dec-Apr",
    "text": "Tiger reserve in the Anamalai hills bordering Valparai's tea estates."
  },
  {
    "id": "p033",
    "place": "Vedanthangal Bird Sanctuary",
    "district": "Chengalpattu",
    "state": "Tamil Nadu",
    "category": "wildlife",
    "lat": 12.5432,
    "lng": 79.859,
    "best": "Nov-Feb",
    "text": "One of India's oldest bird sanctuaries, home to thousands of migratory waterbirds."
  },
  {
    "id": "p034",
    "place": "Kalakad Mundanthurai Tiger Reserve",
    "district": "Tirunelveli",
    "state": "Tamil Nadu",
    "category": "wildlife",
    "lat": 8.5667,
    "lng": 77.3833,
    "best": "Dec-Mar",
    "text": "Biodiverse tiger reserve in the southern Western Ghats."
  },
  {
    "id": "p035",
    "place": "Point Calimere Wildlife Sanctuary",
    "district": "Nagapattinam",
    "state": "Tamil Nadu",
    "category": "wildlife",
    "lat": 10.2917,
    "lng": 79.85,
    "best": "Nov-Feb",
    "text": "Coastal sanctuary known for blackbuck and flocks of flamingos."
  },
  {
    "id": "p036",
    "place": "Courtallam Falls",
    "district": "Tenkasi",
    "state": "Tamil Nadu",
    "category": "waterfall",
    "lat": 8.9333,
    "lng": 77.2833,
    "best": "Jun-Sep",
    "text": "Known as the 'Spa of South India', a cluster of falls believed to have healing properties."
  },
  {
    "id": "p037",
    "place": "Hogenakkal Falls",
    "district": "Dharmapuri",
    "state": "Tamil Nadu",
    "category": "waterfall",
    "lat": 12.1167,
    "lng": 77.7833,
    "best": "Jul-Jan",
    "text": "Cascades on the Kaveri river, famous for coracle boat rides."
  },
  {
    "id": "p038",
    "place": "Silver Cascade Falls",
    "district": "Kodaikanal",
    "state": "Tamil Nadu",
    "category": "waterfall",
    "lat": 10.265,
    "lng": 77.485,
    "best": "Jun-Sep",
    "text": "Roadside waterfall on the Kodaikanal ghat road, easy to reach."
  },
  {
    "id": "p039",
    "place": "Pykara Falls",
    "district": "The Nilgiris",
    "state": "Tamil Nadu",
    "category": "waterfall",
    "lat": 11.4833,
    "lng": 76.6167,
    "best": "Jun-Sep",
    "text": "Waterfall and lake near Ooty popular for boating."
  },
  {
    "id": "p040",
    "place": "Thirparappu Falls",
    "district": "Kanyakumari",
    "state": "Tamil Nadu",
    "category": "waterfall",
    "lat": 8.2833,
    "lng": 77.3167,
    "best": "Jun-Dec",
    "text": "Horseshoe-shaped falls on the Kodayar river."
  },
  {
    "id": "p041",
    "place": "Shore Temple",
    "district": "Mahabalipuram",
    "state": "Tamil Nadu",
    "category": "heritage",
    "lat": 12.6169,
    "lng": 80.1998,
    "best": "Nov-Feb",
    "text": "UNESCO-listed 8th-century rock-cut temple standing right on the shoreline."
  },
  {
    "id": "p042",
    "place": "Gingee Fort",
    "district": "Villupuram",
    "state": "Tamil Nadu",
    "category": "heritage",
    "lat": 12.2547,
    "lng": 79.4142,
    "best": "Nov-Feb",
    "text": "Massive hill fort spread across three hills, called the 'Troy of the East'."
  },
  {
    "id": "p043",
    "place": "Vellore Fort",
    "district": "Vellore",
    "state": "Tamil Nadu",
    "category": "heritage",
    "lat": 12.9186,
    "lng": 79.1325,
    "best": "Nov-Feb",
    "text": "16th-century fort with a moat, temple and the site of the 1806 Vellore mutiny."
  },
  {
    "id": "p044",
    "place": "Thanjavur Maratha Palace",
    "district": "Thanjavur",
    "state": "Tamil Nadu",
    "category": "heritage",
    "lat": 10.8052,
    "lng": 79.1354,
    "best": "Oct-Mar",
    "text": "Former royal residence housing a durbar hall and the Saraswathi Mahal Library."
  },
  {
    "id": "p045",
    "place": "Chettinad Mansions",
    "district": "Karaikudi",
    "state": "Tamil Nadu",
    "category": "heritage",
    "lat": 10.073,
    "lng": 78.783,
    "best": "Oct-Feb",
    "text": "Grand 19th-century mansions of the Chettiar merchant community, famed for tilework."
  },
  {
    "id": "p046",
    "place": "Fort St. George",
    "district": "Chennai",
    "state": "Tamil Nadu",
    "category": "heritage",
    "lat": 13.0797,
    "lng": 80.287,
    "best": "Nov-Feb",
    "text": "First English fortress in India, now housing a museum and the Tamil Nadu Assembly."
  },
  {
    "id": "p047",
    "place": "Ooty Botanical Garden",
    "district": "The Nilgiris",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 11.4144,
    "lng": 76.7125,
    "best": "Sep-May",
    "text": "Terraced Victorian-era garden with a fossilised tree trunk over 20 million years old."
  },
  {
    "id": "p048",
    "place": "Berijam Lake",
    "district": "Kodaikanal",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 10.1333,
    "lng": 77.4167,
    "best": "Sep-May",
    "text": "Pristine forest lake accessible only with a permit, a quiet escape from Kodaikanal town."
  },
  {
    "id": "p049",
    "place": "Government Museum Chennai",
    "district": "Chennai",
    "state": "Tamil Nadu",
    "category": "museum",
    "lat": 13.07,
    "lng": 80.2578,
    "best": "Nov-Feb",
    "text": "One of India's oldest museums, with a renowned bronze gallery."
  },
  {
    "id": "p050",
    "place": "Gandhi Memorial Museum",
    "district": "Madurai",
    "state": "Tamil Nadu",
    "category": "museum",
    "lat": 9.9252,
    "lng": 78.1198,
    "best": "Oct-Mar",
    "text": "Museum tracing India's freedom struggle, housed in a former Rani Mangammal palace."
  },
  {
    "id": "p051",
    "place": "Yelagiri Paragliding Point",
    "district": "Vellore",
    "state": "Tamil Nadu",
    "category": "adventure",
    "lat": 12.585,
    "lng": 78.645,
    "best": "Oct-Mar",
    "text": "Popular paragliding launch point overlooking the Yelagiri valley."
  },
  {
    "id": "p052",
    "place": "Top Slip",
    "district": "Coimbatore",
    "state": "Tamil Nadu",
    "category": "adventure",
    "lat": 10.5833,
    "lng": 76.9333,
    "best": "Dec-Apr",
    "text": "Gateway to the Anamalai Tiger Reserve, offering jungle safaris and trekking."
  },
  {
    "id": "p053",
    "place": "Sabarimala Temple",
    "district": "Pathanamthitta",
    "state": "Kerala",
    "category": "temple",
    "lat": 9.4325,
    "lng": 77.0817,
    "best": "Nov-Jan",
    "text": "Major pilgrimage hill shrine of Lord Ayyappa, reached by forest trek."
  },
  {
    "id": "p054",
    "place": "Padmanabhaswamy Temple",
    "district": "Thiruvananthapuram",
    "state": "Kerala",
    "category": "temple",
    "lat": 8.4828,
    "lng": 76.9436,
    "best": "Nov-Feb",
    "text": "Historic temple famed for its vast treasure vaults and Dravidian architecture."
  },
  {
    "id": "p055",
    "place": "Guruvayur Sri Krishna Temple",
    "district": "Thrissur",
    "state": "Kerala",
    "category": "temple",
    "lat": 10.5946,
    "lng": 76.0393,
    "best": "Nov-Feb",
    "text": "One of Kerala's most revered Krishna temples, known for its elephant processions."
  },
  {
    "id": "p056",
    "place": "Vadakkunnathan Temple",
    "district": "Thrissur",
    "state": "Kerala",
    "category": "temple",
    "lat": 10.5276,
    "lng": 76.2144,
    "best": "Nov-Feb",
    "text": "Ancient Shiva temple at the heart of Thrissur, centre of the Pooram festival."
  },
  {
    "id": "p057",
    "place": "Chottanikkara Temple",
    "district": "Ernakulam",
    "state": "Kerala",
    "category": "temple",
    "lat": 9.9333,
    "lng": 76.4167,
    "best": "Nov-Feb",
    "text": "Popular Devi temple known for its healing rituals."
  },
  {
    "id": "p058",
    "place": "Ambalappuzha Krishna Temple",
    "district": "Alappuzha",
    "state": "Kerala",
    "category": "temple",
    "lat": 9.3833,
    "lng": 76.35,
    "best": "Nov-Feb",
    "text": "Temple famous for its ceremonial 'palpayasam' milk pudding offering."
  },
  {
    "id": "p059",
    "place": "Munnar",
    "district": "Idukki",
    "state": "Kerala",
    "category": "hill",
    "lat": 10.0889,
    "lng": 77.0595,
    "best": "Sep-May",
    "text": "Rolling tea-estate hills, home to the rare Neelakurinji flower and Eravikulam park."
  },
  {
    "id": "p060",
    "place": "Wayanad (Kalpetta)",
    "district": "Wayanad",
    "state": "Kerala",
    "category": "hill",
    "lat": 11.6854,
    "lng": 76.132,
    "best": "Oct-May",
    "text": "Green plateau of forests, spice plantations and caves in northern Kerala."
  },
  {
    "id": "p061",
    "place": "Ponmudi",
    "district": "Thiruvananthapuram",
    "state": "Kerala",
    "category": "hill",
    "lat": 8.75,
    "lng": 77.1167,
    "best": "Sep-May",
    "text": "Compact hill station with hairpin roads and views over the Western Ghats."
  },
  {
    "id": "p062",
    "place": "Vagamon",
    "district": "Idukki",
    "state": "Kerala",
    "category": "hill",
    "lat": 9.6833,
    "lng": 76.9333,
    "best": "Sep-May",
    "text": "Meadowed hill town known for paragliding and pine forests."
  },
  {
    "id": "p063",
    "place": "Nelliampathy",
    "district": "Palakkad",
    "state": "Kerala",
    "category": "hill",
    "lat": 10.4833,
    "lng": 76.6667,
    "best": "Nov-Apr",
    "text": "Lesser-visited hills of orange orchards and cardamom estates."
  },
  {
    "id": "p064",
    "place": "Devikulam",
    "district": "Idukki",
    "state": "Kerala",
    "category": "hill",
    "lat": 10.05,
    "lng": 77.0833,
    "best": "Sep-May",
    "text": "Quiet hill town near Munnar with the sacred Sita Devi Lake."
  },
  {
    "id": "p065",
    "place": "Peermade",
    "district": "Idukki",
    "state": "Kerala",
    "category": "hill",
    "lat": 9.5667,
    "lng": 76.9667,
    "best": "Sep-May",
    "text": "Plantation town on the old spice route, gateway to Periyar."
  },
  {
    "id": "p066",
    "place": "Kovalam Beach",
    "district": "Thiruvananthapuram",
    "state": "Kerala",
    "category": "beach",
    "lat": 8.4004,
    "lng": 76.9787,
    "best": "Sep-Mar",
    "text": "Crescent-shaped beach with a lighthouse, one of Kerala's most famous."
  },
  {
    "id": "p067",
    "place": "Varkala Beach",
    "district": "Thiruvananthapuram",
    "state": "Kerala",
    "category": "beach",
    "lat": 8.7379,
    "lng": 76.7163,
    "best": "Sep-Mar",
    "text": "Dramatic red-cliff beach lined with cafes, also a pilgrimage spot."
  },
  {
    "id": "p068",
    "place": "Cherai Beach",
    "district": "Ernakulam",
    "state": "Kerala",
    "category": "beach",
    "lat": 10.144,
    "lng": 76.181,
    "best": "Sep-Mar",
    "text": "Wide beach near Kochi where backwaters and sea nearly meet."
  },
  {
    "id": "p069",
    "place": "Marari Beach",
    "district": "Alappuzha",
    "state": "Kerala",
    "category": "beach",
    "lat": 9.6008,
    "lng": 76.2933,
    "best": "Sep-Mar",
    "text": "Quiet fishing-village beach known for laid-back resorts."
  },
  {
    "id": "p070",
    "place": "Bekal Beach",
    "district": "Kasaragod",
    "state": "Kerala",
    "category": "beach",
    "lat": 12.3961,
    "lng": 75.0308,
    "best": "Oct-Mar",
    "text": "Beach beneath the historic Bekal Fort in northern Kerala."
  },
  {
    "id": "p071",
    "place": "Kappad Beach",
    "district": "Kozhikode",
    "state": "Kerala",
    "category": "beach",
    "lat": 11.3833,
    "lng": 75.6833,
    "best": "Oct-Mar",
    "text": "Historic beach where Vasco da Gama first landed in India in 1498."
  },
  {
    "id": "p072",
    "place": "Alleppey Backwaters",
    "district": "Alappuzha",
    "state": "Kerala",
    "category": "backwater",
    "lat": 9.4981,
    "lng": 76.3388,
    "best": "Sep-Mar",
    "text": "Kerala's houseboat capital, a maze of canals, lagoons and paddy fields."
  },
  {
    "id": "p073",
    "place": "Kumarakom Backwaters",
    "district": "Kottayam",
    "state": "Kerala",
    "category": "backwater",
    "lat": 9.615,
    "lng": 76.43,
    "best": "Sep-Mar",
    "text": "Backwater village on Vembanad Lake, known for its bird sanctuary."
  },
  {
    "id": "p074",
    "place": "Kollam Backwaters (Ashtamudi Lake)",
    "district": "Kollam",
    "state": "Kerala",
    "category": "backwater",
    "lat": 8.95,
    "lng": 76.5833,
    "best": "Sep-Mar",
    "text": "Eight-armed lake offering quieter houseboat cruises than Alleppey."
  },
  {
    "id": "p075",
    "place": "Munroe Island",
    "district": "Kollam",
    "state": "Kerala",
    "category": "backwater",
    "lat": 8.95,
    "lng": 76.6167,
    "best": "Sep-Mar",
    "text": "Cluster of islands where the backwaters meet, popular for canoe tours."
  },
  {
    "id": "p076",
    "place": "Periyar Tiger Reserve (Thekkady)",
    "district": "Idukki",
    "state": "Kerala",
    "category": "wildlife",
    "lat": 9.4667,
    "lng": 77.1667,
    "best": "Oct-Apr",
    "text": "Forested reserve around Periyar Lake, famous for boat safaris and elephants."
  },
  {
    "id": "p077",
    "place": "Wayanad Wildlife Sanctuary",
    "district": "Wayanad",
    "state": "Kerala",
    "category": "wildlife",
    "lat": 11.6333,
    "lng": 76.4167,
    "best": "Oct-Apr",
    "text": "Sanctuary linking Nagarhole and Bandipur, home to elephants and tigers."
  },
  {
    "id": "p078",
    "place": "Eravikulam National Park",
    "district": "Idukki",
    "state": "Kerala",
    "category": "wildlife",
    "lat": 10.1936,
    "lng": 77.0631,
    "best": "Sep-Mar",
    "text": "Home to the endangered Nilgiri Tahr and rolling grassland peaks near Munnar."
  },
  {
    "id": "p079",
    "place": "Silent Valley National Park",
    "district": "Palakkad",
    "state": "Kerala",
    "category": "wildlife",
    "lat": 11.1333,
    "lng": 76.4333,
    "best": "Dec-Apr",
    "text": "One of the last undisturbed tracts of tropical evergreen forest in India."
  },
  {
    "id": "p080",
    "place": "Parambikulam Tiger Reserve",
    "district": "Palakkad",
    "state": "Kerala",
    "category": "wildlife",
    "lat": 10.4167,
    "lng": 76.8167,
    "best": "Dec-Apr",
    "text": "Reserve known for its ancient trees and eco-tourism treks."
  },
  {
    "id": "p081",
    "place": "Chinnar Wildlife Sanctuary",
    "district": "Idukki",
    "state": "Kerala",
    "category": "wildlife",
    "lat": 10.3,
    "lng": 77.1167,
    "best": "Dec-Apr",
    "text": "Dry scrub sanctuary near Munnar, home to the endangered grizzled giant squirrel."
  },
  {
    "id": "p082",
    "place": "Athirappilly Falls",
    "district": "Thrissur",
    "state": "Kerala",
    "category": "waterfall",
    "lat": 10.2851,
    "lng": 76.5695,
    "best": "Jun-Jan",
    "text": "Kerala's largest waterfall, often called the 'Niagara of India'."
  },
  {
    "id": "p083",
    "place": "Vazhachal Falls",
    "district": "Thrissur",
    "state": "Kerala",
    "category": "waterfall",
    "lat": 10.3167,
    "lng": 76.5833,
    "best": "Jun-Jan",
    "text": "Wide cascading falls a short drive past Athirappilly."
  },
  {
    "id": "p084",
    "place": "Meenmutty Falls",
    "district": "Wayanad",
    "state": "Kerala",
    "category": "waterfall",
    "lat": 11.5667,
    "lng": 76.2167,
    "best": "Jun-Nov",
    "text": "Wayanad's tallest waterfall, reached via a forest trek."
  },
  {
    "id": "p085",
    "place": "Soochipara Falls",
    "district": "Wayanad",
    "state": "Kerala",
    "category": "waterfall",
    "lat": 11.5333,
    "lng": 76.1833,
    "best": "Jun-Nov",
    "text": "Three-tiered falls popular for a short trek and a swim at the base."
  },
  {
    "id": "p086",
    "place": "Thommankuthu Falls",
    "district": "Idukki",
    "state": "Kerala",
    "category": "waterfall",
    "lat": 9.7833,
    "lng": 76.85,
    "best": "Jun-Nov",
    "text": "Seven-step cascading falls set in dense forest."
  },
  {
    "id": "p087",
    "place": "Palaruvi Falls",
    "district": "Kollam",
    "state": "Kerala",
    "category": "waterfall",
    "lat": 8.9667,
    "lng": 77.1667,
    "best": "Jun-Jan",
    "text": "'Stream of Milk' falls dropping 300 feet through the Western Ghats."
  },
  {
    "id": "p088",
    "place": "Fort Kochi",
    "district": "Ernakulam",
    "state": "Kerala",
    "category": "heritage",
    "lat": 9.9658,
    "lng": 76.2422,
    "best": "Oct-Mar",
    "text": "Colonial-era waterfront quarter with Chinese fishing nets and colonial architecture."
  },
  {
    "id": "p089",
    "place": "Mattancherry Palace",
    "district": "Ernakulam",
    "state": "Kerala",
    "category": "heritage",
    "lat": 9.958,
    "lng": 76.2593,
    "best": "Oct-Mar",
    "text": "16th-century Dutch Palace with Kerala mural paintings depicting Hindu epics."
  },
  {
    "id": "p090",
    "place": "Paradesi Synagogue",
    "district": "Ernakulam",
    "state": "Kerala",
    "category": "heritage",
    "lat": 9.9573,
    "lng": 76.2597,
    "best": "Oct-Mar",
    "text": "Oldest active synagogue in the Commonwealth, in Kochi's historic Jew Town."
  },
  {
    "id": "p091",
    "place": "Bekal Fort",
    "district": "Kasaragod",
    "state": "Kerala",
    "category": "heritage",
    "lat": 12.3961,
    "lng": 75.0308,
    "best": "Oct-Mar",
    "text": "Kerala's largest fort, a laterite structure overlooking the Arabian Sea."
  },
  {
    "id": "p092",
    "place": "Hill Palace",
    "district": "Tripunithura",
    "state": "Kerala",
    "category": "heritage",
    "lat": 9.9403,
    "lng": 76.3467,
    "best": "Oct-Mar",
    "text": "Former royal residence of the Kochi royal family, now an archaeological museum."
  },
  {
    "id": "p093",
    "place": "Vembanad Lake",
    "district": "Kottayam",
    "state": "Kerala",
    "category": "nature",
    "lat": 9.6167,
    "lng": 76.4333,
    "best": "Sep-Mar",
    "text": "Kerala's longest lake, the heart of the backwater houseboat network."
  },
  {
    "id": "p094",
    "place": "Bolgatty Island",
    "district": "Ernakulam",
    "state": "Kerala",
    "category": "nature",
    "lat": 10.0167,
    "lng": 76.2667,
    "best": "Oct-Mar",
    "text": "Small island in Kochi harbour with a Dutch-era palace and gardens."
  },
  {
    "id": "p095",
    "place": "Napier Museum",
    "district": "Thiruvananthapuram",
    "state": "Kerala",
    "category": "museum",
    "lat": 8.5074,
    "lng": 76.955,
    "best": "Oct-Mar",
    "text": "19th-century museum in an ornate Indo-Saracenic building, with bronze and ivory collections."
  },
  {
    "id": "p096",
    "place": "Kerala Folklore Museum",
    "district": "Ernakulam",
    "state": "Kerala",
    "category": "museum",
    "lat": 9.97,
    "lng": 76.29,
    "best": "Oct-Mar",
    "text": "Museum built from salvaged wooden temple and palace architecture, showcasing folk art."
  },
  {
    "id": "p097",
    "place": "Kolukkumalai Tea Estate",
    "district": "Idukki",
    "state": "Kerala",
    "category": "adventure",
    "lat": 10.1512,
    "lng": 77.2233,
    "best": "Nov-Feb",
    "text": "One of the world's highest tea plantations, famous for its jeep-track sunrise trek."
  },
  {
    "id": "p098",
    "place": "Top Station",
    "district": "Idukki",
    "state": "Kerala",
    "category": "adventure",
    "lat": 10.1167,
    "lng": 77.2,
    "best": "Sep-May",
    "text": "Highest viewpoint near Munnar on the old Kundala Valley Railway route."
  },
  {
    "id": "p099",
    "place": "Vagamon Paragliding Point",
    "district": "Idukki",
    "state": "Kerala",
    "category": "adventure",
    "lat": 9.6833,
    "lng": 76.9333,
    "best": "Sep-May",
    "text": "Meadow-top launch site for tandem paragliding over the Vagamon hills."
  },
  {
    "id": "p100",
    "place": "Rock Fort Temple (Uchi Pillayar Koil)",
    "district": "Tiruchirappalli",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 10.8285,
    "lng": 78.6975,
    "best": "Oct-Feb",
    "text": "Cliff-top Ganesha shrine carved into an ancient rock, offering panoramic views of Trichy."
  },
  {
    "id": "p101",
    "place": "Jambukeswarar Temple",
    "district": "Thiruvanaikaval",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 10.8508,
    "lng": 78.7069,
    "best": "Oct-Feb",
    "text": "One of the Pancha Bhoota Sthalams, dedicated to Shiva as the element of water."
  },
  {
    "id": "p102",
    "place": "Adi Kumbeswarar Temple",
    "district": "Kumbakonam",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 10.9601,
    "lng": 79.3788,
    "best": "Oct-Feb",
    "text": "Ancient Shiva temple at the heart of Kumbakonam, centre of the Mahamaham festival."
  },
  {
    "id": "p103",
    "place": "Sarangapani Temple",
    "district": "Kumbakonam",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 10.9615,
    "lng": 79.3805,
    "best": "Oct-Feb",
    "text": "Chariot-shaped Vishnu temple with an imposing 12-tier gopuram."
  },
  {
    "id": "p104",
    "place": "Swamimalai Murugan Temple",
    "district": "Kumbakonam",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 10.9758,
    "lng": 79.3172,
    "best": "Oct-Feb",
    "text": "One of Murugan's six abodes, known for its bronze-casting artisans."
  },
  {
    "id": "p105",
    "place": "Thyagarajaswamy Temple",
    "district": "Tiruvarur",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 10.7726,
    "lng": 79.6367,
    "best": "Oct-Feb",
    "text": "Vast temple complex famous for its giant temple chariot and classical music heritage."
  },
  {
    "id": "p106",
    "place": "Nagore Dargah",
    "district": "Nagapattinam",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 10.8167,
    "lng": 79.85,
    "best": "Nov-Feb",
    "text": "Revered Sufi shrine drawing pilgrims of all faiths, known for its towering minarets."
  },
  {
    "id": "p107",
    "place": "Velankanni Basilica",
    "district": "Nagapattinam",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 10.6819,
    "lng": 79.8449,
    "best": "Aug-Sep",
    "text": "Basilica of Our Lady of Good Health, one of India's major Christian pilgrimage sites."
  },
  {
    "id": "p108",
    "place": "Alagar Koil",
    "district": "Madurai",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 9.9982,
    "lng": 78.2277,
    "best": "Oct-Feb",
    "text": "Hillside Vishnu temple set amid forest, linked to Madurai by the Chithirai festival."
  },
  {
    "id": "p109",
    "place": "Thiruparankundram Murugan Temple",
    "district": "Madurai",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 9.8667,
    "lng": 78.0833,
    "best": "Oct-Feb",
    "text": "Rock-cut cave temple, one of Murugan's six abodes, carved into a hillside."
  },
  {
    "id": "p110",
    "place": "Gangaikonda Cholapuram Temple",
    "district": "Ariyalur",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 11.1975,
    "lng": 79.4478,
    "best": "Oct-Feb",
    "text": "UNESCO-listed Chola temple built to commemorate a Ganges military campaign."
  },
  {
    "id": "p111",
    "place": "Varadharaja Perumal Temple",
    "district": "Kanchipuram",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 12.8358,
    "lng": 79.713,
    "best": "Nov-Feb",
    "text": "Grand Vishnu temple known for its 100-pillar hall and hanging chain carved from a single stone."
  },
  {
    "id": "p112",
    "place": "Javadi Hills",
    "district": "Tiruvannamalai",
    "state": "Tamil Nadu",
    "category": "hill",
    "lat": 12.5167,
    "lng": 78.8333,
    "best": "Oct-Mar",
    "text": "Lesser-visited range of hills dotted with small tribal settlements and viewpoints."
  },
  {
    "id": "p113",
    "place": "Meghamalai",
    "district": "Theni",
    "state": "Tamil Nadu",
    "category": "hill",
    "lat": 9.7333,
    "lng": 77.3333,
    "best": "Sep-Mar",
    "text": "Remote 'cloud mountains' cardamom hills bordering Kerala, known for tea and coffee estates."
  },
  {
    "id": "p114",
    "place": "Sirumalai",
    "district": "Dindigul",
    "state": "Tamil Nadu",
    "category": "hill",
    "lat": 10.2667,
    "lng": 77.9833,
    "best": "Oct-Mar",
    "text": "Small hill station near Dindigul known for its orchards and cool climate."
  },
  {
    "id": "p115",
    "place": "Manjolai",
    "district": "Tirunelveli",
    "state": "Tamil Nadu",
    "category": "hill",
    "lat": 8.6167,
    "lng": 77.2667,
    "best": "Sep-Feb",
    "text": "High tea-estate plateau on the southern Western Ghats bordering Kerala."
  },
  {
    "id": "p116",
    "place": "Silver Beach",
    "district": "Cuddalore",
    "state": "Tamil Nadu",
    "category": "beach",
    "lat": 11.7167,
    "lng": 79.7833,
    "best": "Nov-Feb",
    "text": "One of India's widest beaches, a quiet stretch near Cuddalore town."
  },
  {
    "id": "p117",
    "place": "Tranquebar (Tharangambadi) Beach",
    "district": "Mayiladuthurai",
    "state": "Tamil Nadu",
    "category": "beach",
    "lat": 11.0297,
    "lng": 79.85,
    "best": "Nov-Feb",
    "text": "Former Danish colonial beach town with a fort right on the shore."
  },
  {
    "id": "p118",
    "place": "Manapad Beach",
    "district": "Thoothukudi",
    "state": "Tamil Nadu",
    "category": "beach",
    "lat": 8.4167,
    "lng": 78.0333,
    "best": "Nov-Feb",
    "text": "Historic fishing village beach with a centuries-old church on a rocky point."
  },
  {
    "id": "p119",
    "place": "Sathyamangalam Tiger Reserve",
    "district": "Erode",
    "state": "Tamil Nadu",
    "category": "wildlife",
    "lat": 11.5,
    "lng": 77.25,
    "best": "Dec-Apr",
    "text": "Forested tiger reserve connecting the Western and Eastern Ghats corridors."
  },
  {
    "id": "p120",
    "place": "Koonthankulam Bird Sanctuary",
    "district": "Tirunelveli",
    "state": "Tamil Nadu",
    "category": "wildlife",
    "lat": 8.4833,
    "lng": 77.7667,
    "best": "Nov-Feb",
    "text": "Village tank sanctuary famous for nesting painted storks and pelicans."
  },
  {
    "id": "p121",
    "place": "Karikili Bird Sanctuary",
    "district": "Kanchipuram",
    "state": "Tamil Nadu",
    "category": "wildlife",
    "lat": 12.6333,
    "lng": 79.9333,
    "best": "Nov-Feb",
    "text": "Small wetland sanctuary near Vedanthangal, good for a quieter birding visit."
  },
  {
    "id": "p122",
    "place": "Guindy National Park",
    "district": "Chennai",
    "state": "Tamil Nadu",
    "category": "wildlife",
    "lat": 13.0067,
    "lng": 80.2206,
    "best": "Nov-Feb",
    "text": "Rare city-limits national park with blackbuck and spotted deer."
  },
  {
    "id": "p123",
    "place": "Mukurthi National Park",
    "district": "The Nilgiris",
    "state": "Tamil Nadu",
    "category": "wildlife",
    "lat": 11.3667,
    "lng": 76.5333,
    "best": "Feb-May",
    "text": "High-altitude shola-grassland park protecting the Nilgiri tahr."
  },
  {
    "id": "p124",
    "place": "Kumbakkarai Falls",
    "district": "Dindigul",
    "state": "Tamil Nadu",
    "category": "waterfall",
    "lat": 10.1167,
    "lng": 77.5833,
    "best": "Jun-Sep",
    "text": "Multi-tiered falls near Kodaikanal, popular for its natural rock pools."
  },
  {
    "id": "p125",
    "place": "Monkey Falls (Aliyar)",
    "district": "Coimbatore",
    "state": "Tamil Nadu",
    "category": "waterfall",
    "lat": 10.4333,
    "lng": 76.9833,
    "best": "Jun-Sep",
    "text": "Roadside falls on the way to Valparai, named for the resident macaques."
  },
  {
    "id": "p126",
    "place": "Suruli Falls",
    "district": "Theni",
    "state": "Tamil Nadu",
    "category": "waterfall",
    "lat": 9.9667,
    "lng": 77.3167,
    "best": "Jun-Sep",
    "text": "Falls beside an ancient cave temple, believed to have medicinal properties."
  },
  {
    "id": "p127",
    "place": "Manimuthar Falls",
    "district": "Tirunelveli",
    "state": "Tamil Nadu",
    "category": "waterfall",
    "lat": 8.6833,
    "lng": 77.3167,
    "best": "Jun-Dec",
    "text": "Scenic falls near Manimuthar dam on the southern Western Ghats."
  },
  {
    "id": "p128",
    "place": "Agaya Gangai Falls",
    "district": "Kolli Hills",
    "state": "Tamil Nadu",
    "category": "waterfall",
    "lat": 11.2497,
    "lng": 78.3288,
    "best": "Jul-Jan",
    "text": "Kolli Hills' main waterfall, reached via a steep forest staircase."
  },
  {
    "id": "p129",
    "place": "Vattakottai Fort",
    "district": "Kanyakumari",
    "state": "Tamil Nadu",
    "category": "heritage",
    "lat": 8.1167,
    "lng": 77.4833,
    "best": "Nov-Feb",
    "text": "Coastal granite fort built by the Travancore kingdom, with sweeping sea views."
  },
  {
    "id": "p130",
    "place": "Thirumalai Nayakkar Mahal",
    "district": "Madurai",
    "state": "Tamil Nadu",
    "category": "heritage",
    "lat": 9.9195,
    "lng": 78.1225,
    "best": "Oct-Mar",
    "text": "17th-century Indo-Saracenic palace known for its massive courtyard and pillars."
  },
  {
    "id": "p131",
    "place": "Sankagiri Fort",
    "district": "Salem",
    "state": "Tamil Nadu",
    "category": "heritage",
    "lat": 11.4747,
    "lng": 77.8703,
    "best": "Nov-Feb",
    "text": "Hilltop fort with a long history under Chola, Vijayanagara and British rule."
  },
  {
    "id": "p132",
    "place": "Saraswathi Mahal Library & Art Gallery",
    "district": "Thanjavur",
    "state": "Tamil Nadu",
    "category": "museum",
    "lat": 10.8052,
    "lng": 79.1354,
    "best": "Oct-Mar",
    "text": "Historic royal library housing rare palm-leaf manuscripts and Chola-era paintings."
  },
  {
    "id": "p133",
    "place": "Vaigai Dam",
    "district": "Theni",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 9.9314,
    "lng": 77.572,
    "best": "Nov-Feb",
    "text": "Large reservoir and garden popular as a weekend picnic spot near Madurai."
  },
  {
    "id": "p134",
    "place": "Anna Zoological Park (Vandalur Zoo)",
    "district": "Chennai",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 12.8827,
    "lng": 80.08,
    "best": "Nov-Feb",
    "text": "One of South Asia's largest zoos, on the outskirts of Chennai."
  },
  {
    "id": "p135",
    "place": "Amirthi Zoological Park",
    "district": "Vellore",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 12.7333,
    "lng": 78.7667,
    "best": "Nov-Feb",
    "text": "Small forested zoo and picnic spot in the hills near Vellore."
  },
  {
    "id": "p136",
    "place": "Kodungallur Bhagavathy Temple",
    "district": "Thrissur",
    "state": "Kerala",
    "category": "temple",
    "lat": 10.2333,
    "lng": 76.1833,
    "best": "Nov-Feb",
    "text": "Ancient Devi temple known for its energetic Bharani festival."
  },
  {
    "id": "p137",
    "place": "Sree Poornathrayeesa Temple",
    "district": "Ernakulam",
    "state": "Kerala",
    "category": "temple",
    "lat": 9.9436,
    "lng": 76.3475,
    "best": "Nov-Feb",
    "text": "Krishna temple in Tripunithura famous for its elephant-led Vrischikolsavam festival."
  },
  {
    "id": "p138",
    "place": "Thiruvalla Sri Vallabha Temple",
    "district": "Pathanamthitta",
    "state": "Kerala",
    "category": "temple",
    "lat": 9.3833,
    "lng": 76.5667,
    "best": "Nov-Feb",
    "text": "One of Kerala's oldest Vishnu temples, mentioned in ancient Tamil literature."
  },
  {
    "id": "p139",
    "place": "Ettumanoor Mahadeva Temple",
    "district": "Kottayam",
    "state": "Kerala",
    "category": "temple",
    "lat": 9.6833,
    "lng": 76.55,
    "best": "Nov-Feb",
    "text": "Shiva temple renowned for its mural paintings and annual Ettumanoor Arattu."
  },
  {
    "id": "p140",
    "place": "Kottiyoor Temple",
    "district": "Kannur",
    "state": "Kerala",
    "category": "temple",
    "lat": 11.8667,
    "lng": 75.9333,
    "best": "Apr-Jun",
    "text": "Forest shrine active only during an annual festival, reached by trekking through a river."
  },
  {
    "id": "p141",
    "place": "Chembra Peak",
    "district": "Wayanad",
    "state": "Kerala",
    "category": "hill",
    "lat": 11.5,
    "lng": 76.1,
    "best": "Sep-Mar",
    "text": "Wayanad's highest peak, famous for its heart-shaped lake on the trekking route."
  },
  {
    "id": "p142",
    "place": "Ramakkalmedu",
    "district": "Idukki",
    "state": "Kerala",
    "category": "hill",
    "lat": 9.7,
    "lng": 77.0333,
    "best": "Sep-May",
    "text": "Windswept viewpoint lined with wind turbines, on the border with Tamil Nadu."
  },
  {
    "id": "p143",
    "place": "Gavi",
    "district": "Pathanamthitta",
    "state": "Kerala",
    "category": "nature",
    "lat": 9.3167,
    "lng": 77.1667,
    "best": "Sep-Apr",
    "text": "Remote eco-tourism forest reserve near Periyar, reachable only with prior permits."
  },
  {
    "id": "p144",
    "place": "Anamudi Peak",
    "district": "Idukki",
    "state": "Kerala",
    "category": "adventure",
    "lat": 10.1667,
    "lng": 77.0667,
    "best": "Sep-Apr",
    "text": "Highest peak in South India, a permitted trek through Eravikulam National Park."
  },
  {
    "id": "p145",
    "place": "Meesapulimala",
    "district": "Idukki",
    "state": "Kerala",
    "category": "adventure",
    "lat": 10.15,
    "lng": 77.1333,
    "best": "Sep-Mar",
    "text": "Second-highest peak in South India, a popular overnight trekking route from Munnar."
  },
  {
    "id": "p146",
    "place": "Banasura Sagar Dam",
    "district": "Wayanad",
    "state": "Kerala",
    "category": "nature",
    "lat": 11.6667,
    "lng": 76.05,
    "best": "Sep-Mar",
    "text": "Largest earthen dam in India, with boating and island trekking nearby."
  },
  {
    "id": "p147",
    "place": "Payyambalam Beach",
    "district": "Kannur",
    "state": "Kerala",
    "category": "beach",
    "lat": 11.8745,
    "lng": 75.3704,
    "best": "Oct-Mar",
    "text": "Long, clean beach with a sculpture park, on the edge of Kannur town."
  },
  {
    "id": "p148",
    "place": "Muzhappilangad Drive-in Beach",
    "district": "Kannur",
    "state": "Kerala",
    "category": "beach",
    "lat": 11.7167,
    "lng": 75.4667,
    "best": "Oct-Mar",
    "text": "India's longest drive-in beach, a 4km stretch open to vehicles at low tide."
  },
  {
    "id": "p149",
    "place": "Thirumullavaram Beach",
    "district": "Kollam",
    "state": "Kerala",
    "category": "beach",
    "lat": 8.9167,
    "lng": 76.5833,
    "best": "Oct-Mar",
    "text": "Quiet rocky-cove beach near Kollam town, popular with locals at sunset."
  },
  {
    "id": "p150",
    "place": "Kozhikode Beach",
    "district": "Kozhikode",
    "state": "Kerala",
    "category": "beach",
    "lat": 11.2497,
    "lng": 75.7804,
    "best": "Oct-Mar",
    "text": "City beach with a pier and lighthouse, a lively evening spot in Kozhikode."
  },
  {
    "id": "p151",
    "place": "Neyyar Wildlife Sanctuary",
    "district": "Thiruvananthapuram",
    "state": "Kerala",
    "category": "wildlife",
    "lat": 8.5667,
    "lng": 77.1167,
    "best": "Dec-Apr",
    "text": "Forest sanctuary around Neyyar Dam with a lion safari park and crocodile farm."
  },
  {
    "id": "p152",
    "place": "Aralam Wildlife Sanctuary",
    "district": "Kannur",
    "state": "Kerala",
    "category": "wildlife",
    "lat": 11.85,
    "lng": 75.95,
    "best": "Dec-Apr",
    "text": "Remote northern Kerala sanctuary bordering Karnataka's Western Ghats forests."
  },
  {
    "id": "p153",
    "place": "Kadalundi Bird Sanctuary",
    "district": "Kozhikode",
    "state": "Kerala",
    "category": "wildlife",
    "lat": 11.1333,
    "lng": 75.8167,
    "best": "Nov-Feb",
    "text": "Estuarine sanctuary where migratory shorebirds gather among mangrove islands."
  },
  {
    "id": "p154",
    "place": "Thattekad Bird Sanctuary",
    "district": "Ernakulam",
    "state": "Kerala",
    "category": "wildlife",
    "lat": 10.1167,
    "lng": 76.7167,
    "best": "Nov-Feb",
    "text": "Kerala's first bird sanctuary, renowned among birdwatchers for its density of species."
  },
  {
    "id": "p155",
    "place": "Chethalayam Falls",
    "district": "Wayanad",
    "state": "Kerala",
    "category": "waterfall",
    "lat": 11.6167,
    "lng": 76.0667,
    "best": "Jun-Nov",
    "text": "Forest waterfall near Kalpetta, a short trek from the main road."
  },
  {
    "id": "p156",
    "place": "Kanthanpara Falls",
    "district": "Wayanad",
    "state": "Kerala",
    "category": "waterfall",
    "lat": 11.5833,
    "lng": 76.1,
    "best": "Jun-Nov",
    "text": "Family-friendly falls with a shallow pool, popular for a quick dip."
  },
  {
    "id": "p157",
    "place": "Cheeyappara & Valara Falls",
    "district": "Idukki",
    "state": "Kerala",
    "category": "waterfall",
    "lat": 10.05,
    "lng": 76.8833,
    "best": "Jun-Nov",
    "text": "Twin roadside waterfalls on the Munnar highway, easy stop for photos."
  },
  {
    "id": "p158",
    "place": "St. Angelo Fort",
    "district": "Kannur",
    "state": "Kerala",
    "category": "heritage",
    "lat": 11.876,
    "lng": 75.3568,
    "best": "Oct-Mar",
    "text": "16th-century Portuguese sea fort overlooking Kannur's harbour."
  },
  {
    "id": "p159",
    "place": "Thalassery Fort",
    "district": "Kannur",
    "state": "Kerala",
    "category": "heritage",
    "lat": 11.75,
    "lng": 75.4833,
    "best": "Oct-Mar",
    "text": "British-era fort in a town famous as the birthplace of Kerala's circus tradition."
  },
  {
    "id": "p160",
    "place": "Krishnapuram Palace",
    "district": "Alappuzha",
    "state": "Kerala",
    "category": "heritage",
    "lat": 9.2833,
    "lng": 76.4833,
    "best": "Oct-Mar",
    "text": "Travancore-era palace museum housing the large 'Gajendra Moksham' mural."
  },
  {
    "id": "p161",
    "place": "Kuthiramalika Palace Museum",
    "district": "Thiruvananthapuram",
    "state": "Kerala",
    "category": "museum",
    "lat": 8.4833,
    "lng": 76.945,
    "best": "Oct-Mar",
    "text": "19th-century palace named for its 122 carved wooden horses, built by a Travancore king."
  },
  {
    "id": "p162",
    "place": "Thiruvaiyaru Panchanatheeswarar Temple",
    "district": "Thanjavur",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 10.8833,
    "lng": 79.0667,
    "best": "Oct-Feb",
    "text": "Riverside Shiva temple famed for its annual Thyagaraja music festival."
  },
  {
    "id": "p163",
    "place": "Tiruvidaimarudur Mahalingaswamy Temple",
    "district": "Thanjavur",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 10.95,
    "lng": 79.4667,
    "best": "Oct-Feb",
    "text": "One of the largest Shiva temple complexes in the Kaveri delta."
  },
  {
    "id": "p164",
    "place": "Mayuranathaswami Temple",
    "district": "Mayiladuthurai",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 11.1028,
    "lng": 79.6528,
    "best": "Oct-Feb",
    "text": "Ancient Shiva temple giving Mayiladuthurai (Mayuram) its name."
  },
  {
    "id": "p165",
    "place": "Papanasam Shiva Temple",
    "district": "Thanjavur",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 10.8667,
    "lng": 79.2667,
    "best": "Oct-Feb",
    "text": "Riverside temple town on the Kaveri, believed to wash away sins for pilgrims."
  },
  {
    "id": "p166",
    "place": "Tiruchengodu Ardhanareeswarar Temple",
    "district": "Namakkal",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 11.3833,
    "lng": 77.8833,
    "best": "Oct-Feb",
    "text": "Hilltop temple to Shiva-Parvati's combined form, reached by a long stepped path."
  },
  {
    "id": "p167",
    "place": "Thirukalukundram Vedagiriswarar Temple",
    "district": "Chengalpattu",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 12.6,
    "lng": 79.9167,
    "best": "Oct-Feb",
    "text": "Hilltop shrine once known for a daily visit by a pair of sacred eagles."
  },
  {
    "id": "p168",
    "place": "Adhipureeswarar Temple",
    "district": "Tiruvottiyur",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 13.15,
    "lng": 80.3,
    "best": "Oct-Feb",
    "text": "One of the oldest temples in Chennai, mentioned in ancient Tamil hymns."
  },
  {
    "id": "p169",
    "place": "Marundeeswarar Temple",
    "district": "Thiruvanmiyur",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 12.9833,
    "lng": 80.2667,
    "best": "Oct-Feb",
    "text": "Coastal Shiva temple believed to house medicinal herbs blessed by sages."
  },
  {
    "id": "p170",
    "place": "Parthasarathy Temple",
    "district": "Triplicane",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 13.0592,
    "lng": 80.2792,
    "best": "Oct-Feb",
    "text": "One of Chennai's oldest Vishnu temples, over a thousand years old."
  },
  {
    "id": "p171",
    "place": "Vaikunta Perumal Temple",
    "district": "Kanchipuram",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 12.838,
    "lng": 79.705,
    "best": "Nov-Feb",
    "text": "8th-century Pallava-era Vishnu temple with a distinctive multi-storey sanctum."
  },
  {
    "id": "p172",
    "place": "Kamakshi Amman Temple",
    "district": "Kanchipuram",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 12.8347,
    "lng": 79.6997,
    "best": "Nov-Feb",
    "text": "One of the Shakti Peethas, among the most important Devi temples in South India."
  },
  {
    "id": "p173",
    "place": "Nellaiappar Temple",
    "district": "Tirunelveli",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 8.7167,
    "lng": 77.75,
    "best": "Oct-Feb",
    "text": "Riverside Shiva temple known for its musical pillars carved from single stones."
  },
  {
    "id": "p174",
    "place": "Tiruchendur Murugan Temple",
    "district": "Thoothukudi",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 8.4967,
    "lng": 78.12,
    "best": "Oct-Feb",
    "text": "One of Murugan's six abodes, uniquely built directly facing the sea."
  },
  {
    "id": "p175",
    "place": "Pazhamudircholai Murugan Temple",
    "district": "Madurai",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 9.9333,
    "lng": 78.2833,
    "best": "Oct-Feb",
    "text": "Forest hillside shrine, one of Murugan's six sacred abodes near Madurai."
  },
  {
    "id": "p176",
    "place": "Kutralanathar Temple",
    "district": "Tenkasi",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 8.9333,
    "lng": 77.2833,
    "best": "Oct-Feb",
    "text": "Shiva temple beside the Courtallam falls, especially lively during monsoon season."
  },
  {
    "id": "p177",
    "place": "Kasi Viswanathar Temple",
    "district": "Tenkasi",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 8.96,
    "lng": 77.31,
    "best": "Oct-Feb",
    "text": "Large Shiva temple giving Tenkasi its name as the 'Kasi of the South'."
  },
  {
    "id": "p178",
    "place": "Sankaranarayanar Temple",
    "district": "Sankarankovil",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 9.1667,
    "lng": 77.55,
    "best": "Oct-Feb",
    "text": "Rare temple honouring Shiva and Vishnu as a single combined deity."
  },
  {
    "id": "p179",
    "place": "Srivilliputhur Andal Temple",
    "district": "Virudhunagar",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 9.5167,
    "lng": 77.6333,
    "best": "Oct-Feb",
    "text": "Temple to the poet-saint Andal, its tower is depicted on Tamil Nadu's state emblem."
  },
  {
    "id": "p180",
    "place": "Alwarthirunagari Adinathar Temple",
    "district": "Thoothukudi",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 8.6167,
    "lng": 78.0167,
    "best": "Oct-Feb",
    "text": "Birthplace shrine of the Vaishnavite saint Nammalvar."
  },
  {
    "id": "p181",
    "place": "Perur Pateeswarar Temple",
    "district": "Coimbatore",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 11.0,
    "lng": 76.9333,
    "best": "Oct-Feb",
    "text": "Riverside Shiva temple known for its elaborate stone and wood carvings."
  },
  {
    "id": "p182",
    "place": "Marudhamalai Murugan Temple",
    "district": "Coimbatore",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 11.0733,
    "lng": 76.8894,
    "best": "Oct-Feb",
    "text": "Hilltop Murugan temple overlooking Coimbatore city, reached by road or steps."
  },
  {
    "id": "p183",
    "place": "Bhavani Sangameswarar Temple",
    "district": "Erode",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 11.45,
    "lng": 77.6833,
    "best": "Oct-Feb",
    "text": "Temple at the sacred confluence of the Kaveri and Bhavani rivers."
  },
  {
    "id": "p184",
    "place": "Pasupatheeswarar Temple",
    "district": "Karur",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 10.95,
    "lng": 78.0833,
    "best": "Oct-Feb",
    "text": "Ancient riverside Shiva temple in Karur town."
  },
  {
    "id": "p185",
    "place": "Vedaranyeswarar Temple",
    "district": "Vedaranyam",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 10.3667,
    "lng": 79.85,
    "best": "Oct-Feb",
    "text": "Coastal Shiva temple in the town famous for Gandhi's 1930 salt satyagraha."
  },
  {
    "id": "p186",
    "place": "Nagaraja Temple",
    "district": "Nagercoil",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 8.1833,
    "lng": 77.4333,
    "best": "Oct-Feb",
    "text": "Unique temple giving Nagercoil its name, dedicated to the serpent deity."
  },
  {
    "id": "p187",
    "place": "Uraiyur Kamalavalli Nachiyar Temple",
    "district": "Tiruchirappalli",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 10.8167,
    "lng": 78.7,
    "best": "Oct-Feb",
    "text": "Ancient temple in Trichy's old Chola capital quarter of Uraiyur."
  },
  {
    "id": "p188",
    "place": "Thiruvellarai Pundarikakshan Perumal Temple",
    "district": "Tiruchirappalli",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 10.95,
    "lng": 78.6167,
    "best": "Oct-Feb",
    "text": "One of the oldest Divya Desam Vishnu temples, on the banks of the Kollidam."
  },
  {
    "id": "p189",
    "place": "Thirukoshtiyur Temple",
    "district": "Sivaganga",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 9.7667,
    "lng": 78.3667,
    "best": "Oct-Feb",
    "text": "Historic Vishnu temple important in the teachings of the philosopher Ramanuja."
  },
  {
    "id": "p190",
    "place": "Namakkal Anjaneyar Temple",
    "district": "Namakkal",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 11.2231,
    "lng": 78.1653,
    "best": "Oct-Feb",
    "text": "Temple famed for its towering monolithic Hanuman statue carved into a rock."
  },
  {
    "id": "p191",
    "place": "Kudumiyanmalai Temple",
    "district": "Pudukkottai",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 10.3833,
    "lng": 78.7833,
    "best": "Oct-Feb",
    "text": "Rock-cut Shiva temple with a rare ancient inscription of musical notation."
  },
  {
    "id": "p192",
    "place": "Kalayar Kovil Temple",
    "district": "Sivaganga",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 9.9333,
    "lng": 78.5667,
    "best": "Oct-Feb",
    "text": "Historic Shiva-Vishnu temple town in the Sivaganga countryside."
  },
  {
    "id": "p193",
    "place": "Kundrakudi Murugan Temple",
    "district": "Sivaganga",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 10.05,
    "lng": 78.6167,
    "best": "Oct-Feb",
    "text": "Hilltop Murugan shrine known for its large flagstaff and rock steps."
  },
  {
    "id": "p194",
    "place": "Pillaiyarpatti Karpaga Vinayagar Temple",
    "district": "Sivaganga",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 10.1333,
    "lng": 78.6667,
    "best": "Oct-Feb",
    "text": "Rock-cut Ganesha temple, one of the oldest cave temples in the Chettinad region."
  },
  {
    "id": "p195",
    "place": "Koodal Azhagar Temple",
    "district": "Madurai",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 9.9167,
    "lng": 78.1167,
    "best": "Oct-Feb",
    "text": "Ancient Vishnu temple in Madurai, mentioned in early Tamil Sangam literature."
  },
  {
    "id": "p196",
    "place": "Sripuram Golden Temple",
    "district": "Vellore",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 12.6333,
    "lng": 79.15,
    "best": "Nov-Feb",
    "text": "Modern Mahalakshmi shrine famous for its gold-plated exterior set amid landscaped gardens."
  },
  {
    "id": "p197",
    "place": "Chennimalai Murugan Temple",
    "district": "Erode",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 11.15,
    "lng": 77.6167,
    "best": "Oct-Feb",
    "text": "Hilltop Murugan temple near Erode, popular with local pilgrims."
  },
  {
    "id": "p198",
    "place": "Vettuvan Koil",
    "district": "Kalugumalai",
    "state": "Tamil Nadu",
    "category": "heritage",
    "lat": 9.1667,
    "lng": 77.8833,
    "best": "Oct-Feb",
    "text": "Unfinished 8th-century monolithic rock-cut temple, carved top-down out of a single boulder."
  },
  {
    "id": "p199",
    "place": "Fort Dansborg (Tranquebar Fort)",
    "district": "Mayiladuthurai",
    "state": "Tamil Nadu",
    "category": "heritage",
    "lat": 11.0297,
    "lng": 79.85,
    "best": "Nov-Feb",
    "text": "17th-century Danish colonial fort standing right on the Tharangambadi shoreline."
  },
  {
    "id": "p200",
    "place": "Tirumalai Jain Temple Caves",
    "district": "Tiruvannamalai",
    "state": "Tamil Nadu",
    "category": "heritage",
    "lat": 12.5,
    "lng": 79.1667,
    "best": "Nov-Feb",
    "text": "12th-century rock-cut Jain temple complex with a reclining Tirthankara sculpture."
  },
  {
    "id": "p201",
    "place": "Namakkal Fort",
    "district": "Namakkal",
    "state": "Tamil Nadu",
    "category": "heritage",
    "lat": 11.2189,
    "lng": 78.1674,
    "best": "Nov-Feb",
    "text": "Ancient hill fort with rock-cut chambers, later used by the Vijayanagara and British."
  },
  {
    "id": "p202",
    "place": "Bhuvanagiri Fort",
    "district": "Cuddalore",
    "state": "Tamil Nadu",
    "category": "heritage",
    "lat": 11.7667,
    "lng": 79.4667,
    "best": "Nov-Feb",
    "text": "Hilltop Pallava-era fort ruin near Cuddalore, offering wide countryside views."
  },
  {
    "id": "p203",
    "place": "Dindigul Fort",
    "district": "Dindigul",
    "state": "Tamil Nadu",
    "category": "heritage",
    "lat": 10.35,
    "lng": 77.95,
    "best": "Nov-Feb",
    "text": "Rock hill fort built by Vijayanagara rulers, later held by Hyder Ali and Tipu Sultan."
  },
  {
    "id": "p204",
    "place": "Krishnagiri Fort",
    "district": "Krishnagiri",
    "state": "Tamil Nadu",
    "category": "heritage",
    "lat": 12.5167,
    "lng": 78.2167,
    "best": "Nov-Feb",
    "text": "Hill fort overlooking Krishnagiri town, with a checkered Vijayanagara-to-British history."
  },
  {
    "id": "p205",
    "place": "Thirumayam Fort",
    "district": "Pudukkottai",
    "state": "Tamil Nadu",
    "category": "heritage",
    "lat": 10.2833,
    "lng": 78.7,
    "best": "Nov-Feb",
    "text": "18th-century fort built by a local chieftain, with cannons and a temple inside its walls."
  },
  {
    "id": "p206",
    "place": "Chettinad Palace",
    "district": "Kanadukathan",
    "state": "Tamil Nadu",
    "category": "heritage",
    "lat": 10.0833,
    "lng": 78.7833,
    "best": "Oct-Feb",
    "text": "Grand ancestral mansion of the Chettiar community, famed for Athangudi tiles and teakwood."
  },
  {
    "id": "p207",
    "place": "Sittanavasal Cave Temple",
    "district": "Pudukkottai",
    "state": "Tamil Nadu",
    "category": "heritage",
    "lat": 10.4833,
    "lng": 78.7333,
    "best": "Nov-Feb",
    "text": "2nd-century Jain cave shrine with rare, faded fresco paintings on its ceiling."
  },
  {
    "id": "p208",
    "place": "Kallanai (Grand Anicut)",
    "district": "Tiruchirappalli",
    "state": "Tamil Nadu",
    "category": "heritage",
    "lat": 10.8167,
    "lng": 78.9333,
    "best": "Nov-Feb",
    "text": "One of the world's oldest water-diversion dams still in use, built by the Cholas nearly 2000 years ago."
  },
  {
    "id": "p209",
    "place": "Vivekananda Rock Memorial",
    "district": "Kanyakumari",
    "state": "Tamil Nadu",
    "category": "heritage",
    "lat": 8.0778,
    "lng": 77.5511,
    "best": "Nov-Feb",
    "text": "Memorial on a rock islet reached by ferry, marking where Swami Vivekananda meditated."
  },
  {
    "id": "p210",
    "place": "Thiruvalluvar Statue",
    "district": "Kanyakumari",
    "state": "Tamil Nadu",
    "category": "heritage",
    "lat": 8.0764,
    "lng": 77.5514,
    "best": "Nov-Feb",
    "text": "133-foot statue of the Tamil poet-philosopher, standing beside the Vivekananda Rock."
  },
  {
    "id": "p211",
    "place": "Mel Sithamur Jain Math",
    "district": "Perambalur",
    "state": "Tamil Nadu",
    "category": "heritage",
    "lat": 11.3667,
    "lng": 78.8333,
    "best": "Nov-Feb",
    "text": "Historic Jain monastery, one of the oldest surviving Jain centres in Tamil Nadu."
  },
  {
    "id": "p212",
    "place": "Isha Yoga Center (Adiyogi Statue)",
    "district": "Coimbatore",
    "state": "Tamil Nadu",
    "category": "heritage",
    "lat": 11.0167,
    "lng": 76.7333,
    "best": "Oct-Mar",
    "text": "Spiritual centre at the Velliangiri foothills, home to a 112-foot Adiyogi Shiva statue."
  },
  {
    "id": "p213",
    "place": "Kalrayan Hills",
    "district": "Salem",
    "state": "Tamil Nadu",
    "category": "hill",
    "lat": 11.7833,
    "lng": 78.5667,
    "best": "Oct-Mar",
    "text": "Remote hill range known for its waterfalls and terrace farming."
  },
  {
    "id": "p214",
    "place": "Pachamalai Hills",
    "district": "Tiruchirappalli",
    "state": "Tamil Nadu",
    "category": "hill",
    "lat": 11.2333,
    "lng": 78.5667,
    "best": "Oct-Mar",
    "text": "Little-visited 'green hills' with tribal hamlets and forest trails."
  },
  {
    "id": "p215",
    "place": "Mannavanur",
    "district": "Kodaikanal",
    "state": "Tamil Nadu",
    "category": "hill",
    "lat": 10.1,
    "lng": 77.3667,
    "best": "Sep-May",
    "text": "Grassland plateau near Kodaikanal with a sheep farm and lake, cooler than the town itself."
  },
  {
    "id": "p216",
    "place": "Vattakanal",
    "district": "Kodaikanal",
    "state": "Tamil Nadu",
    "category": "hill",
    "lat": 10.2167,
    "lng": 77.4833,
    "best": "Sep-May",
    "text": "Small backpacker village near Kodaikanal known for its cliffside views."
  },
  {
    "id": "p217",
    "place": "Poombarai",
    "district": "Kodaikanal",
    "state": "Tamil Nadu",
    "category": "hill",
    "lat": 10.3167,
    "lng": 77.4667,
    "best": "Sep-May",
    "text": "Terraced-farm village on the Kodaikanal plateau with sweeping valley views."
  },
  {
    "id": "p218",
    "place": "Kookal",
    "district": "Kodaikanal",
    "state": "Tamil Nadu",
    "category": "hill",
    "lat": 10.3,
    "lng": 77.4167,
    "best": "Sep-May",
    "text": "Remote hamlet beyond Kodaikanal known for its lake and quiet forest trails."
  },
  {
    "id": "p219",
    "place": "Anaikatti",
    "district": "Coimbatore",
    "state": "Tamil Nadu",
    "category": "hill",
    "lat": 11.05,
    "lng": 76.75,
    "best": "Oct-Mar",
    "text": "Foothill town on the Kerala border, gateway to the Siruvani hills."
  },
  {
    "id": "p220",
    "place": "Doddabetta Peak",
    "district": "The Nilgiris",
    "state": "Tamil Nadu",
    "category": "hill",
    "lat": 11.4064,
    "lng": 76.7397,
    "best": "Sep-May",
    "text": "Highest peak in the Nilgiris, with a telescope house offering panoramic views."
  },
  {
    "id": "p221",
    "place": "Thoovanam Falls",
    "district": "Coimbatore",
    "state": "Tamil Nadu",
    "category": "waterfall",
    "lat": 10.35,
    "lng": 76.95,
    "best": "Jun-Sep",
    "text": "Remote falls inside the Indira Gandhi Wildlife Sanctuary near Top Slip."
  },
  {
    "id": "p222",
    "place": "Vattaparai Falls",
    "district": "Coimbatore",
    "state": "Tamil Nadu",
    "category": "waterfall",
    "lat": 10.4667,
    "lng": 77.0,
    "best": "Jun-Sep",
    "text": "Rocky cascade near Pollachi, popular with local day-trippers."
  },
  {
    "id": "p223",
    "place": "Agasthiyar Falls (Papanasam)",
    "district": "Tirunelveli",
    "state": "Tamil Nadu",
    "category": "waterfall",
    "lat": 8.6167,
    "lng": 77.4,
    "best": "Jun-Dec",
    "text": "Sacred falls near the Papanasam dam, believed to wash away sins."
  },
  {
    "id": "p224",
    "place": "Tiger Falls, Courtallam",
    "district": "Tenkasi",
    "state": "Tamil Nadu",
    "category": "waterfall",
    "lat": 8.93,
    "lng": 77.275,
    "best": "Jun-Sep",
    "text": "One of the five Courtallam falls, named for the roar of its water."
  },
  {
    "id": "p225",
    "place": "Old Falls, Courtallam",
    "district": "Tenkasi",
    "state": "Tamil Nadu",
    "category": "waterfall",
    "lat": 8.92,
    "lng": 77.27,
    "best": "Jun-Sep",
    "text": "The original and most visited of the Courtallam falls cluster."
  },
  {
    "id": "p226",
    "place": "Vallanadu Blackbuck Sanctuary",
    "district": "Thoothukudi",
    "state": "Tamil Nadu",
    "category": "wildlife",
    "lat": 8.75,
    "lng": 77.85,
    "best": "Nov-Feb",
    "text": "Scrub-forest sanctuary protecting one of Tamil Nadu's blackbuck populations."
  },
  {
    "id": "p227",
    "place": "Mahendragiri Wildlife Sanctuary",
    "district": "Kanyakumari",
    "state": "Tamil Nadu",
    "category": "wildlife",
    "lat": 8.3,
    "lng": 77.3,
    "best": "Dec-Mar",
    "text": "Forested hill sanctuary near Kanyakumari, part of the Western Ghats biodiversity belt."
  },
  {
    "id": "p228",
    "place": "Srivilliputhur Grizzled Squirrel Sanctuary",
    "district": "Virudhunagar",
    "state": "Tamil Nadu",
    "category": "wildlife",
    "lat": 9.6167,
    "lng": 77.6333,
    "best": "Dec-Mar",
    "text": "Protected forest for the endangered grizzled giant squirrel near Srivilliputhur."
  },
  {
    "id": "p229",
    "place": "Poompuhar Beach",
    "district": "Mayiladuthurai",
    "state": "Tamil Nadu",
    "category": "beach",
    "lat": 11.1333,
    "lng": 79.85,
    "best": "Nov-Feb",
    "text": "Historic beach town believed to be the site of an ancient submerged Chola port."
  },
  {
    "id": "p230",
    "place": "Marakkanam Beach",
    "district": "Villupuram",
    "state": "Tamil Nadu",
    "category": "beach",
    "lat": 12.2,
    "lng": 79.9333,
    "best": "Nov-Feb",
    "text": "Quiet beach town known for its salt pans and old Dutch-era pond."
  },
  {
    "id": "p231",
    "place": "Colachel Beach",
    "district": "Kanyakumari",
    "state": "Tamil Nadu",
    "category": "beach",
    "lat": 8.1667,
    "lng": 77.2667,
    "best": "Nov-Feb",
    "text": "Historic fishing-town beach, site of a notable 1741 naval battle."
  },
  {
    "id": "p232",
    "place": "Emerald Lake",
    "district": "The Nilgiris",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 11.3667,
    "lng": 76.5667,
    "best": "Sep-May",
    "text": "Secluded reservoir in the upper Nilgiris surrounded by dense shola forest."
  },
  {
    "id": "p233",
    "place": "Avalanche Lake",
    "district": "The Nilgiris",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 11.3,
    "lng": 76.55,
    "best": "Sep-May",
    "text": "Remote forest lake near Ooty, named after a historic landslide in the area."
  },
  {
    "id": "p234",
    "place": "Aliyar Dam",
    "district": "Coimbatore",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 10.4333,
    "lng": 76.9833,
    "best": "Nov-Feb",
    "text": "Reservoir and garden park at the foot of the Anamalai hills near Pollachi."
  },
  {
    "id": "p235",
    "place": "Amaravathi Dam",
    "district": "Tiruppur",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 10.3667,
    "lng": 77.2833,
    "best": "Nov-Feb",
    "text": "Reservoir with an attached crocodile farm on the edge of the Anamalai reserve."
  },
  {
    "id": "p236",
    "place": "Stanley Reservoir (Mettur Dam)",
    "district": "Salem",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 11.7833,
    "lng": 77.8,
    "best": "Nov-Feb",
    "text": "One of India's largest dams, forming a vast reservoir on the Kaveri river."
  },
  {
    "id": "p237",
    "place": "Krishnagiri Dam",
    "district": "Krishnagiri",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 12.5333,
    "lng": 78.1833,
    "best": "Nov-Feb",
    "text": "Reservoir and garden park popular for weekend picnics near Krishnagiri town."
  },
  {
    "id": "p238",
    "place": "Sathanur Dam",
    "district": "Tiruvannamalai",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 12.2333,
    "lng": 78.9667,
    "best": "Nov-Feb",
    "text": "Dam and crocodile park on the Thenpennai river with a small amusement park."
  },
  {
    "id": "p239",
    "place": "Bhavanisagar Dam",
    "district": "Erode",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 11.4833,
    "lng": 77.1167,
    "best": "Nov-Feb",
    "text": "Large reservoir at the confluence point feeding the Bhavani river."
  },
  {
    "id": "p240",
    "place": "Guna Caves (Devil's Kitchen)",
    "district": "Kodaikanal",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 10.2333,
    "lng": 77.4667,
    "best": "Sep-May",
    "text": "Mysterious rock-cave formation near Kodaikanal, named after a popular Tamil film."
  },
  {
    "id": "p241",
    "place": "Pillar Rocks",
    "district": "Kodaikanal",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 10.2167,
    "lng": 77.4667,
    "best": "Sep-May",
    "text": "Three vertical rock formations rising dramatically from the Kodaikanal hillside."
  },
  {
    "id": "p242",
    "place": "Kodaikanal Lake",
    "district": "Dindigul",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 10.2381,
    "lng": 77.4892,
    "best": "Sep-May",
    "text": "Star-shaped artificial lake at the centre of Kodaikanal town, popular for boating."
  },
  {
    "id": "p243",
    "place": "VOC Park & Zoo",
    "district": "Coimbatore",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 11.0,
    "lng": 76.9667,
    "best": "Nov-Feb",
    "text": "City park and small zoo in central Coimbatore, popular with families."
  },
  {
    "id": "p244",
    "place": "Kovai Kutralam Falls",
    "district": "Coimbatore",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 11.3333,
    "lng": 76.95,
    "best": "Jun-Sep",
    "text": "Waterfall and forest park near Coimbatore, a popular monsoon getaway."
  },
  {
    "id": "p245",
    "place": "Siruvani Falls & Dam",
    "district": "Coimbatore",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 11.0333,
    "lng": 76.6333,
    "best": "Jun-Sep",
    "text": "Forest dam near the Kerala border, said to have some of the sweetest water in India."
  },
  {
    "id": "p246",
    "place": "Poondi Reservoir",
    "district": "Tiruvallur",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 13.2833,
    "lng": 79.9167,
    "best": "Nov-Feb",
    "text": "Major reservoir supplying Chennai's drinking water, with a scenic dam-top road."
  },
  {
    "id": "p247",
    "place": "Kodiveri Dam",
    "district": "Erode",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 11.25,
    "lng": 77.1833,
    "best": "Nov-Feb",
    "text": "Small dam and garden on the Bhavani river, popular for a short family outing."
  },
  {
    "id": "p248",
    "place": "Mukkombu (Upper Anicut)",
    "district": "Tiruchirappalli",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 10.9333,
    "lng": 78.6167,
    "best": "Nov-Feb",
    "text": "Riverside park at the point where the Kaveri splits into the Kollidam."
  },
  {
    "id": "p249",
    "place": "Puliyancholai Falls",
    "district": "Tiruchirappalli",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 10.9333,
    "lng": 78.6333,
    "best": "Jun-Sep",
    "text": "Small seasonal falls and picnic spot in the hills near Trichy."
  },
  {
    "id": "p250",
    "place": "Muttom Beach",
    "district": "Kanyakumari",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 8.1333,
    "lng": 77.3167,
    "best": "Nov-Feb",
    "text": "Rocky beach with a lighthouse, quieter than nearby Kanyakumari town."
  },
  {
    "id": "p251",
    "place": "Fort Museum, Fort St. George",
    "district": "Chennai",
    "state": "Tamil Nadu",
    "category": "museum",
    "lat": 13.0797,
    "lng": 80.287,
    "best": "Nov-Feb",
    "text": "Museum inside the fort walls housing colonial-era artefacts, weapons and paintings."
  },
  {
    "id": "p252",
    "place": "Manjampatti Valley Trek",
    "district": "Coimbatore",
    "state": "Tamil Nadu",
    "category": "adventure",
    "lat": 10.35,
    "lng": 77.0,
    "best": "Dec-Mar",
    "text": "Remote dry-forest valley trek on the Tamil Nadu-Kerala border inside the Anamalai reserve."
  },
  {
    "id": "p253",
    "place": "Grass Hills Trek (Anaimalai)",
    "district": "Coimbatore",
    "state": "Tamil Nadu",
    "category": "adventure",
    "lat": 10.3833,
    "lng": 77.0167,
    "best": "Dec-Mar",
    "text": "High-altitude shola-grassland trekking route inside the Anamalai Tiger Reserve."
  },
  {
    "id": "p254",
    "place": "Suryanar Kovil",
    "district": "Kumbakonam",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 10.9833,
    "lng": 79.4667,
    "best": "Oct-Feb",
    "text": "Sun temple, part of the Navagraha (nine planets) circuit near Kumbakonam."
  },
  {
    "id": "p255",
    "place": "Thirunageswaram Naganathaswamy Temple",
    "district": "Kumbakonam",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 10.9667,
    "lng": 79.4,
    "best": "Oct-Feb",
    "text": "Rahu shrine of the Navagraha circuit, believed to ease astrological afflictions."
  },
  {
    "id": "p256",
    "place": "Thirukkadaiyur Amirthakadeswarar Temple",
    "district": "Mayiladuthurai",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 11.2333,
    "lng": 79.8167,
    "best": "Oct-Feb",
    "text": "Temple famous for hosting 60th, 70th and 80th wedding-anniversary blessing ceremonies."
  },
  {
    "id": "p257",
    "place": "Thiruvenkadu Swetharanyeswarar Temple",
    "district": "Sirkazhi",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 11.1667,
    "lng": 79.75,
    "best": "Oct-Feb",
    "text": "Ketu shrine of the Navagraha circuit, on the banks of the Kaveri."
  },
  {
    "id": "p258",
    "place": "Mannargudi Rajagopalaswamy Temple",
    "district": "Tiruvarur",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 10.6667,
    "lng": 79.45,
    "best": "Oct-Feb",
    "text": "One of the largest temple complexes in the Kaveri delta, with a vast temple tank."
  },
  {
    "id": "p259",
    "place": "Patteeswaram Durgai Amman Temple",
    "district": "Thanjavur",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 10.9667,
    "lng": 79.4167,
    "best": "Oct-Feb",
    "text": "Popular Devi temple near Kumbakonam known for its Fridays of special prayer."
  },
  {
    "id": "p260",
    "place": "Thiruvavaduthurai Adheenam",
    "district": "Mayiladuthurai",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 11.05,
    "lng": 79.65,
    "best": "Oct-Feb",
    "text": "Historic Shaiva monastery and temple, a centre of Tamil religious scholarship."
  },
  {
    "id": "p261",
    "place": "Mahamaham Tank",
    "district": "Kumbakonam",
    "state": "Tamil Nadu",
    "category": "heritage",
    "lat": 10.96,
    "lng": 79.3833,
    "best": "Oct-Feb",
    "text": "Sacred temple tank at the heart of Kumbakonam, centre of the 12-yearly Mahamaham festival."
  },
  {
    "id": "p262",
    "place": "Poondi Madha Basilica",
    "district": "Thanjavur",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 10.7667,
    "lng": 79.0,
    "best": "Sep-Oct",
    "text": "Major Catholic pilgrimage church known for its annual September festival."
  },
  {
    "id": "p263",
    "place": "Veeraraghava Perumal Temple",
    "district": "Tiruvallur",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 13.1333,
    "lng": 79.9167,
    "best": "Oct-Feb",
    "text": "Ancient Vishnu temple in Tiruvallur town, an important Divya Desam shrine."
  },
  {
    "id": "p264",
    "place": "Tirutani Murugan Temple",
    "district": "Tiruvallur",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 13.1833,
    "lng": 79.6167,
    "best": "Oct-Feb",
    "text": "Hilltop Murugan temple, one of his six sacred abodes, on the Chennai-Tirupati road."
  },
  {
    "id": "p265",
    "place": "Thiruvalangadu Vadaranyeswarar Temple",
    "district": "Tiruvallur",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 13.2333,
    "lng": 79.6167,
    "best": "Oct-Feb",
    "text": "Temple linked with Chidambaram, associated with Shiva's cosmic dance legend."
  },
  {
    "id": "p266",
    "place": "Kottai Mariamman Temple",
    "district": "Salem",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 11.6643,
    "lng": 78.146,
    "best": "Oct-Feb",
    "text": "Popular Devi temple inside Salem's old fort area."
  },
  {
    "id": "p267",
    "place": "Thoppur Ghat Viewpoint",
    "district": "Dharmapuri",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 11.95,
    "lng": 78.1167,
    "best": "Nov-Feb",
    "text": "Winding ghat-road viewpoint on the Salem-Bengaluru highway through forested hills."
  },
  {
    "id": "p268",
    "place": "Rangaswamy Pillar",
    "district": "The Nilgiris",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 11.4667,
    "lng": 76.7,
    "best": "Sep-May",
    "text": "Rock viewpoint near Ooty offering wide views over the Nilgiri plains."
  },
  {
    "id": "p269",
    "place": "Pykara Lake",
    "district": "The Nilgiris",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 11.4833,
    "lng": 76.6167,
    "best": "Sep-May",
    "text": "Boating lake beside Pykara Falls, framed by eucalyptus forest."
  },
  {
    "id": "p270",
    "place": "Botanical Garden, Coonoor (Sim's Park)",
    "district": "The Nilgiris",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 11.3489,
    "lng": 76.7936,
    "best": "Sep-May",
    "text": "Terraced garden in Coonoor known for its exotic tree collection."
  },
  {
    "id": "p271",
    "place": "Dolphin's Nose",
    "district": "Coonoor",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 11.3167,
    "lng": 76.7833,
    "best": "Sep-May",
    "text": "Rock viewpoint near Coonoor overlooking Catherine Falls and the plains below."
  },
  {
    "id": "p272",
    "place": "Catherine Falls",
    "district": "Coonoor",
    "state": "Tamil Nadu",
    "category": "waterfall",
    "lat": 11.3167,
    "lng": 76.7667,
    "best": "Jun-Sep",
    "text": "Two-tiered waterfall near Coonoor, visible from the Dolphin's Nose viewpoint."
  },
  {
    "id": "p273",
    "place": "Law's Falls",
    "district": "Coonoor",
    "state": "Tamil Nadu",
    "category": "waterfall",
    "lat": 11.3333,
    "lng": 76.8,
    "best": "Jun-Sep",
    "text": "Roadside falls on the old Coonoor-Mettupalayam ghat road."
  },
  {
    "id": "p274",
    "place": "Vandiyur Mariamman Teppakulam",
    "district": "Madurai",
    "state": "Tamil Nadu",
    "category": "heritage",
    "lat": 9.9,
    "lng": 78.1333,
    "best": "Oct-Feb",
    "text": "Large temple tank in Madurai, centre of the annual float festival."
  },
  {
    "id": "p275",
    "place": "Thirumalai Nayak Palace Sound & Light Show",
    "district": "Madurai",
    "state": "Tamil Nadu",
    "category": "heritage",
    "lat": 9.9195,
    "lng": 78.1225,
    "best": "Oct-Mar",
    "text": "Evening sound-and-light retelling of Madurai's history inside the historic palace."
  },
  {
    "id": "p276",
    "place": "Vayalur Murugan Temple",
    "district": "Tiruchirappalli",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 10.75,
    "lng": 78.75,
    "best": "Oct-Feb",
    "text": "Hillside Murugan shrine on the outskirts of Trichy."
  },
  {
    "id": "p277",
    "place": "Uyyakondan Channel Park",
    "district": "Tiruchirappalli",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 10.8,
    "lng": 78.6833,
    "best": "Nov-Feb",
    "text": "Riverside walking park along an ancient Chola-era irrigation channel."
  },
  {
    "id": "p278",
    "place": "Rajagopalaswamy Temple, Mannargudi",
    "district": "Tiruvarur",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 10.6667,
    "lng": 79.45,
    "best": "Oct-Feb",
    "text": "Grand Vishnu temple in Mannargudi, one of the largest in the delta region."
  },
  {
    "id": "p279",
    "place": "Devipattinam (Navapashanam)",
    "district": "Ramanathapuram",
    "state": "Tamil Nadu",
    "category": "heritage",
    "lat": 9.3833,
    "lng": 78.8667,
    "best": "Nov-Feb",
    "text": "Coastal site with nine sacred stones in the sea, linked to the Ramayana legend."
  },
  {
    "id": "p280",
    "place": "Ramanathapuram Palace (Sethupathi Palace)",
    "district": "Ramanathapuram",
    "state": "Tamil Nadu",
    "category": "heritage",
    "lat": 9.3667,
    "lng": 78.8333,
    "best": "Nov-Feb",
    "text": "19th-century palace of the Sethupathi rulers of Ramnad."
  },
  {
    "id": "p281",
    "place": "Sanguthurai Beach",
    "district": "Kanyakumari",
    "state": "Tamil Nadu",
    "category": "beach",
    "lat": 8.0667,
    "lng": 77.5667,
    "best": "Nov-Feb",
    "text": "Small, calmer beach near Kanyakumari town, popular with local families."
  },
  {
    "id": "p282",
    "place": "Thiruvattar Adikesava Perumal Temple",
    "district": "Kanyakumari",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 8.3167,
    "lng": 77.2667,
    "best": "Oct-Feb",
    "text": "One of the oldest Vishnu temples in South India, with a rare reclining deity carved from lime mortar."
  },
  {
    "id": "p283",
    "place": "Manakudy Estuary",
    "district": "Kanyakumari",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 8.1167,
    "lng": 77.5167,
    "best": "Nov-Feb",
    "text": "Backwater estuary near Kanyakumari popular for birdwatching."
  },
  {
    "id": "p284",
    "place": "Courtallam Five Falls",
    "district": "Tenkasi",
    "state": "Tamil Nadu",
    "category": "waterfall",
    "lat": 8.925,
    "lng": 77.28,
    "best": "Jun-Sep",
    "text": "Cluster of five separate falls making up the wider Courtallam waterfalls area."
  },
  {
    "id": "p285",
    "place": "Kadamba Falls",
    "district": "Tenkasi",
    "state": "Tamil Nadu",
    "category": "waterfall",
    "lat": 8.955,
    "lng": 77.305,
    "best": "Jun-Sep",
    "text": "Smaller falls near the Kutralanathar temple, less crowded than the main falls."
  },
  {
    "id": "p286",
    "place": "Gingee Fort Sound & Light Show",
    "district": "Villupuram",
    "state": "Tamil Nadu",
    "category": "heritage",
    "lat": 12.2547,
    "lng": 79.4142,
    "best": "Nov-Feb",
    "text": "Evening light show narrating the history of the 'Troy of the East' hill fort."
  },
  {
    "id": "p287",
    "place": "Auroville Matrimandir viewpoint",
    "district": "Villupuram",
    "state": "Tamil Nadu",
    "category": "heritage",
    "lat": 12.0068,
    "lng": 79.8099,
    "best": "Nov-Feb",
    "text": "Golden geodesic meditation structure at the heart of the Auroville international township."
  },
  {
    "id": "p288",
    "place": "Veeranam Lake",
    "district": "Cuddalore",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 11.45,
    "lng": 79.4833,
    "best": "Nov-Feb",
    "text": "Ancient man-made lake dating to Chola times, a major water source for Chennai."
  },
  {
    "id": "p289",
    "place": "Vellore Government Museum",
    "district": "Vellore",
    "state": "Tamil Nadu",
    "category": "museum",
    "lat": 12.9167,
    "lng": 79.1325,
    "best": "Nov-Feb",
    "text": "Small museum inside Vellore Fort displaying regional artefacts and history."
  },
  {
    "id": "p290",
    "place": "Jalakandeswarar Temple, Vellore Fort",
    "district": "Vellore",
    "state": "Tamil Nadu",
    "category": "temple",
    "lat": 12.9186,
    "lng": 79.1325,
    "best": "Oct-Feb",
    "text": "Vijayanagara-era Shiva temple built inside the walls of Vellore Fort."
  },
  {
    "id": "p291",
    "place": "Yelagiri Lake",
    "district": "Vellore",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 12.5833,
    "lng": 78.6333,
    "best": "Oct-Mar",
    "text": "Small boating lake at the centre of Yelagiri hill station."
  },
  {
    "id": "p292",
    "place": "Punganur Lake",
    "district": "Vellore",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 12.9167,
    "lng": 79.1167,
    "best": "Nov-Feb",
    "text": "Lake beside Vellore Fort, popular for an evening walk."
  },
  {
    "id": "p293",
    "place": "San Thome Basilica",
    "district": "Chennai",
    "state": "Tamil Nadu",
    "category": "heritage",
    "lat": 13.0336,
    "lng": 80.2775,
    "best": "Nov-Feb",
    "text": "Neo-Gothic basilica built over the tomb of the apostle St. Thomas."
  },
  {
    "id": "p294",
    "place": "Valluvar Kottam",
    "district": "Chennai",
    "state": "Tamil Nadu",
    "category": "heritage",
    "lat": 13.0538,
    "lng": 80.2425,
    "best": "Nov-Feb",
    "text": "Memorial to the Tamil poet Thiruvalluvar, shaped like a temple chariot."
  },
  {
    "id": "p295",
    "place": "Semmozhi Poonga",
    "district": "Chennai",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 13.0364,
    "lng": 80.2517,
    "best": "Nov-Feb",
    "text": "Botanical garden in the middle of Chennai city, a green break from traffic."
  },
  {
    "id": "p296",
    "place": "Theosophical Society Gardens",
    "district": "Chennai",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 13.0186,
    "lng": 80.2664,
    "best": "Nov-Feb",
    "text": "Riverside gardens in Adyar with one of the widest banyan trees in the world."
  },
  {
    "id": "p297",
    "place": "Black Thunder Amusement Park",
    "district": "Coimbatore",
    "state": "Tamil Nadu",
    "category": "adventure",
    "lat": 10.6167,
    "lng": 77.0333,
    "best": "Nov-Feb",
    "text": "Water and amusement park at the base of the Anamalai hills near Mettupalayam."
  },
  {
    "id": "p298",
    "place": "Kotagiri Viewpoints (Catherine Falls area)",
    "district": "The Nilgiris",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 11.4167,
    "lng": 76.85,
    "best": "Sep-May",
    "text": "Cluster of scenic lookouts and tea-estate roads around Kotagiri town."
  },
  {
    "id": "p299",
    "place": "Amirthi Falls",
    "district": "Vellore",
    "state": "Tamil Nadu",
    "category": "waterfall",
    "lat": 12.7333,
    "lng": 78.7667,
    "best": "Jun-Sep",
    "text": "Small forest waterfall beside the Amirthi zoological park near Vellore."
  },
  {
    "id": "p300",
    "place": "Elliot's Beach Lighthouse",
    "district": "Chennai",
    "state": "Tamil Nadu",
    "category": "heritage",
    "lat": 13.0,
    "lng": 80.2717,
    "best": "Nov-Feb",
    "text": "Small lighthouse on Besant Nagar's Elliot's Beach, a popular evening landmark."
  },
  {
    "id": "p301",
    "place": "Kanyakumari Sunset Point",
    "district": "Kanyakumari",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 8.0783,
    "lng": 77.5385,
    "best": "Nov-Feb",
    "text": "Popular viewpoint at India's southern tip where sunrise and sunset can both be watched over the sea."
  },
  {
    "id": "p302",
    "place": "Kodaikanal Bryant Park",
    "district": "Dindigul",
    "state": "Tamil Nadu",
    "category": "nature",
    "lat": 10.2417,
    "lng": 77.4869,
    "best": "Sep-May",
    "text": "Landscaped botanical park beside Kodaikanal Lake, known for its annual flower show."
  },
  {
    "id": "p303",
    "place": "Chettinad Athangudi Tile Villages",
    "district": "Sivaganga",
    "state": "Tamil Nadu",
    "category": "heritage",
    "lat": 10.06,
    "lng": 78.81,
    "best": "Oct-Feb",
    "text": "Cluster of Chettinad villages famous for handmade cement floor tiles and mansion architecture."
  }
];
